export const Types = {
  abrakleur: {
    displayName: 'Abrakleur',
    type: 'mob',
    mob: 'enderman',
    equipments: {
      main_hand: { type: 'menitrass_100', count: 1 },
    },
    xp: 540,
    loots: [
      { item: 'coin', chance: 0.01 },
      { item: 'coin', chance: 0.01 },
      { item: 'bronze_coin', chance: 0.05 },
      { item: 'bronze_coin', chance: 0.05 },
      { item: 'bronze_coin', chance: 0 },
      { item: 'trekker_eye', chance: 0.01 },
      { item: 'magma_stone', chance: 0.01 },
    ],
    speed: 0.35,
    health: 1500,
    damage: 120,
    sounds: {
      say: 'roar1',
      hit: 'mob.endermen.hit',
      death: 'mob.endermen.death',
    },
  },
  centenary_abrakleur: {
    displayName: 'Abrakleur Centenaire',
    type: 'mob',
    mob: 'enderman',
    xp: 800,
    loots: [
      { item: 'gold_coin', chance: 0.02 },
      { item: 'coin', chance: 0.05 },
      { item: 'coin', chance: 0.05 },
      { item: 'trekker_eye', chance: 0.08 },
      { item: 'magma_stone', chance: 0.5 },
    ],
    speed: 0.35,
    health: 1800,
    damage: 0,
    sounds: {
      say: 'roar1',
      hit: 'mob.endermen.hit',
      death: 'mob.endermen.death',
    },
  },
  atrophy_ankre: {
    displayName: 'Ankre Atrophié',
    type: 'mob',
    mob: 'squid',
    xp: 50,
    loots: [
      { item: 'thick_ink', chance: 0.01 },
      { item: 'ink_powder', chance: 0.02 },
      { item: 'ink_powder', chance: 0.02 },
      { item: 'bronze_coin', chance: 0.05 },
      { item: 'bronze_coin', chance: 0.05 },
    ],
    speed: 0.25,
    health: 70,
    damage: 20,
    sounds: {
      say: 'ankresay',
      hit: 'ankrehit',
      death: 'ankresay',
    },
  },
  harpoon_ankre: {
    displayName: 'Ankre Harpon',
    type: 'mob',
    mob: 'squid',
    xp: 200,
    loots: [
      { item: 'thick_ink', chance: 0.05 },
      { item: 'ink_powder', chance: 0.01 },
      { item: 'ink_powder', chance: 0.01 },
      { item: 'bronze_coin', chance: 0.05 },
    ],
    speed: 0.35,
    health: 400,
    damage: 70,
    sounds: {
      say: 'ankresay',
      hit: 'ankrehit',
      death: 'ankresay',
    },
  },
  depths_ankre: {
    displayName: 'Ankre des Profondeurs',
    type: 'mob',
    mob: 'squid',
    xp: 380,
    loots: [
      { item: 'ink_powder', chance: 0.05 },
      { item: 'coin', chance: 0.02 },
      { item: 'magma_stone', chance: 0.1 },
    ],
    speed: 0.9,
    health: 800,
    damage: 150,
    sounds: {
      say: 'ankresay',
      hit: 'ankrehit',
      death: 'ankresay',
    },
  },
  venerable_ankre: {
    displayName: 'Ankre Vénérables',
    type: 'mob',
    mob: 'squid',
    xp: 650,
    loots: [
      { item: 'thick_ink', chance: 0.2 },
      { item: 'ink_powder', chance: 0.05 },
      { item: 'ink_powder', chance: 0.05 },
      { item: 'coin', chance: 0.02 },
    ],
    speed: 0.9,
    health: 1300,
    damage: 260,
    sounds: {
      say: 'ankresay',
      hit: 'ankrehit',
      death: 'ankresay',
    },
  },
  hungry_arakne: {
    displayName: 'Arakne Affamée',
    type: 'mob',
    mob: 'cave_spider',
    xp: 550,
    loots: [
      { item: 'low_venom', chance: 0.15 },
      { item: 'arakne_egg', chance: 0.02 },
      { item: 'coin', chance: 0.01 },
      { item: 'arakne_egg', chance: 0.05 },
      { item: 'magma_stone', chance: 0.05 },
    ],
    speed: 0.4,
    health: 1000,
    damage: 180,
    sounds: {
      say: 'mob.spider.say',
      hit: 'mob.spider.say',
      death: 'mob.spider.death',
      step: 'mob.spider.step',
    },
  },
  elven_arakne: {
    displayName: 'Arakne Elfique',
    type: 'mob',
    mob: 'spider',
    xp: 1300,
    loots: [
      { item: 'low_venom', chance: 0.3 },
      { item: 'effective_venom', chance: 0.05 },
      { item: 'magma_stone', chance: 0.02 },
      { item: 'magma_stone', chance: 0.01 },
      { item: 'porous_cocoons', chance: 0.02 },
      { item: 'porous_cocoons', chance: 0.02 },
      { item: 'porous_cocoons', chance: 0.02 },
    ],
    speed: 0.45,
    health: 2000,
    damage: 350,
    sounds: {
      say: 'mob.spider.say',
      hit: 'mob.spider.say',
      death: 'mob.spider.death',
      step: 'mob.spider.step',
    },
  },
  harmless_arakne: {
    displayName: 'Arakne Innofensive',
    type: 'mob',
    mob: 'cave_spider',
    xp: 12,
    loots: [
      { item: 'low_venom', chance: 0.01 },
      { item: 'arakne_egg', chance: 0.01 },
      { item: 'arakne_egg', chance: 0.01 },
      { item: 'bronze_coin', chance: 0.01 },
    ],
    speed: 0.35,
    health: 15,
    damage: 4,
    sounds: {
      say: 'mob.spider.say',
      hit: 'mob.spider.say',
      death: 'mob.spider.death',
      step: 'mob.spider.step',
    },
  },
  darker_arakne: {
    displayName: 'Arakne Sombre',
    type: 'mob',
    mob: 'spider',
    xp: 600,
    loots: [
      { item: 'low_venom', chance: 0.15 },
      { item: 'effective_venom', chance: 0.01 },
      { item: 'arakne_egg', chance: 0.05 },
      { item: 'coin', chance: 0.02 },
      { item: 'arakne_egg', chance: 0.05 },
      { item: 'porous_cocoons', chance: 0.02 },
    ],
    speed: 0.45,
    health: 1100,
    damage: 235,
    sounds: {
      say: 'mob.spider.say',
      hit: 'mob.spider.say',
      death: 'mob.spider.death',
      step: 'mob.spider.step',
    },
  },
  darkness_archer: {
    displayName: 'Archer des Ténèbres',
    type: 'mob',
    mob: 'zombified_piglin',
    xp: 1900,
    loots: [
      { item: 'intermonde_brick', chance: 0.09 },
      { item: 'temporal_powder', chance: 0.09 },
    ],
    speed: 0.3,
    health: 2600,
    damage: 260,
    sounds: {
      say: 'mob.zombiepig.zpig',
      hit: 'mob.zombiepig.zpighurt',
      death: 'mob.zombiepig.zpigdeath',
    },
  },
  cannibal: {
    displayName: 'Cannibale',
    type: 'mob',
    mob: 'villager',
    xp: 500,
    loots: [
      { item: 'cannibal_steak', chance: 0.06 },
      { item: 'coin', chance: 0.01 },
      { item: 'coin', chance: 0.01 },
      { item: 'magma_stone', chance: 0.05 },
      { item: 'magma_stone', chance: 0.02 },
    ],
    speed: 0.37,
    health: 920,
    damage: 190,
    sounds: {
      say: 'mob.villager.idle',
      hit: 'mob.villager.hit',
      death: 'mob.villager.death',
    },
  },
  cerbere: {
    displayName: 'Cerbère',
    type: 'mob',
    mob: 'wolf',
    xp: 2350,
    loots: [
      { item: 'temporal_powder', chance: 0.09 },
      { item: 'intermonde_brick', chance: 0.09 },
    ],
    speed: 0.4,
    health: 6000,
    sounds: {
      say: 'mob.wolf.howl',
      hit: 'mob.wolf.hurt',
      death: 'mob.wolf.death',
      step: 'mob.wolf.step',
    },
  },
  shaman: {
    displayName: 'Chaman',
    type: 'mob',
    mob: 'villager',
    xp: 300,
    loots: [
      { item: 'shaman_powder', chance: 0.1 },
      { item: 'standard_rope', chance: 0.05 },
      { item: 'coin', chance: 0.05 },
      { item: 'bronze_coin', chance: 0.02 },
      { item: 'bronze_coin', chance: 0.02 },
      { item: 'magma_stone', chance: 0.05 },
      { item: 'satchel_of_the_sauvageon', chance: 0.2 },
      { item: 'coin', chance: 1 },
    ],
    speed: 0.3,
    health: 800,
    damage: 70,
    sounds: {
      say: 'mob.villager.idle',
      hit: 'mob.villager.hit',
      death: 'mob.villager.death',
    },
  },
  war_chief: {
    displayName: 'Chef de Guerre',
    type: 'mob',
    mob: 'villager',
    xp: 650,
    loots: [
      { item: 'coin', chance: 0.02 },
      { item: 'magma_stone', chance: 0.01 },
      { item: 'magma_stone', chance: 0.05 },
      { item: 'satchel_of_the_sauvageon', chance: 0.2 },
      { item: 'satchel_of_the_sauvageon', chance: 0.2 },
    ],
    speed: 0.35,
    health: 1600,
    damage: 220,
    sounds: {
      say: 'mob.villager.idle',
      hit: 'mob.villager.hit',
      death: 'mob.villager.death',
    },
  },
  hades_horse: {
    displayName: 'Krizan',
    type: 'mob',
    mob: 'horse',
    speed: 0.2,
    health: 25000,
    sounds: {
      say: '',
      hit: 'mob.irongolem.hit',
      death: 'mob.irongolem.death',
      step: 'mob.wolf.step',
    },
  },
  claqueur: {
    displayName: 'Claqueur',
    type: 'mob',
    mob: 'zombie',
    xp: 110,
    loots: [
      { item: 'holed_vest', chance: 0.1 },
      { item: 'bronze_coin', chance: 1 },
      { item: 'bronze_coin', chance: 0.33 },
    ],
    // for lvl8
    speed: 0.45, // TODO: 0.41 for lvl 6
    health: 380, // TODO: 150 for lvl 6
    damage: 50, // TODO: 30 for lvl 6
    sounds: {
      say: 'mob.sheep.step',
      hit: 'claqueurhit',
      death: 'claqueurdeath',
      step: 'mob.cow.step',
    },
  },
  decomposed_claqueur: {
    displayName: 'Claqueur Décomposé',
    type: 'mob',
    mob: 'zombie',
    xp: 180,
    loots: [
      { item: 'infected_skull', chance: 0.03 },
      { item: 'holed_vest', chance: 0.15 },
      { item: 'bronze_coin', chance: 1 },
      { item: 'bronze_coin', chance: 0.5 },
    ],
    speed: 0.4,
    health: 450,
    damage: 65,
    sounds: {
      say: 'mob.sheep.step',
      hit: 'claqueurhit',
      death: 'claqueurdeath',
      step: 'mob.cow.step',
    },
  },
  dark_claqueur: {
    displayName: 'Claqueur Sombre',
    type: 'mob',
    mob: 'zombie',
    xp: 700,
    loots: [
      { item: 'holed_vest', chance: 0.25 },
      { item: 'infected_skull', chance: 0.1 },
      { item: 'basic_vest', chance: 0.01 },
      { item: 'coin', chance: 0.35 },
      { item: 'bronze_coin', chance: 0.05 },
      { item: 'magma_stone', chance: 0.05 },
      { item: 'magma_stone', chance: 0.02 },
    ],
    speed: 0.45,
    health: 1300,
    damage: 250,
    sounds: {
      say: 'mob.sheep.step',
      hit: 'claqueurhit',
      death: 'claqueurdeath',
      step: 'mob.cow.step',
    },
  },
  tormented_skull: {
    displayName: 'Crane Tourmenté',
    type: 'mob',
    mob: 'skeleton',
    xp: 200,
    loots: [
      { item: 'infected_skull', chance: 0.03 },
      { item: 'bronze_coin', chance: 0.05 },
    ],
    speed: 0.45,
    health: 400,
    damage: 55,
    sounds: {
      say: 'mob1',
      hit: 'mob.ghast.scream',
      death: 'mob.zombie.death',
      step: 'mob.skeleton.step',
    },
  },
  hungry_demon: {
    displayName: 'Démon Affamé',
    type: 'mob',
    mob: 'zombified_piglin',
    xp: 2200,
    loots: [
      { item: 'sacred_fire', chance: 0.02 },
      { item: 'intermonde_brick', chance: 0.02 },
      { item: 'intermonde_brick', chance: 0.02 },
      { item: 'temporal_powder', chance: 0.02 },
    ],
    speed: 0.38,
    health: 4350,
    damage: 400,
    sounds: {
      say: 'mob.zombiepig.zpig',
      hit: 'mob.zombiepig.zpigangry',
      death: 'mob.zombiepig.zpigdeath',
    },
  },
  caverns_devourer: {
    displayName: 'Dévoreuse des Cavernes',
    type: 'mob',
    mob: 'spider',
    xp: 220,
    loots: [
      { item: 'bronze_coin', chance: 0.08 },
      { item: 'bronze_coin', chance: 0.5 },
      { item: 'bronze_coin', chance: 0.05 },
      { item: 'arakne_egg', chance: 0.2 },
      { item: 'arakne_egg', chance: 0.2 },
    ],
    speed: 0.35,
    health: 880,
    damage: 95,
    sounds: {
      say: 'mob.spider.say',
      hit: 'mob.spider.say',
      death: 'mob.spider.death',
      step: 'mob.spider.step',
    },
  },
  hairy_devourer: {
    displayName: 'Dévoreuse Velue',
    type: 'mob',
    mob: 'spider',
    xp: 75,
    loots: [
      { item: 'low_venom', chance: 0.02 },
      { item: 'arakne_egg', chance: 0.3 },
      { item: 'arakne_egg', chance: 0.3 },
    ],
    speed: 0.3,
    health: 450,
    damage: 60,
    sounds: {
      say: 'mob.spider.say',
      hit: 'mob.spider.say',
      death: 'mob.spider.death',
      step: 'mob.spider.step',
    },
  },
  draugr: {
    displayName: 'Draugr',
    type: 'mob',
    mob: 'skeleton',
    xp: 50,
    loots: [
      { item: 'rusty_draugr_helmet', chance: 0.01 },
      { item: 'broken_bone', chance: 0.01 },
      { item: 'broken_bone', chance: 0.01 },
      { item: 'broken_bone', chance: 0.01 },
      { item: 'broken_bone', chance: 0.01 },
      { item: 'bronze_coin', chance: 0.01 },
      { item: 'bronze_coin', chance: 0.01 },
    ],
    speed: 0.45,
    health: 80,
    damage: 30,
    sounds: {
      say: 'mob.skeleton.say',
      hit: 'mob.skeleton.hurt',
      death: 'mob.skeleton.death',
      step: 'mob.skeleton.step',
    },
  },
  antic_draugr: {
    displayName: 'Draugr Antique',
    type: 'mob',
    mob: 'skeleton',
    xp: 400,
    loots: [
      { item: 'rusty_draugr_helmet', chance: 0.08 },
      { item: 'broken_bone', chance: 0.02 },
      { item: 'coin', chance: 0.05 },
      { item: 'bronze_coin', chance: 0.08 },
    ],
    speed: 0.35,
    health: 700,
    damage: 150,
    sounds: {
      say: 'mob.skeleton.say',
      hit: 'mob.skeleton.hurt',
      death: 'mob.skeleton.death',
      step: 'mob.skeleton.step',
    },
  },
  archer_draugr: {
    displayName: 'Draugr Archer',
    type: 'mob',
    mob: 'skeleton',
    xp: 80,
    loots: [
      { item: 'rusty_draugr_helmet', chance: 0.03 },
      { item: 'bronze_coin', chance: 0.02 },
      { item: 'bronze_coin', chance: 0.02 },
      { item: 'broken_bone', chance: 0.02 },
    ],
    speed: 0.3,
    health: 130,
    damage: 27,
    sounds: {
      say: 'mob.skeleton.say',
      hit: 'mob.skeleton.hurt',
      death: 'mob.skeleton.death',
      step: 'mob.skeleton.step',
    },
  },
  lancer_draugr: {
    displayName: 'Draugr Lancier',
    type: 'mob',
    mob: 'skeleton',
    xp: 450,
    loots: [
      { item: 'rusty_draugr_helmet', chance: 0.07 },
      { item: 'bronze_coin', chance: 0.08 },
      { item: 'bronze_coin', chance: 0.08 },
      { item: 'bronze_coin', chance: 0.08 },
    ],
    speed: 0.2,
    health: 550,
    damage: 60,
    sounds: {
      say: 'mob.skeleton.say',
      hit: 'mob.skeleton.hurt',
      death: 'mob.silverfish.kill',
      step: 'mob.skeleton.step',
    },
  },
  possesses_draugr: {
    displayName: 'Draugr Possédé',
    type: 'mob',
    mob: 'skeleton',
    xp: 200,
    loots: [
      { item: 'rusty_draugr_helmet', chance: 0.05 },
      { item: 'ice_crystal', chance: 0.05 },
      { item: 'bronze_coin', chance: 1 },
    ],
    speed: 0.4,
    health: 480,
    damage: 48,
    sounds: {
      say: 'mob.skeleton.say',
      hit: 'mob.blaze.death',
      death: 'mob.skeleton.death',
      step: 'mob.skeleton.step',
    },
  },
  insolent_spirit: {
    displayName: 'Esprit Insolent',
    type: 'mob',
    mob: 'blaze',
    xp: 1000,
    loots: [
      { item: 'intermonde_brick', chance: 0.02 },
      { item: 'intermonde_brick', chance: 0.02 },
    ],
    speed: 0.15,
    health: 2100,
    damage: 250,
    sounds: {
      say: 'mob.blaze.breathe',
      hit: 'mob.blaze.hit',
      death: 'mob.blaze.death',
    },
  },
  snow_spirit: {
    displayName: 'Esprit des Glaces',
    type: 'mob',
    mob: 'skeleton',
    xp: 550,
    loots: [
      { item: 'ice_crystal', chance: 0.01 },
      { item: 'coin', chance: 0.02 },
      { item: 'coin', chance: 0.05 },
      { item: 'magma_stone', chance: 0.01 },
      { item: 'magma_stone', chance: 0.05 },
    ],
    speed: 0.3,
    health: 1300,
    damage: 150,
    sounds: {
      say: 'mob1',
      hit: 'mob.ghast.scream',
      death: 'mob.zombie.death',
      step: 'mob.skeleton.step',
    },
  },
  abyss_guardian: {
    displayName: 'Gardien des Abysses',
    type: 'mob',
    mob: 'zombified_piglin',
    xp: 1200,
    loots: [{ item: 'intermonde_brick', chance: 0.09 }],
    speed: 0.23,
    health: 2600,
    damage: 320,
    sounds: {
      say: 'mob.zombiepig.zpig',
      hit: 'mob.zombiepig.zpighurt',
      death: 'mob.zombiepig.zpigdeath',
    },
  },
  wolf_guardian: {
    displayName: 'Guerrier Loup',
    type: 'mob',
    mob: 'zombie',
    xp: 55,
    loots: [
      { item: 'frozen_face', chance: 0.03 },
      { item: 'ice_crystal', chance: 0.01 },
      { item: 'ice_crystal', chance: 0.01 },
      { item: 'ice_crystal', chance: 0.01 },
      { item: 'bronze_coin', chance: 0.02 },
      { item: 'bronze_coin', chance: 0.02 },
    ],
    speed: 0.37,
    health: 90,
    damage: 25,
    sounds: {
      say: 'mob.wolf.growl',
      hit: 'mob.wolf.hurt',
      death: 'mob.zombie.death',
    },
  },
  infected: {
    displayName: 'Infécté',
    type: 'mob',
    mob: 'zombie',
    xp: 60,
    loots: [
      { item: 'old_shorts', chance: 0.04 },
      { item: 'bronze_coin', chance: 0.02 },
    ],
    // for lvl 5
    speed: 0.38, // TODO: 0.25 on lvl 1, 0.33 on lvl 3, 0.3 on lvl 4 ??
    health: 100, // TODO: 12 on lvl 1, 30 on lvl 3, 80 on lvl 4
    damage: 25, // TODO: 5 on lvl 1, 12 on lvl 3, 20 on lvl 4
    sounds: {
      say: 'mob.sheep.step',
      hit: 'claqueurhit',
      death: 'claqueurdeath',
      step: 'mob.cow.step',
    },
  },
  young_wolf: {
    displayName: 'Jeune Loup',
    type: 'mob',
    mob: 'wolf',
    xp: 10,
    loots: [
      { item: 'wolf_tear', chance: 0.05 },
      { item: 'bronze_coin', chance: 0.05 },
    ],
    speed: 0.3,
    health: 25,
    damage: 5,
    sounds: {
      say: 'mob.wolf.howl',
      hit: 'mob.wolf.hurt',
      death: 'mob.wolf.death',
      step: 'mob.wolf.step',
    },
  },
  young_savage: {
    displayName: 'Jeune Sauvageon',
    type: 'mob',
    mob: 'villager',
    xp: 1,
    loots: [
      { item: 'wooden_sandal', chance: 0.01 },
      { item: 'satchel_of_the_sauvageon', chance: 0.07 },
    ],
    speed: 0.4,
    health: 10,
    sounds: {
      say: 'mob.villager.idle',
      hit: 'mob.villager.hit',
      death: 'mob.villager.death',
    },
  },
  young_poisonous: {
    displayName: 'Jeune Venimeuse',
    type: 'mob',
    mob: 'cave_spider',
    xp: 70,
    loots: [
      { item: 'low_venom', chance: 0.02 },
      { item: 'arakne_egg', chance: 0.15 },
      { item: 'arakne_egg', chance: 0.15 },
      { item: 'bronze_coin', chance: 0.05 },
      { item: 'bronze_coin', chance: 0.05 },
    ],
    speed: 0.25,
    health: 100,
    damage: 20,
    sounds: {
      say: 'mob.spider.say',
      hit: 'mob.spider.say',
      death: 'mob.spider.death',
      step: 'mob.spider.step',
    },
  },
  wolf: {
    displayName: 'Loup',
    type: 'mob',
    mob: 'wolf',
    xp: 10,
    loots: [
      { item: 'fragile_wolf_tooth', chance: 0.01 },
      { item: 'wolf_tear', chance: 0.01 },
      { item: 'wolf_tear', chance: 0.05 },
      { item: 'bronze_coin', chance: 0.05 },
      { item: 'bronze_coin', chance: 0.05 },
    ],
    speed: 0.35,
    health: 45,
    damage: 12,
    sounds: {
      say: 'mob.wolf.howl',
      hit: 'mob.wolf.hurt',
      death: 'mob.wolf.death',
      step: 'mob.wolf.step',
    },
  },
  hungry_wolf: {
    displayName: 'Loup Affamé',
    type: 'mob',
    mob: 'wolf',
    xp: 70,
    loots: [
      { item: 'fragile_wolf_tooth', chance: 0.01 },
      { item: 'wolf_tear', chance: 0.01 },
      { item: 'wolf_tear', chance: 0.01 },
      { item: 'wolf_tear', chance: 0.01 },
    ],
    speed: 0.4,
    health: 150,
    damage: 22,
    sounds: {
      say: 'mob.wolf.howl',
      hit: 'mob.wolf.hurt',
      death: 'mob.wolf.death',
      step: 'mob.wolf.step',
    },
  },
  antic_wolf: {
    displayName: 'Loup Antique',
    type: 'mob',
    mob: 'wolf',
    xp: 1800,
    loots: [
      { item: 'magma_stone', chance: 0.02 },
      { item: 'gold_coin', chance: 0.02 },
      { item: 'coin', chance: 0.2 },
      { item: 'running_wolf_tooth', chance: 0.02 },
      { item: 'fragile_wolf_tooth', chance: 0.15 },
    ],
    speed: 0.45,
    health: 2400,
    damage: 400,
    sounds: {
      say: 'mob.wolf.howl',
      hit: 'mob.wolf.hurt',
      death: 'mob.wolf.death',
      step: 'mob.wolf.step',
    },
  },
  white_wolf: {
    displayName: 'Loup Blanc',
    type: 'mob',
    mob: 'wolf',
    xp: 350,
    loots: [
      { item: 'fragile_wolf_tooth', chance: 0.03 },
      { item: 'coin', chance: 0.05 },
      { item: 'jormunld_tear', chance: 0.05 },
      { item: 'bronze_coin', chance: 0.08 },
      { item: 'magma_stone', chance: 0.05 },
    ],
    speed: 0.4,
    health: 600,
    damage: 60,
    sounds: {
      say: 'mob.wolf.howl',
      hit: 'mob.wolf.hurt',
      death: 'mob.wolf.death',
      step: 'mob.wolf.step',
    },
  },
  caverns_wolf: {
    displayName: 'Loup des Cavernes',
    type: 'mob',
    mob: 'wolf',
    xp: 1000,
    loots: [
      { item: 'fragile_wolf_tooth', chance: 0.2 },
      { item: 'running_wolf_tooth', chance: 0.01 },
      { item: 'coin', chance: 0.02 },
      { item: 'magma_stone', chance: 0.01 },
      { item: 'magma_stone', chance: 0.01 },
    ],
    speed: 0.45,
    health: 1400,
    damage: 240,
    sounds: {
      say: 'mob.wolf.howl',
      hit: 'mob.wolf.hurt',
      death: 'mob.wolf.death',
      step: 'mob.wolf.step',
    },
  },
  enraged_wolf: {
    displayName: 'Loup Enragé',
    type: 'mob',
    mob: 'wolf',
    xp: 350,
    loots: [
      { item: 'fragile_wolf_tooth', chance: 0.02 },
      { item: 'wolf_tear', chance: 0.01 },
      { item: 'wolf_tear', chance: 0.01 },
      { item: 'wolf_tear', chance: 0.01 },
      { item: 'bronze_coin', chance: 0.05 },
      { item: 'bronze_coin', chance: 0.05 },
    ],
    speed: 0.45,
    health: 400,
    damage: 40,
    sounds: {
      say: 'mob.wolf.howl',
      hit: 'mob.wolf.hurt',
      death: 'mob.wolf.death',
      step: 'mob.wolf.step',
    },
  },
  she_wolf: {
    displayName: 'Louve',
    type: 'mob',
    mob: 'wolf',
    xp: 350,
    loots: [
      { item: 'fragile_wolf_tooth', chance: 0.06 },
      { item: 'wolf_tear', chance: 0.05 },
      { item: 'magma_stone', chance: 0.01 },
      { item: 'coin', chance: 0.02 },
    ],
    speed: 0.35,
    health: 2000,
    damage: 250,
    sounds: {
      say: 'mob.wolf.howl',
      hit: 'mob.wolf.hurt',
      death: 'mob.wolf.death',
      step: 'mob.wolf.step',
    },
  },
  cub: {
    displayName: 'Louveteau',
    type: 'mob',
    mob: 'wolf',
    xp: 41,
    loots: [
      { item: 'wolf_tear', chance: 0.01 },
      { item: 'wolf_tear', chance: 0.01 },
      { item: 'bronze_coin', chance: 0.01 },
    ],
    speed: 0.3,
    health: 80,
    sounds: {
      say: 'mob.wolf.howl',
      hit: 'mob.wolf.hurt',
      death: 'mob.wolf.death',
      step: 'mob.wolf.step',
    },
  },
  white_walker: {
    displayName: 'Marcheur Blanc',
    type: 'mob',
    mob: 'zombie',
    xp: 140,
    loots: [
      { item: 'frozen_face', chance: 0.02 },
      { item: 'bronze_coin', chance: 1 },
      { item: 'bronze_coin', chance: 0.5 },
      { item: 'magma_stone', chance: 0.01 },
    ],
    speed: 0.3,
    health: 2700,
    damage: 45,
    sounds: {
      say: 'nazgulcry',
      hit: 'nazgulhit',
      death: 'nazguldeath',
    },
  },
  sheep: {
    displayName: 'Mouton de Thebes',
    type: 'mob',
    mob: 'sheep',
    xp: 5,
    loots: [
      { item: 'decomposed_beast_skin', chance: 0.04 },
      { item: 'corn', chance: 0.05 },
      { item: 'corn', chance: 0.05 },
      { item: 'corn', chance: 0.05 },
      { item: 'bronze_coin', chance: 0.05 },
    ],
    speed: 0.23,
    health: 16,
    damage: 4,
    sounds: {
      say: 'mob.sheep.say',
      hit: 'mob.sheep.say',
      death: 'mob.sheep.say',
      step: 'mob.cow.step',
    },
  },
  nephilainaurata: {
    displayName: 'Néphila Inaurata',
    type: 'mob',
    mob: 'spider',
    xp: 350,
    loots: [
      { item: 'low_venom', chance: 0.05 },
      { item: 'bronze_coin', chance: 0.08 },
      { item: 'magma_stone', chance: 0.05 },
    ],
    speed: 0.37,
    health: 800,
    damage: 80,
    sounds: {
      say: 'mob.spider.say',
      hit: 'mob.spider.say',
      death: 'mob.spider.death',
      step: 'mob.spider.step',
    },
  },
  golden_nephile: {
    displayName: 'Néphile Dorée',
    type: 'mob',
    mob: 'spider',
    xp: 180,
    loots: [
      { item: 'low_venom', chance: 0.04 },
      { item: 'bronze_coin', chance: 0.08 },
      { item: 'arakne_egg', chance: 0.5 },
      { item: 'arakne_egg', chance: 0.5 },
    ],
    speed: 0.3,
    health: 650,
    damage: 70,
    sounds: {
      say: 'mob.spider.say',
      hit: 'mob.spider.say',
      death: 'mob.spider.death',
      step: 'mob.spider.step',
    },
  },
  immature_nephile: {
    displayName: 'Néphile Immature',
    type: 'mob',
    mob: 'cave_spider',
    xp: 230,
    loots: [
      { item: 'arakne_egg', chance: 0.3 },
      { item: 'arakne_egg', chance: 0.3 },
      { item: 'bronze_coin', chance: 0.08 },
      { item: 'bronze_coin', chance: 0.08 },
    ],
    speed: 0.3,
    health: 500,
    damage: 50,
    sounds: {
      say: 'mob.spider.say',
      hit: 'mob.spider.say',
      death: 'mob.spider.death',
      step: 'mob.spider.step',
    },
  },
  talus_pig: {
    displayName: 'Porc de Talus',
    type: 'mob',
    mob: 'pig',
    xp: 10,
    loots: [
      { item: 'corn', chance: 0.05 },
      { item: 'corn', chance: 0.05 },
      { item: 'decomposed_beast_skin', chance: 0.04 },
      { item: 'corn', chance: 0.02 },
      { item: 'decomposed_beast_skin', chance: 0.04 },
      { item: 'decomposed_beast_skin', chance: 0.04 },
      { item: 'bronze_coin', chance: 0.01 },
    ],
    speed: 0.25,
    health: 50,
    damage: 15,
    sounds: {
      say: 'mob.pig.say',
      hit: 'mob.pig.say',
      death: 'mob.pig.death',
      step: 'mob.pig.step',
    },
  },
  bamboula_pig: {
    displayName: 'Porc Bamboula',
    type: 'mob',
    mob: 'pig',
    xp: 5,
    loots: [
      { item: 'decomposed_beast_skin', chance: 0.04 },
      { item: 'corn', chance: 0.02 },
      { item: 'bronze_coin', chance: 0.05 },
      { item: 'bronze_coin', chance: 0.05 },
    ],
    speed: 0.25,
    health: 20,
    damage: 7,
    sounds: {
      say: 'mob.pig.say',
      hit: 'mob.pig.say',
      death: 'mob.pig.death',
      step: 'mob.pig.step',
    },
  },
  savannah_pig: {
    displayName: 'Porc de Savanne',
    type: 'mob',
    mob: 'pig',
    xp: 5,
    loots: [
      { item: 'decomposed_beast_skin', chance: 0.04 },
      { item: 'corn', chance: 0.02 },
      { item: 'corn', chance: 0.02 },
      { item: 'bronze_coin', chance: 0.05 },
      { item: 'bronze_coin', chance: 0.05 },
    ],
    speed: 0.25,
    health: 30,
    damage: 10,
    sounds: {
      say: 'mob.pig.say',
      hit: 'mob.pig.say',
      death: 'mob.pig.death',
      step: 'mob.pig.step',
    },
  },
  chicken: {
    displayName: 'Poule',
    type: 'mob',
    mob: 'chicken',
    equipment: {
      main_hand: {
        type: 'menitrass_100',
        count: 1,
      },
    },
    speed: 0.25,
    health: 5,
    sounds: {
      say: 'mob.chicken.say',
      hit: 'mob.chicken.hurt',
      death: 'mob.chicken.hurt',
      step: 'mob.chicken.step',
    },
    xp: 2,
    loots: [
      { item: 'corn', chance: 0.05 },
      { item: 'corn', chance: 0.05 },
      { item: 'feather', chance: 0.01 },
      { item: 'bronze_coin', chance: 0.01 },
    ],
  },
  sick_chicken: {
    displayName: 'Poule Malade',
    type: 'mob',
    mob: 'chicken',
    xp: 3,
    loots: [
      { item: 'corn', chance: 0.05 },
      { item: 'corn', chance: 0.05 },
      { item: 'corn', chance: 0.05 },
      { item: 'feather', chance: 0.01 },
      { item: 'feather', chance: 0.01 },
    ],
    speed: 0.35,
    health: 10,
    damage: 4,
    sounds: {
      say: 'mob.chicken.say',
      hit: 'mob.chicken.hurt',
      death: 'mob.chicken.hurt',
      step: 'mob.chicken.step',
    },
  },
  monk_chicken: {
    displayName: 'Poulet Moîne',
    type: 'mob',
    mob: 'chicken',
    xp: 2,
    loots: [
      { item: 'corn', chance: 0.05 },
      { item: 'corn', chance: 0.05 },
      { item: 'corn', chance: 0.05 },
      { item: 'bronze_coin', chance: 0.05 },
    ],
    speed: 0.3,
    health: 12,
    damage: 4,
    sounds: {
      say: 'mob.chicken.say',
      hit: 'mob.chicken.hurt',
      death: 'mob.chicken.hurt',
      step: 'mob.chicken.step',
    },
  },
  rat: {
    displayName: 'Rat',
    type: 'mob',
    mob: 'silverfish',
    xp: 4,
    loots: [{ item: 'bronze_coin', chance: 0.05 }],
    speed: 0.25,
    health: 20,
    damage: 6,
    sounds: {
      say: 'mob.silverfish.say',
      hit: 'mob.silverfish.hit',
      death: 'mob.silverfish.kill',
      step: 'mob.silverfish.step',
    },
  },
  nordicRat: {
    displayName: 'Rat Nordique',
    type: 'mob',
    mob: 'silverfish',
    xp: 6,
    loots: [
      { item: 'bronze_coin', chance: 0.05 },
      { item: 'bronze_coin', chance: 0.05 },
    ],
    speed: 1.5,
    health: 65,
    damage: 18,
    sounds: {
      say: 'mob.silverfish.say',
      hit: 'mob.silverfish.hit',
      death: 'mob.silverfish.kill',
      step: 'mob.silverfish.step',
    },
  },
  plains_boar: {
    displayName: 'Sanglier des Plaines',
    type: 'mob',
    mob: 'pig',
    xp: 2000,
    loots: [
      { item: 'gold_coin', chance: 0.1 },
      { item: 'coin', chance: 0.05 },
      { item: 'magma_stone', chance: 0.5 },
      { item: 'magma_stone', chance: 0.5 },
      { item: 'standard_animal_skin', chance: 0.5 },
    ],
    speed: 0.55,
    health: 8000,
    damage: 500,
    sounds: {
      say: 'mob.pig.say',
      hit: 'mob.zombiepig.zpighurt',
      death: 'mob.pig.death',
      step: 'mob.pig.step',
    },
  },
  savage: {
    displayName: 'Sauvageon',
    type: 'mob',
    mob: 'villager',
    xp: 1,
    loots: [
      { item: 'wooden_sandal', chance: 0.01 },
      { item: 'satchel_of_the_sauvageon', chance: 0.07 },
      { item: 'bronze_coin', chance: 0.05 },
      { item: 'bronze_coin', chance: 0.05 },
    ],
    speed: 0.25,
    health: 20,
    sounds: {
      say: 'mob.villager.idle',
      hit: 'mob.villager.hit',
      death: 'mob.villager.death',
    },
  },
  aggressive_savage: {
    displayName: 'Sauvageon Agressif',
    type: 'mob',
    mob: 'villager',
    xp: 25,
    loots: [
      { item: 'wooden_sandal', chance: 0.01 },
      { item: 'satchel_of_the_sauvageon', chance: 0.07 },
      { item: 'satchel_of_the_sauvageon', chance: 0.07 },
      { item: 'satchel_of_the_sauvageon', chance: 0.07 },
      { item: 'satchel_of_the_sauvageon', chance: 0.07 },
      { item: 'satchel_of_the_sauvageon', chance: 0.07 },
      { item: 'bronze_coin', chance: 0.01 },
    ],
    speed: 0.3,
    health: 50,
    damage: 15,
    sounds: {
      say: 'mob.villager.idle',
      hit: 'mob.villager.hit',
      death: 'mob.villager.death',
    },
  },
  fallen_savage: {
    displayName: 'Sauvageon Déchu',
    type: 'mob',
    mob: 'villager',
    xp: 70,
    loots: [
      { item: 'wooden_sandal', chance: 0.02 },
      { item: 'bronze_coin', chance: 0.01 },
      { item: 'bronze_coin', chance: 0.01 },
    ],
    speed: 0.3,
    health: 180,
    damage: 20,
    sounds: {
      say: 'mob.villager.idle',
      hit: 'mob.villager.hit',
      death: 'mob.villager.death',
    },
  },
  slinger_savage: {
    displayName: 'Sauvageon Frondeur',
    type: 'mob',
    mob: 'villager',
    xp: 12,
    loots: [
      { item: 'wooden_sandal', chance: 0.01 },
      { item: 'slinger_projectile', chance: 0.01 },
      { item: 'satchel_of_the_sauvageon', chance: 0.07 },
      { item: 'satchel_of_the_sauvageon', chance: 0.07 },
      { item: 'satchel_of_the_sauvageon', chance: 0.07 },
      { item: 'bronze_coin', chance: 0.05 },
      { item: 'bronze_coin', chance: 0.05 },
    ],
    speed: 0.3,
    health: 23,
    damage: 4,
    sounds: {
      say: 'mob.villager.idle',
      hit: 'mob.villager.hit',
      death: 'mob.villager.death',
    },
  },
  fertile_savagene: {
    displayName: 'Sauvageonne Féconde',
    type: 'mob',
    mob: 'villager',
    xp: 200,
    loots: [
      { item: 'wooden_sandal', chance: 0.04 },
      { item: 'satchel_of_the_sauvageon', chance: 0.02 },
      { item: 'satchel_of_the_sauvageon', chance: 0.02 },
      { item: 'satchel_of_the_sauvageon', chance: 0.02 },
      { item: 'satchel_of_the_sauvageon', chance: 0.02 },
      { item: 'satchel_of_the_sauvageon', chance: 0.02 },
      { item: 'bronze_coin', chance: 0.02 },
      { item: 'bronze_coin', chance: 0.02 },
      { item: 'bronze_coin', chance: 0.01 },
      { item: 'bronze_coin', chance: 0.01 },
    ],
    speed: 0.3,
    health: 500,
    damage: 55,
    sounds: {
      say: 'mob.villager.idle',
      hit: 'mob.villager.hit',
      death: 'mob.villager.death',
    },
  },
  savagene: {
    displayName: 'Sauvageonne',
    type: 'mob',
    mob: 'villager',
    xp: 115,
    loots: [
      { item: 'wooden_sandal', chance: 0.03 },
      { item: 'satchel_of_the_sauvageon', chance: 0.02 },
      { item: 'satchel_of_the_sauvageon', chance: 0.02 },
      { item: 'satchel_of_the_sauvageon', chance: 0.02 },
      { item: 'bronze_coin', chance: 0.02 },
      { item: 'bronze_coin', chance: 0.02 },
    ],
    speed: 0.3,
    health: 185,
    damage: 30,
    sounds: {
      say: 'mob.villager.idle',
      hit: 'mob.villager.hit',
      death: 'mob.villager.death',
    },
  },
  savage_perjurer: {
    displayName: 'Sauvageon Parjure',
    type: 'mob',
    mob: 'villager',
    xp: 2,
    loots: [
      { item: 'wooden_sandal', chance: 0.01 },
      { item: 'satchel_of_the_sauvageon', chance: 0.07 },
      { item: 'satchel_of_the_sauvageon', chance: 0.07 },
      { item: 'bronze_coin', chance: 0.05 },
    ],
    speed: 0.3,
    health: 15,
    damage: 3,
    sounds: {
      say: 'mob.villager.idle',
      hit: 'mob.villager.hit',
      death: 'mob.villager.death',
    },
  },
  darkness_soldier: {
    displayName: 'Soldat des Ténèbres',
    type: 'mob',
    mob: 'zombified_piglin',
    xp: 2000,
    loots: [
      { item: 'temporal_powder', chance: 0.02 },
      { item: 'temporal_powder', chance: 0.09 },
    ],
    speed: 0.35,
    health: 3200,
    damage: 350,
    sounds: {
      say: 'mob.zombiepig.zpig',
      hit: 'mob.zombiepig.zpighurt',
      death: 'mob.zombiepig.zpigdeath',
    },
  },
  skeleton: {
    displayName: 'Squelette',
    type: 'mob',
    mob: 'skeleton',
    equipment: {
      main_hand: {
        type: 'menitrass_100',
        count: 1,
      },
      chestplate: {
        type: 'numen_armor',
        count: 1,
      },
    },
    speed: 0.3,
    health: 90,
    damage: 20,
    sounds: {
      say: 'mob.skeleton.say',
      hit: 'mob.skeleton.hurt',
      death: 'mob.skeleton.death',
      step: 'mob.skeleton.step',
    },
    xp: 35,
    loots: [
      { item: 'old_shorts', chance: 0.01 },
      { item: 'infected_skull', chance: 0.01 },
      { item: 'broken_bone', chance: 0.01 },
      { item: 'broken_bone', chance: 0.01 },
      { item: 'broken_bone', chance: 0.01 },
      { item: 'bronze_coin', chance: 0.01 },
    ],
  },
  brittle_skeleton: {
    displayName: 'Squelette Fragile',
    type: 'mob',
    mob: 'skeleton',
    xp: 20,
    loots: [
      { item: 'old_shorts', chance: 0.01 },
      { item: 'infected_skull', chance: 0.01 },
      { item: 'broken_bone', chance: 0.01 },
      { item: 'bronze_coin', chance: 0.05 },
    ],
    speed: 0.25,
    health: 20,
    damage: 10,
    sounds: {
      say: 'mob.skeleton.say',
      hit: 'mob.skeleton.hurt',
      death: 'mob.skeleton.death',
      step: 'mob.skeleton.step',
    },
  },
  nordic_skeleton: {
    displayName: 'Squelette Nordique',
    type: 'mob',
    mob: 'skeleton',
    xp: 110,
    loots: [
      { item: 'infected_skull', chance: 0.02 },
      { item: 'old_shorts', chance: 0.02 },
      { item: 'frozen_face', chance: 0.02 },
      { item: 'broken_bone', chance: 0.02 },
      { item: 'broken_bone', chance: 0.02 },
      { item: 'bronze_coin', chance: 1 },
      { item: 'bronze_coin', chance: 0.33 },
    ],
    speed: 0.35,
    health: 240,
    damage: 35,
    sounds: {
      say: 'mob.skeleton.say',
      hit: 'mob.skeleton.hurt',
      death: 'mob.skeleton.death',
      step: 'mob.skeleton.step',
    },
  },
  agressive_tegenarian: {
    displayName: 'Tégénaire Agressive',
    type: 'mob',
    mob: 'spider',
    xp: 35,
    loots: [
      { item: 'low_venom', chance: 0.01 },
      { item: 'bronze_coin', chance: 0.01 },
      { item: 'arakne_egg', chance: 0.01 },
      { item: 'arakne_egg', chance: 0.01 },
    ],
    speed: 0.4,
    health: 30,
    damage: 10,
    sounds: {
      say: 'mob.spider.say',
      hit: 'mob.spider.say',
      death: 'mob.spider.death',
      step: 'mob.spider.step',
    },
  },
  forest_tegenarian: {
    displayName: 'Tégénaire de Foret',
    type: 'mob',
    mob: 'spider',
    xp: 35,
    loots: [
      { item: 'low_venom', chance: 0.01 },
      { item: 'arakne_egg', chance: 0.01 },
      { item: 'arakne_egg', chance: 0.01 },
      { item: 'bronze_coin', chance: 0.05 },
    ],
    speed: 0.4,
    health: 55,
    damage: 18,
    sounds: {
      say: 'mob.spider.say',
      hit: 'mob.spider.say',
      death: 'mob.spider.death',
      step: 'mob.spider.step',
    },
  },
  cow: {
    displayName: 'Vache',
    type: 'mob',
    mob: 'cow',
    xp: 7,
    loots: [
      { item: 'decomposed_beast_skin', chance: 0.04 },
      { item: 'corn', chance: 0.05 },
      { item: 'corn', chance: 0.05 },
      { item: 'corn', chance: 0.05 },
      { item: 'corn', chance: 0.05 },
      { item: 'bronze_coin', chance: 0.05 },
      { item: 'bronze_coin', chance: 0.05 },
    ],
    speed: 0.5,
    health: 60,
    sounds: {
      say: 'mob.cow.say',
      hit: 'mob.cow.hurt',
      death: 'mob.cow.death',
      step: 'mob.cow.step',
    },
  },
  hook_poisonous: {
    displayName: 'Venimeuse à Crochets',
    type: 'mob',
    mob: 'cave_spider',
    xp: 115,
    loots: [
      { item: 'low_venom', chance: 0.02 },
      { item: 'arakne_egg', chance: 0.15 },
      { item: 'bronze_coin', chance: 0.08 },
    ],
    speed: 0.25,
    health: 315,
    damage: 30,
    sounds: {
      say: 'mob.spider.say',
      hit: 'mob.spider.say',
      death: 'mob.spider.death',
      step: 'mob.spider.step',
    },
  },
  araknea: {
    displayName: 'Araknéa la Couveuse',
    type: 'archiMob',
    mob: 'spider',
    xp: 5000,
    loots: [
      { item: 'coin', chance: 0.01 },
      { item: 'arakne_egg', chance: 0.2 },
      { item: 'porous_cocoons', chance: 0.02 },
      { item: 'porous_cocoons', chance: 0.1 },
    ],
    speed: 0.45,
    health: 7000,
    damage: 350,
    sounds: {
      say: 'mob.spider.say',
      hit: 'mob.spider.say',
      death: 'mob.spider.scream',
      step: 'mob.spider.step',
    },
  },
  moutron: {
    displayName: "Moutron l'Epique",
    type: 'archiMob',
    mob: 'sheep',
    xp: 125,
    loots: [],
    speed: 0.35,
    health: 75,
    damage: 10,
    sounds: {
      say: 'mob.sheep.say',
      hit: 'mob.sheep.say',
      death: 'mob.sheep.say',
      step: 'mob.skeleton.step',
    },
  },
  nofus: {
    displayName: 'Nofus le Chafer',
    type: 'archiMob',
    mob: 'skeleton',
    xp: 2000,
    loots: [
      { item: 'coin', chance: 0.02 },
      { item: 'broken_bone', chance: 0.02 },
      { item: 'broken_bone', chance: 0.02 },
    ],
    speed: 0.35,
    health: 2500,
    damage: 150,
    sounds: {
      say: 'mob.skeleton.say',
      hit: 'mob.skeleton.hurt',
      death: 'mob.skeleton.remedy',
      step: 'mob.skeleton.step',
    },
  },
  ramick: {
    displayName: 'Ramick Eymouse',
    type: 'archiMob',
    mob: 'silverfish',
    xp: 20,
    loots: [{ item: 'magma_stone', chance: 0.1 }],
    speed: 0.25,
    health: 100,
    damage: 5,
    sounds: {
      say: 'mob.silverfish.say',
      hit: 'mob.silverfish.hit',
      death: 'mob.silverfish.kill',
      step: 'mob.silverfish.step',
    },
  },
  raton: {
    displayName: "Raton L'immaculé",
    type: 'archiMob',
    mob: 'silverfish',
    speed: 0.3,
    health: 300,
    damage: 20,
    sounds: {
      say: 'mob.silverfish.say',
      hit: 'mob.silverfish.hit',
      death: 'mob.silverfish.kill',
      step: 'mob.silverfish.step',
    },
  },
  severin: {
    displayName: 'Severin le boursouflé',
    type: 'archiMob',
    mob: 'pig',
    xp: 250,
    loots: [
      { item: 'magma_stone', chance: 0.1 },
      { item: 'bronze_coin', chance: 0.2 },
      { item: 'bronze_coin', chance: 0.2 },
      { item: 'bronze_coin', chance: 0.2 },
    ],
    speed: 0.35,
    health: 400,
    damage: 15,
    sounds: {
      say: 'mob.silverfish.say',
      hit: 'mob.silverfish.hit',
      death: 'mob.silverfish.kill',
      step: 'mob.silverfish.step',
    },
  },
  sparot: {
    displayName: 'Sparot le Pirate',
    type: 'archiMob',
    mob: 'zombie',
    xp: 850,
    loots: [{ item: 'magma_stone', chance: 1 }],
    speed: 0.35,
    health: 1300,
    damage: 190,
    sounds: {
      say: 'mob.villager.haggle',
      hit: 'mob.villager.hit',
      death: 'mob.whiter.shoot',
      step: 'mob.skeleton.step',
    },
  },
  aragog: {
    displayName: "Aragog L'Acromentule",
    type: 'boss',
    mob: 'spider',
    xp: 17000,
    loots: [
      { item: 'teleportation_scroll', chance: 0.1 },
      { item: 'legendary_aragog_gem', chance: 0.035 },
      { item: 'legendary_aragog_gem', chance: 0.035 },
      { item: 'legendary_aragog_gem', chance: 0.06 },
      { item: 'legendary_aragog_gem', chance: 0.08 },
      { item: 'legendary_aragog_gem', chance: 0.08 },
      { item: 'legendary_aragog_gem', chance: 0.08 },
      { item: 'legendary_aragog_gem', chance: 0.08 },
      { item: 'aragog_sewing_thread', chance: 0.04 },
      { item: 'porous_cocoons', chance: 0.1 },
      { item: 'porous_cocoons', chance: 0.1 },
      { item: 'porous_cocoons', chance: 0.1 },
    ],
    speed: 0.35,
    health: 25000,
    damage: 450,
    sounds: {
      say: 'mob.spider.say',
      hit: 'mob.spider.say',
      death: 'mob.spider.death',
      step: 'mob.spider.step',
    },
  },
  hades: {
    displayName: "Hades l'impitoyable",
    type: 'boss',
    mob: 'skeleton',
    speed: 0.25,
    health: 100000, // * 4 * (level - 20) / 60 + 1
    damage: 400, // * 4 * (level - 20) / 60 + 1
    sounds: {
      say: 'mob.skeleton.say',
      hit: 'mob.skeleton.hurt',
      step: 'mob.skeleton.step',
    },
  },
  kraken: {
    displayName: 'Kraken',
    type: 'boss',
    mob: 'skeleton',
    xp: 9000,
    loots: [
      { item: 'teleportation_scroll', chance: 0.08 },
      { item: 'gem_of_the_kraken', chance: 0.06 },
      { item: 'kraken_gem', chance: 0.03 },
      { item: 'gem_of_the_kraken', chance: 0.06 },
      { item: 'gem_of_the_kraken', chance: 0.06 },
      { item: 'gem_of_the_kraken', chance: 0.06 },
      { item: 'gem_of_the_kraken', chance: 0.04 },
      { item: 'rotten_bag', chance: 0.04 },
    ],
    speed: 0.9,
    health: 16000,
    damage: 330,
    sounds: {
      say: 'ankresay',
      hit: 'ankrehit',
      death: 'ankresay',
    },
  },
  nerak: {
    displayName: "Nérak l'Invoqué",
    type: 'boss',
    mob: 'skeleton',
    xp: 3000,
    loots: [
      { item: 'bronze_coin', chance: 0 },
      { item: 'gem_of_nerak', chance: 0.07 },
      { item: 'gem_of_nerak', chance: 0.07 },
      { item: 'gem_of_nerak', chance: 0.07 },
      { item: 'gem_of_nerak', chance: 0.07 },
      { item: 'gem_of_nerak', chance: 0.04 },
      { item: 'gem_of_nerak', chance: 0.03 },
      { item: 'teleportation_scroll', chance: 0.05 },
    ],
    speed: 0.4,
    health: 6000,
    damage: 200,
    sounds: {
      say: 'mob.skeleton.say',
      hit: 'mob.skeleton.hurt',
      death: 'mob.wither.death',
      step: 'mob.skeleton.step',
    },
  },
  warthog: {
    displayName: 'Phacochère',
    type: 'boss',
    mob: 'pig',
    xp: 300,
    loots: [
      { item: 'bronze_coin', chance: 0.02 },
      { item: 'bronze_coin', chance: 0.02 },
      { item: 'bronze_coin', chance: 0.02 },
      { item: 'decomposed_beast_skin', chance: 1 },
      { item: 'warthog_gem', chance: 0.07 },
      { item: 'warthog_gem', chance: 0.09 },
      { item: 'warthog_gem', chance: 0.09 },
      { item: 'warthog_gem', chance: 0.09 },
      { item: 'warthog_gem', chance: 0.09 },
      { item: 'teleportation_scroll', chance: 0.1 },
    ],
    speed: 0.35,
    health: 300,
    damage: 30,
    sounds: {
      say: 'mob.pig.say',
      hit: 'mob.pig.say',
      death: 'mob.pig.death',
      step: 'mob.pig.step',
    },
  },
  numen_citizen: {
    displayName: 'Citoyen de Nùmen',
    type: 'npc',
    mob: 'villager',
    dialogs: [
      'O man dôr túliel le ?',
      'Man anírach cerin an le ?',
      'Gwanno ereb nin !',
      'No dhínen !',
      'Garich i dhôl goll o Orch',
      'Nai Aragog meditha le!',
      'Heca, firimar !',
    ],
    speed: 0.35,
    health: 20,
    sounds: {
      say: 'mob.villager.idle',
      hit: 'mob.villager.hit',
      death: 'mob.villager.death',
    },
  },
  segeste_citizen: {
    displayName: 'Citoyen de Ségeste',
    type: 'npc',
    mob: 'villager',
    dialogs: [
      'A Ségeste nous aimons la pêche et les belles villageoises !',
      "Teh c'est le petit {player} ! On m'avait dit que tu étais moche mais je ne pensais pas à ce point !",
      'On raconte que le puit de Ségeste est ensorcelé.. sans doute une vieille légende',
      "Ne m'adresse pas la parole petit ! nous n'avons pas les mêmes valeurs.",
      'Encore toi ?',
      'Un jour les dragons reviendront et ce sera la fin de notre monde !',
      "AAAAAAAAAAAAAAH !!!! Oups pardon je t'avais prit pour un infécté..",
      'Ce maudit Craken a encore provoqué une inondation...',
      "Une bonne bière et c'est repartit !",
      'Laisse moi !',
    ],
    speed: 0.35,
    health: 20,
    sounds: {
      say: 'mob.villager.idle',
      hit: 'mob.villager.idle',
      death: 'mob.villager.idle',
    },
  },
  thebes_citizen: {
    displayName: 'Citoyen de Thebes',
    type: 'npc',
    mob: 'villager',
    dialogs: [
      "C'est incroyable ce beau temps !",
      "C'est toi {player} ? Je pensais que tu étais plus grand !",
      "Fais attention à ne pas t'aventurer dans les catacombes, c'est dangereux !",
      "Je n'ai pas le temps de te parler, va t'en ou j'apelle la garde !",
      'Encore toi ?',
      'Un jour les dragons reviendront et ce sera la fin de notre monde !',
      'Laisse moi !',
    ],
    speed: 0.35,
    health: 20,
    sounds: {
      say: 'mob.villager.idle',
      hit: 'mob.villager.idle',
      death: 'mob.villager.idle',
    },
  },
  guardian: {
    displayName: 'Garde',
    type: 'npc',
    mob: 'villager',
    speed: 0.35,
    health: 500,
    damage: 500,
    sounds: {
      say: 'mob.villager.idle',
      hit: 'mob.villager.hit',
      death: 'mob.villager.idle',
    },
  },
  monk: {
    displayName: 'Moine',
    type: 'npc',
    mob: 'villager',
    dialogs: [
      'A Bien le bonjour étranger !',
      "Le père Niflard n'est pas rentré de sa ceuillette de choux..",
      'Amen',
      "A quelques lieues d'içi se trouve un gouffre terrible remplit d'Arakne.",
      'je doit aller à la messe !',
      'Un jour les dragons reviendront et ce sera la fin de notre monde !',
      'Diantre ! que tu est vilain..',
      'Oh !',
      "Une bonne cervoise et c'est repartit !",
      'Hum ?',
    ],
    speed: 0.35,
    health: 20,
    sounds: {
      say: 'mob.villager.idle',
      hit: 'mob.villager.idle',
      death: 'mob.villager.idle',
    },
  },
}
