// SPDX-License-Identifier: LicenseRef-AresRPG-Source-Available
// © 2026 Sceat — All rights reserved. See LICENSE.
// GENERATED by scripts/generate_doors.mjs from packages/move/sources/character.move — DO NOT EDIT.
// Kept isolated so display code does not pull the transaction writer into the initial UI chunk.

export const CHARACTER_PRICE_MIST = 1000000000n
