// SPDX-License-Identifier: LicenseRef-AresRPG-Source-Available
// © 2026 Sceat — All rights reserved. See LICENSE.
// GENERATED by scripts/generate_doors.mjs from packages/move/sources/{api,trade}.move — DO NOT EDIT.
// One builder per public game doors: door(tx, ctx, args) composes the move call onto the given
// Transaction and returns its Move result for further composition.
// `ctx` is the SDK's bound context ({ pins, obj, pin, receiving, pure }) — every input is
// emitted PRE-RESOLVED (objectRef / sharedObjectRef / offline system helpers), so building the
// transaction costs ZERO RPC roundtrips. Doors marked terminal take &Random: THE TERMINAL LAW —
// such a call must be the LAST command of its transaction (an inspectable roll is a free re-roll).
/* eslint-disable max-lines -- generated projection: one builder per door, size follows the Move contract */

import type { Transaction, TransactionObjectArgument } from '@mysten/sui/transactions'

import type { DoorCtx, Resolvable } from './client.ts'

/**
 * `api::split_stack`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg item_id — ID
 * @arg amount — u32
 */
export const split_stack = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; item_id: string; amount: number }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::split_stack`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'item_policy', false),
      ctx.pure.id(tx, args.item_id),
      ctx.pure.u32(tx, args.amount),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::merge_stacks`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg target_id — ID
 * @arg source_id — ID
 */
export const merge_stacks = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; target_id: string; source_id: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::merge_stacks`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'item_protected_policy', false),
      ctx.pure.id(tx, args.target_id),
      ctx.pure.id(tx, args.source_id),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::create_character`
 * @arg payment — Coin<SUI>
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg raw_name — String
 * @arg classe — String
 * @arg male — bool
 * @arg color_1 — u32
 * @arg color_2 — u32
 * @arg color_3 — u32
 * @arg first_world — &WorldContent
 */
export const create_character = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    payment: Resolvable
    kiosk: Resolvable
    cap: Resolvable
    raw_name: string
    classe: string
    male: boolean
    color_1: number
    color_2: number
    color_3: number
    first_world: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::create_character`,
    arguments: [
      ctx.pin(tx, 'name_registry', true),
      ctx.obj(tx, args.payment, true),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'character_policy', false),
      ctx.pure.string(tx, args.raw_name),
      ctx.pure.string(tx, args.classe),
      ctx.pure.bool(tx, args.male),
      ctx.pure.u32(tx, args.color_1),
      ctx.pure.u32(tx, args.color_2),
      ctx.pure.u32(tx, args.color_3),
      ctx.obj(tx, args.first_world, false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::join_world`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg destination — &WorldContent
 */
export const join_world = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; character_id: string; destination: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::join_world`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.obj(tx, args.destination, false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::create_zone` — TERMINAL (&Random): last command of its transaction.
 * @arg kiosk — &mut Kiosk
 * @arg personal — &PersonalKioskCap
 * @arg character_id — ID
 * @arg x — u32
 * @arg z — u32
 * @arg world_object — &mut World
 */
export const create_zone = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    kiosk: Resolvable
    personal: Resolvable
    character_id: string
    x: number
    z: number
    world_object: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::create_zone`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.personal, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.u32(tx, args.x),
      ctx.pure.u32(tx, args.z),
      ctx.obj(tx, args.world_object, true),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::refresh_zone` — TERMINAL (&Random): last command of its transaction.
 * @arg kiosk — &mut Kiosk
 * @arg personal — &PersonalKioskCap
 * @arg character_id — ID
 * @arg x — u32
 * @arg z — u32
 * @arg zone_object — &mut Zone
 */
export const refresh_zone = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; personal: Resolvable; character_id: string; x: number; z: number; zone_object: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::refresh_zone`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.personal, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.u32(tx, args.x),
      ctx.pure.u32(tx, args.z),
      ctx.obj(tx, args.zone_object, true),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::raise_stat`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg stat — String
 * @arg points — u16
 */
export const raise_stat = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; character_id: string; stat: string; points: number }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::raise_stat`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.string(tx, args.stat),
      ctx.pure.u16(tx, args.points),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::raise_spell`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg spell — &SpellTemplate
 */
export const raise_spell = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; character_id: string; spell: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::raise_spell`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.obj(tx, args.spell, false),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::equip_item`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg slot — String
 * @arg item_id — ID
 */
export const equip_item = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; character_id: string; slot: string; item_id: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::equip_item`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.string(tx, args.slot),
      ctx.pure.id(tx, args.item_id),
      ctx.pin(tx, 'item_protected_policy', false),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::unequip_item`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg slot — String
 * @arg receiving — Receiving<Item>
 */
export const unequip_item = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; character_id: string; slot: string; receiving: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::unequip_item`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.string(tx, args.slot),
      ctx.receiving(tx, args.receiving),
      ctx.pin(tx, 'item_policy', false),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::feed_kiosk_pet`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg pet_template — &ItemTemplate
 * @arg pet_id — ID
 * @arg food_id — ID
 */
export const feed_kiosk_pet = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; pet_template: Resolvable; pet_id: string; food_id: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::feed_kiosk_pet`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.pet_template, false),
      ctx.pure.id(tx, args.pet_id),
      ctx.pure.id(tx, args.food_id),
      ctx.pin(tx, 'item_protected_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::delete_character`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 */
export const delete_character = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; character_id: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::delete_character`,
    arguments: [
      ctx.pin(tx, 'friend_registry', false),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pin(tx, 'character_protected_policy', false),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::engage_fight`
 * @arg kiosk — &mut Kiosk
 * @arg personal — &PersonalKioskCap
 * @arg character_id — ID
 * @arg zone_object — &mut Zone
 * @arg world_content — &WorldContent
 * @arg group_index — u64
 * @arg access — u8
 * @arg catalog — &BoardCatalog
 */
export const engage_fight = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    kiosk: Resolvable
    personal: Resolvable
    character_id: string
    zone_object: Resolvable
    world_content: Resolvable
    group_index: bigint | number | string
    access: number
    catalog: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::engage_fight`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.personal, false),
      ctx.pure.id(tx, args.character_id),
      ctx.obj(tx, args.zone_object, true),
      ctx.obj(tx, args.world_content, false),
      ctx.pure.u64(tx, args.group_index),
      ctx.pure.u8(tx, args.access),
      ctx.pin(tx, 'character_protected_policy', false),
      ctx.obj(tx, args.catalog, false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::add_fight_mob`
 * @arg build — FightBuild
 * @arg template — &MobTemplate
 */
export const add_fight_mob = (tx: Transaction, ctx: DoorCtx, args: { build: Resolvable; template: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::add_fight_mob`,
    arguments: [ctx.obj(tx, args.build, true), ctx.obj(tx, args.template, false)],
  })

/**
 * `api::launch_fight` — TERMINAL (&Random): last command of its transaction.
 * @arg build — FightBuild
 */
export const launch_fight = (tx: Transaction, ctx: DoorCtx, args: { build: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::launch_fight`,
    arguments: [ctx.obj(tx, args.build, true), tx.object.random(), tx.object.clock()],
  })

/**
 * `api::challenge_duel` — TERMINAL (&Random): last command of its transaction.
 * @arg kiosk — &mut Kiosk
 * @arg personal — &PersonalKioskCap
 * @arg character_id — ID
 * @arg target — ID
 * @arg x — u32
 * @arg z — u32
 * @arg access — u8
 * @arg catalog — &BoardCatalog
 */
export const challenge_duel = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    kiosk: Resolvable
    personal: Resolvable
    character_id: string
    target: string
    x: number
    z: number
    access: number
    catalog: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::challenge_duel`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.personal, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.id(tx, args.target),
      ctx.pure.u32(tx, args.x),
      ctx.pure.u32(tx, args.z),
      ctx.pure.u8(tx, args.access),
      ctx.pin(tx, 'character_protected_policy', false),
      ctx.obj(tx, args.catalog, false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::join_fight`
 * @arg fight_object — &mut Fight
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg team — u8
 * @arg access — u8
 */
export const join_fight = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    fight_object: Resolvable
    kiosk: Resolvable
    cap: Resolvable
    character_id: string
    team: number
    access: number
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::join_fight`,
    arguments: [
      ctx.obj(tx, args.fight_object, true),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.u8(tx, args.team),
      ctx.pure.u8(tx, args.access),
      ctx.pin(tx, 'character_protected_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::join_fight_grouped`
 * @arg fight_object — &mut Fight
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg team — u8
 * @arg shared_party — &Party
 */
export const join_fight_grouped = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    fight_object: Resolvable
    kiosk: Resolvable
    cap: Resolvable
    character_id: string
    team: number
    shared_party: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::join_fight_grouped`,
    arguments: [
      ctx.obj(tx, args.fight_object, true),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.u8(tx, args.team),
      ctx.obj(tx, args.shared_party, false),
      ctx.pin(tx, 'character_protected_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::place_fighter`
 * @arg fight_object — &mut Fight
 * @arg fighter_idx — u64
 * @arg cell — u64
 */
export const place_fighter = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { fight_object: Resolvable; fighter_idx: bigint | number | string; cell: bigint | number | string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::place_fighter`,
    arguments: [
      ctx.obj(tx, args.fight_object, true),
      ctx.pure.u64(tx, args.fighter_idx),
      ctx.pure.u64(tx, args.cell),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::ready_fight`
 * @arg fight_object — &mut Fight
 * @arg fighter_idx — u64
 */
export const ready_fight = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { fight_object: Resolvable; fighter_idx: bigint | number | string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::ready_fight`,
    arguments: [
      ctx.obj(tx, args.fight_object, true),
      ctx.pure.u64(tx, args.fighter_idx),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::ready_and_start_fight` — TERMINAL (&Random): last command of its transaction.
 * @arg fight_object — &mut Fight
 * @arg fighter_idx — u64
 */
export const ready_and_start_fight = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { fight_object: Resolvable; fighter_idx: bigint | number | string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::ready_and_start_fight`,
    arguments: [
      ctx.obj(tx, args.fight_object, true),
      ctx.pure.u64(tx, args.fighter_idx),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::start_fight` — TERMINAL (&Random): last command of its transaction.
 * @arg fight_object — &mut Fight
 */
export const start_fight = (tx: Transaction, ctx: DoorCtx, args: { fight_object: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::start_fight`,
    arguments: [
      ctx.obj(tx, args.fight_object, true),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::cast_spell`
 * @arg fight_object — &mut Fight
 * @arg fighter_idx — u64
 * @arg spell — &SpellTemplate
 * @arg target_cell — u64
 */
export const cast_spell = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    fight_object: Resolvable
    fighter_idx: bigint | number | string
    spell: Resolvable
    target_cell: bigint | number | string
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::cast_spell`,
    arguments: [
      ctx.obj(tx, args.fight_object, true),
      ctx.pure.u64(tx, args.fighter_idx),
      ctx.obj(tx, args.spell, false),
      ctx.pure.u64(tx, args.target_cell),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::weapon_strike`
 * @arg fight_object — &mut Fight
 * @arg fighter_idx — u64
 * @arg target_cell — u64
 */
export const weapon_strike = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { fight_object: Resolvable; fighter_idx: bigint | number | string; target_cell: bigint | number | string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::weapon_strike`,
    arguments: [
      ctx.obj(tx, args.fight_object, true),
      ctx.pure.u64(tx, args.fighter_idx),
      ctx.pure.u64(tx, args.target_cell),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::move_fighter`
 * @arg fight_object — &mut Fight
 * @arg path — vector<u64>
 */
export const move_fighter = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { fight_object: Resolvable; path: readonly (bigint | number | string)[] }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::move_fighter`,
    arguments: [
      ctx.obj(tx, args.fight_object, true),
      ctx.pure.vector(tx, 'u64', args.path),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::seal_fight_loot` — TERMINAL (&Random): last command of its transaction.
 * @arg fight_object — &mut Fight
 */
export const seal_fight_loot = (tx: Transaction, ctx: DoorCtx, args: { fight_object: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::seal_fight_loot`,
    arguments: [ctx.obj(tx, args.fight_object, true), tx.object.random(), ctx.pin(tx, 'version', false)],
  })

/**
 * `api::end_fight_turn` — TERMINAL (&Random): last command of its transaction.
 * @arg fight_object — &mut Fight
 */
export const end_fight_turn = (tx: Transaction, ctx: DoorCtx, args: { fight_object: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::end_fight_turn`,
    arguments: [
      ctx.obj(tx, args.fight_object, true),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::crank_fight` — TERMINAL (&Random): last command of its transaction.
 * @arg fight_object — &mut Fight
 */
export const crank_fight = (tx: Transaction, ctx: DoorCtx, args: { fight_object: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::crank_fight`,
    arguments: [
      ctx.obj(tx, args.fight_object, true),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::forfeit_fight`
 * @arg fight_object — &mut Fight
 * @arg fighter_idx — u64
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 */
export const forfeit_fight = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { fight_object: Resolvable; fighter_idx: bigint | number | string; kiosk: Resolvable; cap: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::forfeit_fight`,
    arguments: [
      ctx.obj(tx, args.fight_object, true),
      ctx.pure.u64(tx, args.fighter_idx),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'character_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::prepare_fight_loot`
 * @arg template — &ItemTemplate
 * @arg existing — Option<ID>
 */
export const prepare_fight_loot = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { template: Resolvable; existing: string | null | undefined }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::prepare_fight_loot`,
    arguments: [ctx.obj(tx, args.template, false), ctx.pure.option(tx, 'id', args.existing ?? null)],
  })

/**
 * `api::start_first_daily_quest` — TERMINAL (&Random): last command of its transaction.
 * @arg world_content — &WorldContent
 * @arg kiosk — &Kiosk
 * @arg personal — &PersonalKioskCap
 * @arg character_id — ID
 */
export const start_first_daily_quest = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { world_content: Resolvable; kiosk: Resolvable; personal: Resolvable; character_id: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::start_first_daily_quest`,
    arguments: [
      ctx.pin(tx, 'friend_registry', true),
      ctx.obj(tx, args.world_content, false),
      ctx.obj(tx, args.kiosk, false),
      ctx.obj(tx, args.personal, false),
      ctx.pure.id(tx, args.character_id),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::start_daily_quest` — TERMINAL (&Random): last command of its transaction.
 * @arg mastery_object — &mut Mastery
 * @arg world_content — &WorldContent
 * @arg kiosk — &Kiosk
 * @arg personal — &PersonalKioskCap
 * @arg character_id — ID
 */
export const start_daily_quest = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    mastery_object: Resolvable
    world_content: Resolvable
    kiosk: Resolvable
    personal: Resolvable
    character_id: string
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::start_daily_quest`,
    arguments: [
      ctx.obj(tx, args.mastery_object, true),
      ctx.obj(tx, args.world_content, false),
      ctx.obj(tx, args.kiosk, false),
      ctx.obj(tx, args.personal, false),
      ctx.pure.id(tx, args.character_id),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::complete_daily_quest_if_eligible`
 * @arg mastery_object — &mut Mastery
 * @arg fight_object — &Fight
 * @arg fighter_idx — u64
 * @arg dungeon_content — &DungeonContent
 */
export const complete_daily_quest_if_eligible = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    mastery_object: Resolvable
    fight_object: Resolvable
    fighter_idx: bigint | number | string
    dungeon_content: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::complete_daily_quest_if_eligible`,
    arguments: [
      ctx.obj(tx, args.mastery_object, true),
      ctx.obj(tx, args.fight_object, false),
      ctx.pure.u64(tx, args.fighter_idx),
      ctx.obj(tx, args.dungeon_content, false),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::redeem_mastery_offer`
 * @arg mastery_object — &mut Mastery
 * @arg offer — &MasteryOffer
 * @arg template — &ItemTemplate
 * @arg existing — Option<ID>
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 */
export const redeem_mastery_offer = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    mastery_object: Resolvable
    offer: Resolvable
    template: Resolvable
    existing: string | null | undefined
    kiosk: Resolvable
    cap: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::redeem_mastery_offer`,
    arguments: [
      ctx.obj(tx, args.mastery_object, true),
      ctx.obj(tx, args.offer, false),
      ctx.obj(tx, args.template, false),
      ctx.pure.option(tx, 'id', args.existing ?? null),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'item_policy', false),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::settle_fight` — TERMINAL (&Random): last command of its transaction.
 * @arg fight_object — &mut Fight
 * @arg fighter_indices — vector<u64>
 * @arg plan_lengths — vector<u64>
 * @arg plan — vector<PM>
 * @arg kiosk — &mut Kiosk
 * @arg personal — &PersonalKioskCap
 */
export const settle_fight = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    fight_object: Resolvable
    fighter_indices: readonly (bigint | number | string)[]
    plan_lengths: readonly (bigint | number | string)[]
    plan: readonly TransactionObjectArgument[]
    kiosk: Resolvable
    personal: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::settle_fight`,
    arguments: [
      ctx.obj(tx, args.fight_object, true),
      ctx.pure.vector(tx, 'u64', args.fighter_indices),
      ctx.pure.vector(tx, 'u64', args.plan_lengths),
      tx.makeMoveVec({ type: `${ctx.game_type_package}::item::PM`, elements: [...args.plan] }),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.personal, false),
      ctx.pin(tx, 'character_policy', false),
      ctx.pin(tx, 'item_policy', false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::settle_last_fight` — TERMINAL (&Random): last command of its transaction.
 * @arg fight_object — Fight
 * @arg fighter_indices — vector<u64>
 * @arg plan_lengths — vector<u64>
 * @arg plan — vector<PM>
 * @arg kiosk — &mut Kiosk
 * @arg personal — &PersonalKioskCap
 */
export const settle_last_fight = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    fight_object: Resolvable
    fighter_indices: readonly (bigint | number | string)[]
    plan_lengths: readonly (bigint | number | string)[]
    plan: readonly TransactionObjectArgument[]
    kiosk: Resolvable
    personal: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::settle_last_fight`,
    arguments: [
      ctx.obj(tx, args.fight_object, true),
      ctx.pure.vector(tx, 'u64', args.fighter_indices),
      ctx.pure.vector(tx, 'u64', args.plan_lengths),
      tx.makeMoveVec({ type: `${ctx.game_type_package}::item::PM`, elements: [...args.plan] }),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.personal, false),
      ctx.pin(tx, 'character_policy', false),
      ctx.pin(tx, 'item_policy', false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::close_fight`
 * @arg fight_object — Fight
 */
export const close_fight = (tx: Transaction, ctx: DoorCtx, args: { fight_object: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::close_fight`,
    arguments: [ctx.obj(tx, args.fight_object, true), ctx.pin(tx, 'version', false)],
  })

/**
 * `api::create_party_invitation`
 * @arg kiosk — &Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg invited_character — ID
 */
export const create_party_invitation = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; character_id: string; invited_character: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::create_party_invitation`,
    arguments: [
      ctx.pin(tx, 'friend_registry', true),
      ctx.obj(tx, args.kiosk, false),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.id(tx, args.invited_character),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::party_invitation`
 * @arg party_object — &mut Party
 * @arg kiosk — &Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg actor_id — ID
 * @arg invited_character — ID
 * @arg present — bool
 */
export const party_invitation = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    party_object: Resolvable
    kiosk: Resolvable
    cap: Resolvable
    actor_id: string
    invited_character: string
    present: boolean
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::party_invitation`,
    arguments: [
      ctx.pin(tx, 'friend_registry', false),
      ctx.obj(tx, args.party_object, true),
      ctx.obj(tx, args.kiosk, false),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.actor_id),
      ctx.pure.id(tx, args.invited_character),
      ctx.pure.bool(tx, args.present),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::party_invitation_from_fight`
 * @arg party_object — &mut Party
 * @arg fight_object — &Fight
 * @arg fighter_idx — u64
 * @arg actor_id — ID
 * @arg invited_character — ID
 */
export const party_invitation_from_fight = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    party_object: Resolvable
    fight_object: Resolvable
    fighter_idx: bigint | number | string
    actor_id: string
    invited_character: string
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::party_invitation_from_fight`,
    arguments: [
      ctx.pin(tx, 'friend_registry', false),
      ctx.obj(tx, args.party_object, true),
      ctx.obj(tx, args.fight_object, false),
      ctx.pure.u64(tx, args.fighter_idx),
      ctx.pure.id(tx, args.actor_id),
      ctx.pure.id(tx, args.invited_character),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::party_accept`
 * @arg party_object — &mut Party
 * @arg kiosk — &Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 */
export const party_accept = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { party_object: Resolvable; kiosk: Resolvable; cap: Resolvable; character_id: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::party_accept`,
    arguments: [
      ctx.pin(tx, 'friend_registry', true),
      ctx.obj(tx, args.party_object, true),
      ctx.obj(tx, args.kiosk, false),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::party_leave`
 * @arg party_object — &mut Party
 * @arg kiosk — &Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 */
export const party_leave = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { party_object: Resolvable; kiosk: Resolvable; cap: Resolvable; character_id: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::party_leave`,
    arguments: [
      ctx.pin(tx, 'friend_registry', true),
      ctx.obj(tx, args.party_object, true),
      ctx.obj(tx, args.kiosk, false),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::party_kick`
 * @arg party_object — &mut Party
 * @arg kiosk — &Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg leader_id — ID
 * @arg target_character — ID
 */
export const party_kick = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { party_object: Resolvable; kiosk: Resolvable; cap: Resolvable; leader_id: string; target_character: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::party_kick`,
    arguments: [
      ctx.pin(tx, 'friend_registry', true),
      ctx.obj(tx, args.party_object, true),
      ctx.obj(tx, args.kiosk, false),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.leader_id),
      ctx.pure.id(tx, args.target_character),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::party_disband`
 * @arg party_object — Party
 * @arg kiosk — &Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg leader_id — ID
 */
export const party_disband = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { party_object: Resolvable; kiosk: Resolvable; cap: Resolvable; leader_id: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::party_disband`,
    arguments: [
      ctx.pin(tx, 'friend_registry', true),
      ctx.obj(tx, args.party_object, true),
      ctx.obj(tx, args.kiosk, false),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.leader_id),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::use_consumable`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg item_id — ID
 * @arg template — &ItemTemplate
 */
export const use_consumable = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; character_id: string; item_id: string; template: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::use_consumable`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.id(tx, args.item_id),
      ctx.obj(tx, args.template, false),
      ctx.pin(tx, 'item_protected_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::use_city_consumable`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg item_id — ID
 * @arg template — &ItemTemplate
 * @arg world_content — &WorldContent
 */
export const use_city_consumable = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    kiosk: Resolvable
    cap: Resolvable
    character_id: string
    item_id: string
    template: Resolvable
    world_content: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::use_city_consumable`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.id(tx, args.item_id),
      ctx.obj(tx, args.template, false),
      ctx.obj(tx, args.world_content, false),
      ctx.pin(tx, 'item_protected_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::gather` — TERMINAL (&Random): last command of its transaction.
 * @arg zone_object — &mut Zone
 * @arg world_content — &WorldContent
 * @arg kiosk — &mut Kiosk
 * @arg personal — &PersonalKioskCap
 * @arg character_id — ID
 * @arg pack_index — u64
 * @arg template — &ItemTemplate
 * @arg rare_template — &ItemTemplate
 * @arg existing — Option<ID>
 * @arg existing_rare — Option<ID>
 */
export const gather = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    zone_object: Resolvable
    world_content: Resolvable
    kiosk: Resolvable
    personal: Resolvable
    character_id: string
    pack_index: bigint | number | string
    template: Resolvable
    rare_template: Resolvable
    existing: string | null | undefined
    existing_rare: string | null | undefined
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::gather`,
    arguments: [
      ctx.obj(tx, args.zone_object, true),
      ctx.obj(tx, args.world_content, false),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.personal, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.u64(tx, args.pack_index),
      ctx.obj(tx, args.template, false),
      ctx.obj(tx, args.rare_template, false),
      ctx.pure.option(tx, 'id', args.existing ?? null),
      ctx.pure.option(tx, 'id', args.existing_rare ?? null),
      ctx.pin(tx, 'item_policy', false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::resolve_ambush`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg protector_template — &MobTemplate
 * @arg catalog — &BoardCatalog
 */
export const resolve_ambush = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    kiosk: Resolvable
    cap: Resolvable
    character_id: string
    protector_template: Resolvable
    catalog: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::resolve_ambush`,
    arguments: [
      ctx.pin(tx, 'character_protected_policy', false),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.obj(tx, args.protector_template, false),
      ctx.obj(tx, args.catalog, false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::craft` — TERMINAL (&Random): last command of its transaction.
 * @arg recipe — &Recipe
 * @arg kiosk — &mut Kiosk
 * @arg personal — &PersonalKioskCap
 * @arg character_id — ID
 * @arg input_item_ids — vector<ID>
 * @arg output_template — &ItemTemplate
 * @arg existing — Option<ID>
 * @arg attempts — u16
 */
export const craft = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    recipe: Resolvable
    kiosk: Resolvable
    personal: Resolvable
    character_id: string
    input_item_ids: readonly string[]
    output_template: Resolvable
    existing: string | null | undefined
    attempts: number
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::craft`,
    arguments: [
      ctx.obj(tx, args.recipe, false),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.personal, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.vector(tx, 'id', args.input_item_ids),
      ctx.obj(tx, args.output_template, false),
      ctx.pure.option(tx, 'id', args.existing ?? null),
      ctx.pure.u16(tx, args.attempts),
      ctx.pin(tx, 'item_protected_policy', false),
      ctx.pin(tx, 'item_policy', false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::scribe_rune` — TERMINAL (&Random): last command of its transaction.
 * @arg kiosk — &mut Kiosk
 * @arg personal — &PersonalKioskCap
 * @arg character_id — ID
 * @arg gear_id — ID
 * @arg gear_template — &ItemTemplate
 * @arg rune_item_id — ID
 * @arg rune_stat — u8
 * @arg rune_tier — u8
 */
export const scribe_rune = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    kiosk: Resolvable
    personal: Resolvable
    character_id: string
    gear_id: string
    gear_template: Resolvable
    rune_item_id: string
    rune_stat: number
    rune_tier: number
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::scribe_rune`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.personal, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.id(tx, args.gear_id),
      ctx.obj(tx, args.gear_template, false),
      ctx.pure.id(tx, args.rune_item_id),
      ctx.pure.u8(tx, args.rune_stat),
      ctx.pure.u8(tx, args.rune_tier),
      ctx.pin(tx, 'item_protected_policy', false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::crush_gear` — TERMINAL (&Random): last command of its transaction.
 * @arg kiosk — &mut Kiosk
 * @arg personal — &PersonalKioskCap
 * @arg gear_ids — vector<ID>
 */
export const crush_gear = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; personal: Resolvable; gear_ids: readonly string[] }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::crush_gear`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.personal, false),
      ctx.pure.vector(tx, 'id', args.gear_ids),
      ctx.pin(tx, 'item_protected_policy', false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::reveal_crush_claim`
 * @arg claim — &mut CrushClaim
 */
export const reveal_crush_claim = (tx: Transaction, ctx: DoorCtx, args: { claim: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::reveal_crush_claim`,
    arguments: [ctx.obj(tx, args.claim, true), ctx.pin(tx, 'version', false)],
  })

/**
 * `api::redeem_rune`
 * @arg claim — &mut CrushClaim
 * @arg template — &ItemTemplate
 * @arg stat — u8
 * @arg tier — u8
 * @arg existing — Option<ID>
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 */
export const redeem_rune = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    claim: Resolvable
    template: Resolvable
    stat: number
    tier: number
    existing: string | null | undefined
    kiosk: Resolvable
    cap: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::redeem_rune`,
    arguments: [
      ctx.obj(tx, args.claim, true),
      ctx.obj(tx, args.template, false),
      ctx.pure.u8(tx, args.stat),
      ctx.pure.u8(tx, args.tier),
      ctx.pure.option(tx, 'id', args.existing ?? null),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'item_policy', false),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::discard_crush_claim`
 * @arg claim — CrushClaim
 */
export const discard_crush_claim = (tx: Transaction, ctx: DoorCtx, args: { claim: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::discard_crush_claim`,
    arguments: [ctx.obj(tx, args.claim, true), ctx.pin(tx, 'version', false)],
  })

/**
 * `api::open_loot_box` — TERMINAL (&Random): last command of its transaction.
 * @arg kiosk — &mut Kiosk
 * @arg personal — &PersonalKioskCap
 * @arg box_item_id — ID
 * @arg box_template — &ItemTemplate
 */
export const open_loot_box = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; personal: Resolvable; box_item_id: string; box_template: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::open_loot_box`,
    arguments: [
      ctx.pin(tx, 'loot_registry', false),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.personal, false),
      ctx.pure.id(tx, args.box_item_id),
      ctx.obj(tx, args.box_template, false),
      ctx.pin(tx, 'item_protected_policy', false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::claim_loot` — TERMINAL (&Random): last command of its transaction.
 * @arg claim — BoxClaim
 * @arg rolled_template — &ItemTemplate
 * @arg existing — Option<ID>
 * @arg kiosk — &mut Kiosk
 * @arg personal — &PersonalKioskCap
 */
export const claim_loot = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    claim: Resolvable
    rolled_template: Resolvable
    existing: string | null | undefined
    kiosk: Resolvable
    personal: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::claim_loot`,
    arguments: [
      ctx.obj(tx, args.claim, true),
      ctx.obj(tx, args.rolled_template, false),
      ctx.pure.option(tx, 'id', args.existing ?? null),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.personal, false),
      ctx.pin(tx, 'item_policy', false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::burn_item`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg item_id — ID
 * @arg amount — u32
 */
export const burn_item = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; item_id: string; amount: number }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::burn_item`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'item_protected_policy', false),
      ctx.pure.id(tx, args.item_id),
      ctx.pure.u32(tx, args.amount),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::claim_airdrop`
 * @arg drop — &mut Airdrop
 * @arg template — &ItemTemplate
 * @arg recipient — address
 */
export const claim_airdrop = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { drop: Resolvable; template: Resolvable; recipient: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::claim_airdrop`,
    arguments: [
      ctx.obj(tx, args.drop, true),
      ctx.obj(tx, args.template, false),
      ctx.pure.address(tx, args.recipient),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::redeem_giftcard`
 * @arg card — Giftcard
 * @arg template — &ItemTemplate
 * @arg existing — Option<ID>
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 */
export const redeem_giftcard = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    card: Resolvable
    template: Resolvable
    existing: string | null | undefined
    kiosk: Resolvable
    cap: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::redeem_giftcard`,
    arguments: [
      ctx.obj(tx, args.card, true),
      ctx.obj(tx, args.template, false),
      ctx.pure.option(tx, 'id', args.existing ?? null),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'item_policy', false),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::enter_dungeon` — TERMINAL (&Random): last command of its transaction.
 * @arg world_object — &World
 * @arg kiosk — &mut Kiosk
 * @arg personal — &PersonalKioskCap
 * @arg character_id — ID
 * @arg world_content — &WorldContent
 * @arg dungeon_content — &DungeonContent
 * @arg key_id — ID
 */
export const enter_dungeon = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    world_object: Resolvable
    kiosk: Resolvable
    personal: Resolvable
    character_id: string
    world_content: Resolvable
    dungeon_content: Resolvable
    key_id: string
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::enter_dungeon`,
    arguments: [
      ctx.obj(tx, args.world_object, false),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.personal, false),
      ctx.pure.id(tx, args.character_id),
      ctx.obj(tx, args.world_content, false),
      ctx.obj(tx, args.dungeon_content, false),
      ctx.pure.id(tx, args.key_id),
      ctx.pin(tx, 'item_protected_policy', false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::engage_dungeon_room`
 * @arg world_object — &World
 * @arg world_content — &WorldContent
 * @arg dungeon_content — &DungeonContent
 * @arg kiosk — &mut Kiosk
 * @arg personal — &PersonalKioskCap
 * @arg character_id — ID
 * @arg access — u8
 * @arg catalog — &BoardCatalog
 */
export const engage_dungeon_room = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    world_object: Resolvable
    world_content: Resolvable
    dungeon_content: Resolvable
    kiosk: Resolvable
    personal: Resolvable
    character_id: string
    access: number
    catalog: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::engage_dungeon_room`,
    arguments: [
      ctx.obj(tx, args.world_object, false),
      ctx.obj(tx, args.world_content, false),
      ctx.obj(tx, args.dungeon_content, false),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.personal, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.u8(tx, args.access),
      ctx.pin(tx, 'character_protected_policy', false),
      ctx.obj(tx, args.catalog, false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::join_dungeon_room`
 * @arg fight_object — &mut Fight
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 */
export const join_dungeon_room = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { fight_object: Resolvable; kiosk: Resolvable; cap: Resolvable; character_id: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::join_dungeon_room`,
    arguments: [
      ctx.obj(tx, args.fight_object, true),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pin(tx, 'character_protected_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::join_dungeon_room_grouped`
 * @arg fight_object — &mut Fight
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg shared_party — &Party
 */
export const join_dungeon_room_grouped = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { fight_object: Resolvable; kiosk: Resolvable; cap: Resolvable; character_id: string; shared_party: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::join_dungeon_room_grouped`,
    arguments: [
      ctx.obj(tx, args.fight_object, true),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.obj(tx, args.shared_party, false),
      ctx.pin(tx, 'character_protected_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::settle_dungeon_room` — TERMINAL (&Random): last command of its transaction.
 * @arg dungeon_content — &DungeonContent
 * @arg fight_object — &mut Fight
 * @arg fighter_indices — vector<u64>
 * @arg plan_lengths — vector<u64>
 * @arg plan — vector<PM>
 * @arg kiosk — &mut Kiosk
 * @arg personal — &PersonalKioskCap
 */
export const settle_dungeon_room = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    dungeon_content: Resolvable
    fight_object: Resolvable
    fighter_indices: readonly (bigint | number | string)[]
    plan_lengths: readonly (bigint | number | string)[]
    plan: readonly TransactionObjectArgument[]
    kiosk: Resolvable
    personal: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::settle_dungeon_room`,
    arguments: [
      ctx.obj(tx, args.dungeon_content, false),
      ctx.obj(tx, args.fight_object, true),
      ctx.pure.vector(tx, 'u64', args.fighter_indices),
      ctx.pure.vector(tx, 'u64', args.plan_lengths),
      tx.makeMoveVec({ type: `${ctx.game_type_package}::item::PM`, elements: [...args.plan] }),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.personal, false),
      ctx.pin(tx, 'character_policy', false),
      ctx.pin(tx, 'item_policy', false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::settle_last_dungeon_room` — TERMINAL (&Random): last command of its transaction.
 * @arg dungeon_content — &DungeonContent
 * @arg fight_object — Fight
 * @arg fighter_indices — vector<u64>
 * @arg plan_lengths — vector<u64>
 * @arg plan — vector<PM>
 * @arg kiosk — &mut Kiosk
 * @arg personal — &PersonalKioskCap
 */
export const settle_last_dungeon_room = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    dungeon_content: Resolvable
    fight_object: Resolvable
    fighter_indices: readonly (bigint | number | string)[]
    plan_lengths: readonly (bigint | number | string)[]
    plan: readonly TransactionObjectArgument[]
    kiosk: Resolvable
    personal: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::settle_last_dungeon_room`,
    arguments: [
      ctx.obj(tx, args.dungeon_content, false),
      ctx.obj(tx, args.fight_object, true),
      ctx.pure.vector(tx, 'u64', args.fighter_indices),
      ctx.pure.vector(tx, 'u64', args.plan_lengths),
      tx.makeMoveVec({ type: `${ctx.game_type_package}::item::PM`, elements: [...args.plan] }),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.personal, false),
      ctx.pin(tx, 'character_policy', false),
      ctx.pin(tx, 'item_policy', false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::give_up_dungeon_room`
 * @arg fight_object — &mut Fight
 * @arg fighter_idx — u64
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 */
export const give_up_dungeon_room = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { fight_object: Resolvable; fighter_idx: bigint | number | string; kiosk: Resolvable; cap: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::give_up_dungeon_room`,
    arguments: [
      ctx.obj(tx, args.fight_object, true),
      ctx.pure.u64(tx, args.fighter_idx),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'character_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::abandon_dungeon_run`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 */
export const abandon_dungeon_run = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; character_id: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::abandon_dungeon_run`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::create_kolizeum` — TERMINAL (&Random): last command of its transaction.
 * @arg pledge — Coin<SUI>
 * @arg format — u64
 * @arg level_min — u16
 * @arg level_max — u16
 * @arg access — u8
 * @arg kiosk — &mut Kiosk
 * @arg personal — &PersonalKioskCap
 * @arg character_id — ID
 * @arg catalog — &BoardCatalog
 */
export const create_kolizeum = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    pledge: Resolvable
    format: bigint | number | string
    level_min: number
    level_max: number
    access: number
    kiosk: Resolvable
    personal: Resolvable
    character_id: string
    catalog: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::create_kolizeum`,
    arguments: [
      ctx.obj(tx, args.pledge, true),
      ctx.pure.u64(tx, args.format),
      ctx.pure.u16(tx, args.level_min),
      ctx.pure.u16(tx, args.level_max),
      ctx.pure.u8(tx, args.access),
      ctx.pin(tx, 'character_protected_policy', false),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.personal, false),
      ctx.pure.id(tx, args.character_id),
      ctx.obj(tx, args.catalog, false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::create_kolizeum_friends` — TERMINAL (&Random): last command of its transaction.
 * @arg pledge — Coin<SUI>
 * @arg format — u64
 * @arg level_min — u16
 * @arg level_max — u16
 * @arg access — u8
 * @arg list — &FriendList
 * @arg kiosk — &mut Kiosk
 * @arg personal — &PersonalKioskCap
 * @arg character_id — ID
 * @arg catalog — &BoardCatalog
 */
export const create_kolizeum_friends = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    pledge: Resolvable
    format: bigint | number | string
    level_min: number
    level_max: number
    access: number
    list: Resolvable
    kiosk: Resolvable
    personal: Resolvable
    character_id: string
    catalog: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::create_kolizeum_friends`,
    arguments: [
      ctx.obj(tx, args.pledge, true),
      ctx.pure.u64(tx, args.format),
      ctx.pure.u16(tx, args.level_min),
      ctx.pure.u16(tx, args.level_max),
      ctx.pure.u8(tx, args.access),
      ctx.obj(tx, args.list, false),
      ctx.pin(tx, 'character_protected_policy', false),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.personal, false),
      ctx.pure.id(tx, args.character_id),
      ctx.obj(tx, args.catalog, false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::join_kolizeum`
 * @arg lobby — &mut Kolizeum
 * @arg fight_object — &mut Fight
 * @arg pledge — Coin<SUI>
 * @arg side — u8
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 */
export const join_kolizeum = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    lobby: Resolvable
    fight_object: Resolvable
    pledge: Resolvable
    side: number
    kiosk: Resolvable
    cap: Resolvable
    character_id: string
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::join_kolizeum`,
    arguments: [
      ctx.obj(tx, args.lobby, true),
      ctx.obj(tx, args.fight_object, true),
      ctx.obj(tx, args.pledge, true),
      ctx.pure.u8(tx, args.side),
      ctx.pin(tx, 'character_protected_policy', false),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::ready_and_start_kolizeum` — TERMINAL (&Random): last command of its transaction.
 * @arg lobby — &mut Kolizeum
 * @arg fight_object — &mut Fight
 * @arg fighter_idx — u64
 */
export const ready_and_start_kolizeum = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { lobby: Resolvable; fight_object: Resolvable; fighter_idx: bigint | number | string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::ready_and_start_kolizeum`,
    arguments: [
      ctx.obj(tx, args.lobby, true),
      ctx.obj(tx, args.fight_object, true),
      ctx.pure.u64(tx, args.fighter_idx),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::start_kolizeum` — TERMINAL (&Random): last command of its transaction.
 * @arg lobby — &mut Kolizeum
 * @arg fight_object — &mut Fight
 */
export const start_kolizeum = (tx: Transaction, ctx: DoorCtx, args: { lobby: Resolvable; fight_object: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::start_kolizeum`,
    arguments: [
      ctx.obj(tx, args.lobby, true),
      ctx.obj(tx, args.fight_object, true),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::settle_kolizeum`
 * @arg lobby — &mut Kolizeum
 * @arg fight_object — &mut Fight
 * @arg fighter_idx — u64
 * @arg kiosk — &mut Kiosk
 * @arg personal — &PersonalKioskCap
 */
export const settle_kolizeum = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    lobby: Resolvable
    fight_object: Resolvable
    fighter_idx: bigint | number | string
    kiosk: Resolvable
    personal: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::settle_kolizeum`,
    arguments: [
      ctx.obj(tx, args.lobby, true),
      ctx.obj(tx, args.fight_object, true),
      ctx.pure.u64(tx, args.fighter_idx),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.personal, false),
      ctx.pin(tx, 'character_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::settle_last_kolizeum`
 * @arg lobby — Kolizeum
 * @arg fight_object — Fight
 * @arg fighter_idx — u64
 * @arg kiosk — &mut Kiosk
 * @arg personal — &PersonalKioskCap
 */
export const settle_last_kolizeum = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    lobby: Resolvable
    fight_object: Resolvable
    fighter_idx: bigint | number | string
    kiosk: Resolvable
    personal: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::settle_last_kolizeum`,
    arguments: [
      ctx.obj(tx, args.lobby, true),
      ctx.obj(tx, args.fight_object, true),
      ctx.pure.u64(tx, args.fighter_idx),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.personal, false),
      ctx.pin(tx, 'character_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::exit_kolizeum`
 * @arg lobby — &mut Kolizeum
 * @arg fight_object — &mut Fight
 * @arg fighter_idx — u64
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 */
export const exit_kolizeum = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    lobby: Resolvable
    fight_object: Resolvable
    fighter_idx: bigint | number | string
    kiosk: Resolvable
    cap: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::exit_kolizeum`,
    arguments: [
      ctx.obj(tx, args.lobby, true),
      ctx.obj(tx, args.fight_object, true),
      ctx.pure.u64(tx, args.fighter_idx),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'character_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::exit_last_kolizeum`
 * @arg lobby — Kolizeum
 * @arg fight_object — Fight
 * @arg fighter_idx — u64
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 */
export const exit_last_kolizeum = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    lobby: Resolvable
    fight_object: Resolvable
    fighter_idx: bigint | number | string
    kiosk: Resolvable
    cap: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::exit_last_kolizeum`,
    arguments: [
      ctx.obj(tx, args.lobby, true),
      ctx.obj(tx, args.fight_object, true),
      ctx.pure.u64(tx, args.fighter_idx),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'character_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::forfeit_kolizeum`
 * @arg fight_object — &mut Fight
 * @arg fighter_idx — u64
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 */
export const forfeit_kolizeum = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { fight_object: Resolvable; fighter_idx: bigint | number | string; kiosk: Resolvable; cap: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::forfeit_kolizeum`,
    arguments: [
      ctx.obj(tx, args.fight_object, true),
      ctx.pure.u64(tx, args.fighter_idx),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'character_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::close_kolizeum`
 * @arg lobby — Kolizeum
 * @arg fight_object — Fight
 */
export const close_kolizeum = (tx: Transaction, ctx: DoorCtx, args: { lobby: Resolvable; fight_object: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::close_kolizeum`,
    arguments: [ctx.obj(tx, args.lobby, true), ctx.obj(tx, args.fight_object, true), ctx.pin(tx, 'version', false)],
  })

/**
 * `api::create_friend_list`
 * @arg first — address
 */
export const create_friend_list = (tx: Transaction, ctx: DoorCtx, args: { first: string }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::create_friend_list`,
    arguments: [ctx.pin(tx, 'friend_registry', true), ctx.pure.address(tx, args.first), ctx.pin(tx, 'version', false)],
  })

/**
 * `api::set_friend`
 * @arg list — &mut FriendList
 * @arg addr — address
 * @arg present — bool
 */
export const set_friend = (tx: Transaction, ctx: DoorCtx, args: { list: Resolvable; addr: string; present: boolean }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::set_friend`,
    arguments: [
      ctx.obj(tx, args.list, true),
      ctx.pure.address(tx, args.addr),
      ctx.pure.bool(tx, args.present),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::trade_put_item`
 * @arg trade_object — &mut Trade
 * @arg cap — PurchaseCap<Item>
 * @arg seen_offer_revision — u64
 */
export const trade_put_item = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { trade_object: Resolvable; cap: Resolvable; seen_offer_revision: bigint | number | string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::trade_put_item`,
    arguments: [
      ctx.obj(tx, args.trade_object, true),
      ctx.obj(tx, args.cap, true),
      ctx.pure.u64(tx, args.seen_offer_revision),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::trade_take_item`
 * @arg trade_object — &mut Trade
 * @arg item — ID
 * @arg seen_offer_revision — u64
 */
export const trade_take_item = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { trade_object: Resolvable; item: string; seen_offer_revision: bigint | number | string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::trade_take_item`,
    arguments: [
      ctx.obj(tx, args.trade_object, true),
      ctx.pure.id(tx, args.item),
      ctx.pure.u64(tx, args.seen_offer_revision),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::trade_claim_item`
 * @arg trade_object — &mut Trade
 * @arg item — ID
 * @arg source — &mut Kiosk
 */
export const trade_claim_item = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { trade_object: Resolvable; item: string; source: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::trade_claim_item`,
    arguments: [
      ctx.obj(tx, args.trade_object, true),
      ctx.pure.id(tx, args.item),
      ctx.obj(tx, args.source, true),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::trade_recover_item`
 * @arg trade_object — &mut Trade
 * @arg item — ID
 */
export const trade_recover_item = (tx: Transaction, ctx: DoorCtx, args: { trade_object: Resolvable; item: string }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::trade_recover_item`,
    arguments: [ctx.obj(tx, args.trade_object, true), ctx.pure.id(tx, args.item), ctx.pin(tx, 'version', false)],
  })

/**
 * `trade::create`
 * @arg counterparty — address
 */
export const trade_create = (tx: Transaction, ctx: DoorCtx, args: { counterparty: string }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::trade::create`,
    arguments: [ctx.pure.address(tx, args.counterparty), ctx.pin(tx, 'version', false)],
  })

/**
 * `trade::join`
 * @arg trade — &mut Trade
 * @arg seen — u64
 */
export const trade_join = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { trade: Resolvable; seen: bigint | number | string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::trade::join`,
    arguments: [ctx.obj(tx, args.trade, true), ctx.pure.u64(tx, args.seen), ctx.pin(tx, 'version', false)],
  })

/**
 * `trade::end_request`
 * @arg trade — Trade
 * @arg seen — u64
 */
export const trade_cancel_request = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { trade: Resolvable; seen: bigint | number | string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::trade::end_request`,
    arguments: [ctx.obj(tx, args.trade, true), ctx.pure.u64(tx, args.seen), ctx.pin(tx, 'version', false)],
  })

/**
 * `trade::end_request`
 * @arg trade — Trade
 * @arg seen — u64
 */
export const trade_decline_request = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { trade: Resolvable; seen: bigint | number | string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::trade::end_request`,
    arguments: [ctx.obj(tx, args.trade, true), ctx.pure.u64(tx, args.seen), ctx.pin(tx, 'version', false)],
  })

/**
 * `trade::cancel`
 * @arg trade — &mut Trade
 * @arg seen — u64
 */
export const trade_cancel = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { trade: Resolvable; seen: bigint | number | string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::trade::cancel`,
    arguments: [ctx.obj(tx, args.trade, true), ctx.pure.u64(tx, args.seen), ctx.pin(tx, 'version', false)],
  })

/**
 * `trade::put_sui`
 * @arg trade — &mut Trade
 * @arg coin — Coin<SUI>
 * @arg seen — u64
 */
export const trade_put_sui = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { trade: Resolvable; coin: Resolvable; seen: bigint | number | string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::trade::put_sui`,
    arguments: [
      ctx.obj(tx, args.trade, true),
      ctx.obj(tx, args.coin, true),
      ctx.pure.u64(tx, args.seen),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `trade::take_sui`
 * @arg trade — &mut Trade
 * @arg amount — u64
 * @arg seen — u64
 */
export const trade_take_sui = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { trade: Resolvable; amount: bigint | number | string; seen: bigint | number | string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::trade::take_sui`,
    arguments: [
      ctx.obj(tx, args.trade, true),
      ctx.pure.u64(tx, args.amount),
      ctx.pure.u64(tx, args.seen),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `trade::accept`
 * @arg trade — &mut Trade
 * @arg seen — u64
 */
export const trade_accept = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { trade: Resolvable; seen: bigint | number | string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::trade::accept`,
    arguments: [ctx.obj(tx, args.trade, true), ctx.pure.u64(tx, args.seen), ctx.pin(tx, 'version', false)],
  })

/**
 * `trade::claim_sui`
 * @arg trade — &mut Trade
 */
export const trade_claim_sui = (tx: Transaction, ctx: DoorCtx, args: { trade: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::trade::claim_sui`,
    arguments: [ctx.obj(tx, args.trade, true), ctx.pin(tx, 'version', false)],
  })

/**
 * `trade::recover_sui`
 * @arg trade — &mut Trade
 */
export const trade_recover_sui = (tx: Transaction, ctx: DoorCtx, args: { trade: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::trade::recover_sui`,
    arguments: [ctx.obj(tx, args.trade, true), ctx.pin(tx, 'version', false)],
  })

/**
 * `trade::close`
 * @arg trade — Trade
 */
export const trade_close = (tx: Transaction, ctx: DoorCtx, args: { trade: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::trade::close`,
    arguments: [ctx.obj(tx, args.trade, true), ctx.pin(tx, 'version', false)],
  })

/** Every door, by name — { params: caller-facing names, terminal: carries &Random }. */
export const DOORS = {
  split_stack: { params: ['kiosk', 'cap', 'item_id', 'amount'], terminal: false },
  merge_stacks: { params: ['kiosk', 'cap', 'target_id', 'source_id'], terminal: false },
  create_character: {
    params: ['payment', 'kiosk', 'cap', 'raw_name', 'classe', 'male', 'color_1', 'color_2', 'color_3', 'first_world'],
    terminal: false,
  },
  join_world: { params: ['kiosk', 'cap', 'character_id', 'destination'], terminal: false },
  create_zone: { params: ['kiosk', 'personal', 'character_id', 'x', 'z', 'world_object'], terminal: true },
  refresh_zone: { params: ['kiosk', 'personal', 'character_id', 'x', 'z', 'zone_object'], terminal: true },
  raise_stat: { params: ['kiosk', 'cap', 'character_id', 'stat', 'points'], terminal: false },
  raise_spell: { params: ['kiosk', 'cap', 'character_id', 'spell'], terminal: false },
  equip_item: { params: ['kiosk', 'cap', 'character_id', 'slot', 'item_id'], terminal: false },
  unequip_item: { params: ['kiosk', 'cap', 'character_id', 'slot', 'receiving'], terminal: false },
  feed_kiosk_pet: { params: ['kiosk', 'cap', 'pet_template', 'pet_id', 'food_id'], terminal: false },
  delete_character: { params: ['kiosk', 'cap', 'character_id'], terminal: false },
  engage_fight: {
    params: ['kiosk', 'personal', 'character_id', 'zone_object', 'world_content', 'group_index', 'access', 'catalog'],
    terminal: false,
  },
  add_fight_mob: { params: ['build', 'template'], terminal: false },
  launch_fight: { params: ['build'], terminal: true },
  challenge_duel: {
    params: ['kiosk', 'personal', 'character_id', 'target', 'x', 'z', 'access', 'catalog'],
    terminal: true,
  },
  join_fight: { params: ['fight_object', 'kiosk', 'cap', 'character_id', 'team', 'access'], terminal: false },
  join_fight_grouped: {
    params: ['fight_object', 'kiosk', 'cap', 'character_id', 'team', 'shared_party'],
    terminal: false,
  },
  place_fighter: { params: ['fight_object', 'fighter_idx', 'cell'], terminal: false },
  ready_fight: { params: ['fight_object', 'fighter_idx'], terminal: false },
  ready_and_start_fight: { params: ['fight_object', 'fighter_idx'], terminal: true },
  start_fight: { params: ['fight_object'], terminal: true },
  cast_spell: { params: ['fight_object', 'fighter_idx', 'spell', 'target_cell'], terminal: false },
  weapon_strike: { params: ['fight_object', 'fighter_idx', 'target_cell'], terminal: false },
  move_fighter: { params: ['fight_object', 'path'], terminal: false },
  seal_fight_loot: { params: ['fight_object'], terminal: true },
  end_fight_turn: { params: ['fight_object'], terminal: true },
  crank_fight: { params: ['fight_object'], terminal: true },
  forfeit_fight: { params: ['fight_object', 'fighter_idx', 'kiosk', 'cap'], terminal: false },
  prepare_fight_loot: { params: ['template', 'existing'], terminal: false },
  start_first_daily_quest: { params: ['world_content', 'kiosk', 'personal', 'character_id'], terminal: true },
  start_daily_quest: {
    params: ['mastery_object', 'world_content', 'kiosk', 'personal', 'character_id'],
    terminal: true,
  },
  complete_daily_quest_if_eligible: {
    params: ['mastery_object', 'fight_object', 'fighter_idx', 'dungeon_content'],
    terminal: false,
  },
  redeem_mastery_offer: {
    params: ['mastery_object', 'offer', 'template', 'existing', 'kiosk', 'cap'],
    terminal: false,
  },
  settle_fight: {
    params: ['fight_object', 'fighter_indices', 'plan_lengths', 'plan', 'kiosk', 'personal'],
    terminal: true,
  },
  settle_last_fight: {
    params: ['fight_object', 'fighter_indices', 'plan_lengths', 'plan', 'kiosk', 'personal'],
    terminal: true,
  },
  close_fight: { params: ['fight_object'], terminal: false },
  create_party_invitation: { params: ['kiosk', 'cap', 'character_id', 'invited_character'], terminal: false },
  party_invitation: {
    params: ['party_object', 'kiosk', 'cap', 'actor_id', 'invited_character', 'present'],
    terminal: false,
  },
  party_invitation_from_fight: {
    params: ['party_object', 'fight_object', 'fighter_idx', 'actor_id', 'invited_character'],
    terminal: false,
  },
  party_accept: { params: ['party_object', 'kiosk', 'cap', 'character_id'], terminal: false },
  party_leave: { params: ['party_object', 'kiosk', 'cap', 'character_id'], terminal: false },
  party_kick: { params: ['party_object', 'kiosk', 'cap', 'leader_id', 'target_character'], terminal: false },
  party_disband: { params: ['party_object', 'kiosk', 'cap', 'leader_id'], terminal: false },
  use_consumable: { params: ['kiosk', 'cap', 'character_id', 'item_id', 'template'], terminal: false },
  use_city_consumable: {
    params: ['kiosk', 'cap', 'character_id', 'item_id', 'template', 'world_content'],
    terminal: false,
  },
  gather: {
    params: [
      'zone_object',
      'world_content',
      'kiosk',
      'personal',
      'character_id',
      'pack_index',
      'template',
      'rare_template',
      'existing',
      'existing_rare',
    ],
    terminal: true,
  },
  resolve_ambush: { params: ['kiosk', 'cap', 'character_id', 'protector_template', 'catalog'], terminal: false },
  craft: {
    params: [
      'recipe',
      'kiosk',
      'personal',
      'character_id',
      'input_item_ids',
      'output_template',
      'existing',
      'attempts',
    ],
    terminal: true,
  },
  scribe_rune: {
    params: ['kiosk', 'personal', 'character_id', 'gear_id', 'gear_template', 'rune_item_id', 'rune_stat', 'rune_tier'],
    terminal: true,
  },
  crush_gear: { params: ['kiosk', 'personal', 'gear_ids'], terminal: true },
  reveal_crush_claim: { params: ['claim'], terminal: false },
  redeem_rune: { params: ['claim', 'template', 'stat', 'tier', 'existing', 'kiosk', 'cap'], terminal: false },
  discard_crush_claim: { params: ['claim'], terminal: false },
  open_loot_box: { params: ['kiosk', 'personal', 'box_item_id', 'box_template'], terminal: true },
  claim_loot: { params: ['claim', 'rolled_template', 'existing', 'kiosk', 'personal'], terminal: true },
  burn_item: { params: ['kiosk', 'cap', 'item_id', 'amount'], terminal: false },
  claim_airdrop: { params: ['drop', 'template', 'recipient'], terminal: false },
  redeem_giftcard: { params: ['card', 'template', 'existing', 'kiosk', 'cap'], terminal: false },
  enter_dungeon: {
    params: ['world_object', 'kiosk', 'personal', 'character_id', 'world_content', 'dungeon_content', 'key_id'],
    terminal: true,
  },
  engage_dungeon_room: {
    params: [
      'world_object',
      'world_content',
      'dungeon_content',
      'kiosk',
      'personal',
      'character_id',
      'access',
      'catalog',
    ],
    terminal: false,
  },
  join_dungeon_room: { params: ['fight_object', 'kiosk', 'cap', 'character_id'], terminal: false },
  join_dungeon_room_grouped: {
    params: ['fight_object', 'kiosk', 'cap', 'character_id', 'shared_party'],
    terminal: false,
  },
  settle_dungeon_room: {
    params: ['dungeon_content', 'fight_object', 'fighter_indices', 'plan_lengths', 'plan', 'kiosk', 'personal'],
    terminal: true,
  },
  settle_last_dungeon_room: {
    params: ['dungeon_content', 'fight_object', 'fighter_indices', 'plan_lengths', 'plan', 'kiosk', 'personal'],
    terminal: true,
  },
  give_up_dungeon_room: { params: ['fight_object', 'fighter_idx', 'kiosk', 'cap'], terminal: false },
  abandon_dungeon_run: { params: ['kiosk', 'cap', 'character_id'], terminal: false },
  create_kolizeum: {
    params: ['pledge', 'format', 'level_min', 'level_max', 'access', 'kiosk', 'personal', 'character_id', 'catalog'],
    terminal: true,
  },
  create_kolizeum_friends: {
    params: [
      'pledge',
      'format',
      'level_min',
      'level_max',
      'access',
      'list',
      'kiosk',
      'personal',
      'character_id',
      'catalog',
    ],
    terminal: true,
  },
  join_kolizeum: {
    params: ['lobby', 'fight_object', 'pledge', 'side', 'kiosk', 'cap', 'character_id'],
    terminal: false,
  },
  ready_and_start_kolizeum: { params: ['lobby', 'fight_object', 'fighter_idx'], terminal: true },
  start_kolizeum: { params: ['lobby', 'fight_object'], terminal: true },
  settle_kolizeum: { params: ['lobby', 'fight_object', 'fighter_idx', 'kiosk', 'personal'], terminal: false },
  settle_last_kolizeum: { params: ['lobby', 'fight_object', 'fighter_idx', 'kiosk', 'personal'], terminal: false },
  exit_kolizeum: { params: ['lobby', 'fight_object', 'fighter_idx', 'kiosk', 'cap'], terminal: false },
  exit_last_kolizeum: { params: ['lobby', 'fight_object', 'fighter_idx', 'kiosk', 'cap'], terminal: false },
  forfeit_kolizeum: { params: ['fight_object', 'fighter_idx', 'kiosk', 'cap'], terminal: false },
  close_kolizeum: { params: ['lobby', 'fight_object'], terminal: false },
  create_friend_list: { params: ['first'], terminal: false },
  set_friend: { params: ['list', 'addr', 'present'], terminal: false },
  trade_put_item: { params: ['trade_object', 'cap', 'seen_offer_revision'], terminal: false },
  trade_take_item: { params: ['trade_object', 'item', 'seen_offer_revision'], terminal: false },
  trade_claim_item: { params: ['trade_object', 'item', 'source'], terminal: false },
  trade_recover_item: { params: ['trade_object', 'item'], terminal: false },
  trade_create: { params: ['counterparty'], terminal: false },
  trade_join: { params: ['trade', 'seen'], terminal: false },
  trade_cancel_request: { params: ['trade', 'seen'], terminal: false },
  trade_decline_request: { params: ['trade', 'seen'], terminal: false },
  trade_cancel: { params: ['trade', 'seen'], terminal: false },
  trade_put_sui: { params: ['trade', 'coin', 'seen'], terminal: false },
  trade_take_sui: { params: ['trade', 'amount', 'seen'], terminal: false },
  trade_accept: { params: ['trade', 'seen'], terminal: false },
  trade_claim_sui: { params: ['trade'], terminal: false },
  trade_recover_sui: { params: ['trade'], terminal: false },
  trade_close: { params: ['trade'], terminal: false },
}
