// SPDX-License-Identifier: LicenseRef-AresRPG-Source-Available
// © 2026 Sceat — All rights reserved. See LICENSE.
// GENERATED by scripts/generate_doors.mjs from packages/move/sources/api.move — DO NOT EDIT.
// One builder per api.move doors: door(tx, ctx, args) composes the move call onto the given
// Transaction and returns its Move result for further composition.
// `ctx` is the SDK's bound context ({ pins, obj, pin, receiving, pure }) — every input is
// emitted PRE-RESOLVED (objectRef / sharedObjectRef / offline system helpers), so building the
// transaction costs ZERO RPC roundtrips. Doors marked terminal take &Random: THE TERMINAL LAW —
// such a call must be the LAST command of its transaction (an inspectable roll is a free re-roll).
/* eslint-disable max-lines -- generated projection: one builder per door, size follows the Move contract */

import type { Transaction } from '@mysten/sui/transactions'

import type { DoorCtx, Resolvable } from './client.ts'

/**
 * `api::create_character`
 * @arg payment — Coin<SUI>
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg raw_name — String
 * @arg classe — String
 * @arg male — bool
 * @arg color_1 — u32
 * @arg color_2 — u32
 * @arg color_3 — u32
 */
export const create_character = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    payment: Resolvable
    kiosk: Resolvable
    cap: Resolvable
    raw_name: string
    classe: string
    male: boolean
    color_1: number
    color_2: number
    color_3: number
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::create_character`,
    arguments: [
      ctx.pin(tx, 'name_registry', true),
      ctx.obj(tx, args.payment, true),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'character_policy', false),
      ctx.pure.string(tx, args.raw_name),
      ctx.pure.string(tx, args.classe),
      ctx.pure.bool(tx, args.male),
      ctx.pure.u32(tx, args.color_1),
      ctx.pure.u32(tx, args.color_2),
      ctx.pure.u32(tx, args.color_3),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::join_world`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg world — String
 */
export const join_world = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; character_id: string; world: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::join_world`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.string(tx, args.world),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::search_zone` — TERMINAL (&Random): last command of its transaction.
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg x — u32
 * @arg z — u32
 * @arg w — &mut World
 */
export const search_zone = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; character_id: string; x: number; z: number; w: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::search_zone`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.u32(tx, args.x),
      ctx.pure.u32(tx, args.z),
      ctx.obj(tx, args.w, true),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::raise_stat`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg stat — String
 * @arg amount — u16
 */
export const raise_stat = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; character_id: string; stat: string; amount: number }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::raise_stat`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.string(tx, args.stat),
      ctx.pure.u16(tx, args.amount),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::raise_spell`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg spell — &SpellTemplate
 */
export const raise_spell = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; character_id: string; spell: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::raise_spell`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.obj(tx, args.spell, false),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::equip_item`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg slot — String
 * @arg item_id — ID
 */
export const equip_item = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; character_id: string; slot: string; item_id: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::equip_item`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.string(tx, args.slot),
      ctx.pure.id(tx, args.item_id),
      ctx.pin(tx, 'item_protected_policy', false),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::unequip_item`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg slot — String
 * @arg receiving — Receiving<Item>
 */
export const unequip_item = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; character_id: string; slot: string; receiving: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::unequip_item`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.string(tx, args.slot),
      ctx.receiving(tx, args.receiving),
      ctx.pin(tx, 'item_policy', false),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::feed_kiosk_pet`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg pet_template — &ItemTemplate
 * @arg pet_id — ID
 * @arg food_id — ID
 */
export const feed_kiosk_pet = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; pet_template: Resolvable; pet_id: string; food_id: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::feed_kiosk_pet`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.pet_template, false),
      ctx.pure.id(tx, args.pet_id),
      ctx.pure.id(tx, args.food_id),
      ctx.pin(tx, 'item_protected_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::delete_character`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 */
export const delete_character = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; character_id: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::delete_character`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pin(tx, 'character_protected_policy', false),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::engage_fight`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg w — &mut World
 * @arg zx — u32
 * @arg zz — u32
 * @arg group_index — u64
 * @arg access — u8
 */
export const engage_fight = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    kiosk: Resolvable
    cap: Resolvable
    character_id: string
    w: Resolvable
    zx: number
    zz: number
    group_index: bigint | number | string
    access: number
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::engage_fight`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.obj(tx, args.w, true),
      ctx.pure.u32(tx, args.zx),
      ctx.pure.u32(tx, args.zz),
      ctx.pure.u64(tx, args.group_index),
      ctx.pure.u8(tx, args.access),
      ctx.pin(tx, 'character_protected_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::add_fight_mob`
 * @arg build — FightBuild
 * @arg template — &MobTemplate
 */
export const add_fight_mob = (tx: Transaction, ctx: DoorCtx, args: { build: Resolvable; template: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::add_fight_mob`,
    arguments: [ctx.obj(tx, args.build, true), ctx.obj(tx, args.template, false)],
  })

/**
 * `api::launch_fight`
 * @arg build — FightBuild
 */
export const launch_fight = (tx: Transaction, ctx: DoorCtx, args: { build: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::launch_fight`,
    arguments: [ctx.obj(tx, args.build, true), tx.object.clock()],
  })

/**
 * `api::challenge_duel` — TERMINAL (&Random): last command of its transaction.
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg x — u32
 * @arg z — u32
 * @arg access — u8
 */
export const challenge_duel = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; character_id: string; x: number; z: number; access: number }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::challenge_duel`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.u32(tx, args.x),
      ctx.pure.u32(tx, args.z),
      ctx.pure.u8(tx, args.access),
      ctx.pin(tx, 'character_protected_policy', false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::join_fight`
 * @arg f — &mut Fight
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg team — u8
 * @arg access — u8
 */
export const join_fight = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { f: Resolvable; kiosk: Resolvable; cap: Resolvable; character_id: string; team: number; access: number }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::join_fight`,
    arguments: [
      ctx.obj(tx, args.f, true),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.u8(tx, args.team),
      ctx.pure.u8(tx, args.access),
      ctx.pin(tx, 'character_protected_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::join_fight_grouped`
 * @arg f — &mut Fight
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg team — u8
 * @arg shared_party — &Party
 */
export const join_fight_grouped = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    f: Resolvable
    kiosk: Resolvable
    cap: Resolvable
    character_id: string
    team: number
    shared_party: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::join_fight_grouped`,
    arguments: [
      ctx.obj(tx, args.f, true),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.u8(tx, args.team),
      ctx.obj(tx, args.shared_party, false),
      ctx.pin(tx, 'character_protected_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::place_fighter`
 * @arg f — &mut Fight
 * @arg fighter_idx — u64
 * @arg cell — u64
 */
export const place_fighter = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { f: Resolvable; fighter_idx: bigint | number | string; cell: bigint | number | string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::place_fighter`,
    arguments: [
      ctx.obj(tx, args.f, true),
      ctx.pure.u64(tx, args.fighter_idx),
      ctx.pure.u64(tx, args.cell),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::ready_fighter`
 * @arg f — &mut Fight
 * @arg fighter_idx — u64
 */
export const ready_fighter = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { f: Resolvable; fighter_idx: bigint | number | string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::ready_fighter`,
    arguments: [ctx.obj(tx, args.f, true), ctx.pure.u64(tx, args.fighter_idx), ctx.pin(tx, 'version', false)],
  })

/**
 * `api::start_fight` — TERMINAL (&Random): last command of its transaction.
 * @arg f — &mut Fight
 */
export const start_fight = (tx: Transaction, ctx: DoorCtx, args: { f: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::start_fight`,
    arguments: [ctx.obj(tx, args.f, true), tx.object.random(), ctx.pin(tx, 'version', false), tx.object.clock()],
  })

/**
 * `api::cast_spell`
 * @arg f — &mut Fight
 * @arg fighter_idx — u64
 * @arg spell — &SpellTemplate
 * @arg target_cell — u64
 */
export const cast_spell = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    f: Resolvable
    fighter_idx: bigint | number | string
    spell: Resolvable
    target_cell: bigint | number | string
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::cast_spell`,
    arguments: [
      ctx.obj(tx, args.f, true),
      ctx.pure.u64(tx, args.fighter_idx),
      ctx.obj(tx, args.spell, false),
      ctx.pure.u64(tx, args.target_cell),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::weapon_strike`
 * @arg f — &mut Fight
 * @arg fighter_idx — u64
 * @arg target_cell — u64
 */
export const weapon_strike = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { f: Resolvable; fighter_idx: bigint | number | string; target_cell: bigint | number | string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::weapon_strike`,
    arguments: [
      ctx.obj(tx, args.f, true),
      ctx.pure.u64(tx, args.fighter_idx),
      ctx.pure.u64(tx, args.target_cell),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::move_fighter`
 * @arg f — &mut Fight
 * @arg path — vector<u64>
 */
export const move_fighter = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { f: Resolvable; path: readonly (bigint | number | string)[] }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::move_fighter`,
    arguments: [ctx.obj(tx, args.f, true), ctx.pure.vector(tx, 'u64', args.path), ctx.pin(tx, 'version', false)],
  })

/**
 * `api::end_fight_turn` — TERMINAL (&Random): last command of its transaction.
 * @arg f — &mut Fight
 */
export const end_fight_turn = (tx: Transaction, ctx: DoorCtx, args: { f: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::end_fight_turn`,
    arguments: [ctx.obj(tx, args.f, true), tx.object.random(), ctx.pin(tx, 'version', false), tx.object.clock()],
  })

/**
 * `api::crank_fight` — TERMINAL (&Random): last command of its transaction.
 * @arg f — &mut Fight
 */
export const crank_fight = (tx: Transaction, ctx: DoorCtx, args: { f: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::crank_fight`,
    arguments: [ctx.obj(tx, args.f, true), tx.object.random(), ctx.pin(tx, 'version', false), tx.object.clock()],
  })

/**
 * `api::forfeit_fight`
 * @arg f — &mut Fight
 * @arg fighter_idx — u64
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 */
export const forfeit_fight = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { f: Resolvable; fighter_idx: bigint | number | string; kiosk: Resolvable; cap: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::forfeit_fight`,
    arguments: [
      ctx.obj(tx, args.f, true),
      ctx.pure.u64(tx, args.fighter_idx),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'character_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::settle_fight` — TERMINAL (&Random): last command of its transaction.
 * @arg f — &mut Fight
 * @arg fighter_idx — u64
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 */
export const settle_fight = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { f: Resolvable; fighter_idx: bigint | number | string; kiosk: Resolvable; cap: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::settle_fight`,
    arguments: [
      ctx.obj(tx, args.f, true),
      ctx.pure.u64(tx, args.fighter_idx),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'character_policy', false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::claim_fight_drop` — TERMINAL (&Random): last command of its transaction.
 * @arg f — &mut Fight
 * @arg fighter_idx — u64
 * @arg template — &ItemTemplate
 * @arg existing — Option<ID>
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 */
export const claim_fight_drop = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    f: Resolvable
    fighter_idx: bigint | number | string
    template: Resolvable
    existing: string | null | undefined
    kiosk: Resolvable
    cap: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::claim_fight_drop`,
    arguments: [
      ctx.obj(tx, args.f, true),
      ctx.pure.u64(tx, args.fighter_idx),
      ctx.obj(tx, args.template, false),
      ctx.pure.option(tx, 'id', args.existing ?? null),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'item_policy', false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::close_fight`
 * @arg f — Fight
 */
export const close_fight = (tx: Transaction, ctx: DoorCtx, args: { f: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::close_fight`,
    arguments: [ctx.obj(tx, args.f, true), ctx.pin(tx, 'version', false)],
  })

/**
 * `api::create_party`
 * @arg kiosk — &Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 */
export const create_party = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; character_id: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::create_party`,
    arguments: [
      ctx.obj(tx, args.kiosk, false),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::party_invite`
 * @arg p — &mut Party
 * @arg kiosk — &Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg leader_id — ID
 * @arg invited_character — ID
 */
export const party_invite = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { p: Resolvable; kiosk: Resolvable; cap: Resolvable; leader_id: string; invited_character: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::party_invite`,
    arguments: [
      ctx.obj(tx, args.p, true),
      ctx.obj(tx, args.kiosk, false),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.leader_id),
      ctx.pure.id(tx, args.invited_character),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::party_accept`
 * @arg p — &mut Party
 * @arg kiosk — &Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 */
export const party_accept = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { p: Resolvable; kiosk: Resolvable; cap: Resolvable; character_id: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::party_accept`,
    arguments: [
      ctx.obj(tx, args.p, true),
      ctx.obj(tx, args.kiosk, false),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::party_decline`
 * @arg p — &mut Party
 * @arg kiosk — &Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 */
export const party_decline = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { p: Resolvable; kiosk: Resolvable; cap: Resolvable; character_id: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::party_decline`,
    arguments: [
      ctx.obj(tx, args.p, true),
      ctx.obj(tx, args.kiosk, false),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::party_rescind`
 * @arg p — &mut Party
 * @arg kiosk — &Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg leader_id — ID
 * @arg invited_character — ID
 */
export const party_rescind = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { p: Resolvable; kiosk: Resolvable; cap: Resolvable; leader_id: string; invited_character: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::party_rescind`,
    arguments: [
      ctx.obj(tx, args.p, true),
      ctx.obj(tx, args.kiosk, false),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.leader_id),
      ctx.pure.id(tx, args.invited_character),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::party_leave`
 * @arg p — &mut Party
 * @arg kiosk — &Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 */
export const party_leave = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { p: Resolvable; kiosk: Resolvable; cap: Resolvable; character_id: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::party_leave`,
    arguments: [
      ctx.obj(tx, args.p, true),
      ctx.obj(tx, args.kiosk, false),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::party_kick`
 * @arg p — &mut Party
 * @arg kiosk — &Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg leader_id — ID
 * @arg target_character — ID
 */
export const party_kick = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { p: Resolvable; kiosk: Resolvable; cap: Resolvable; leader_id: string; target_character: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::party_kick`,
    arguments: [
      ctx.obj(tx, args.p, true),
      ctx.obj(tx, args.kiosk, false),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.leader_id),
      ctx.pure.id(tx, args.target_character),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::party_disband`
 * @arg p — Party
 * @arg kiosk — &Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg leader_id — ID
 */
export const party_disband = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { p: Resolvable; kiosk: Resolvable; cap: Resolvable; leader_id: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::party_disband`,
    arguments: [
      ctx.obj(tx, args.p, true),
      ctx.obj(tx, args.kiosk, false),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.leader_id),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::use_consumable`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg item_id — ID
 * @arg template — &ItemTemplate
 */
export const use_consumable = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; character_id: string; item_id: string; template: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::use_consumable`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.id(tx, args.item_id),
      ctx.obj(tx, args.template, false),
      ctx.pin(tx, 'item_protected_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::gather` — TERMINAL (&Random): last command of its transaction.
 * @arg w — &mut World
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg zx — u32
 * @arg zz — u32
 * @arg pack_index — u64
 * @arg template — &ItemTemplate
 * @arg rare_template — &ItemTemplate
 * @arg existing — Option<ID>
 * @arg existing_rare — Option<ID>
 */
export const gather = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    w: Resolvable
    kiosk: Resolvable
    cap: Resolvable
    character_id: string
    zx: number
    zz: number
    pack_index: bigint | number | string
    template: Resolvable
    rare_template: Resolvable
    existing: string | null | undefined
    existing_rare: string | null | undefined
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::gather`,
    arguments: [
      ctx.obj(tx, args.w, true),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.u32(tx, args.zx),
      ctx.pure.u32(tx, args.zz),
      ctx.pure.u64(tx, args.pack_index),
      ctx.obj(tx, args.template, false),
      ctx.obj(tx, args.rare_template, false),
      ctx.pure.option(tx, 'id', args.existing ?? null),
      ctx.pure.option(tx, 'id', args.existing_rare ?? null),
      ctx.pin(tx, 'item_policy', false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::resolve_ambush`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg protector_template — &MobTemplate
 */
export const resolve_ambush = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; character_id: string; protector_template: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::resolve_ambush`,
    arguments: [
      ctx.pin(tx, 'character_protected_policy', false),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.obj(tx, args.protector_template, false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::craft` — TERMINAL (&Random): last command of its transaction.
 * @arg recipe — &Recipe
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg input_item_ids — vector<ID>
 * @arg output_template — &ItemTemplate
 * @arg existing — Option<ID>
 */
export const craft = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    recipe: Resolvable
    kiosk: Resolvable
    cap: Resolvable
    character_id: string
    input_item_ids: readonly string[]
    output_template: Resolvable
    existing: string | null | undefined
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::craft`,
    arguments: [
      ctx.obj(tx, args.recipe, false),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.vector(tx, 'id', args.input_item_ids),
      ctx.obj(tx, args.output_template, false),
      ctx.pure.option(tx, 'id', args.existing ?? null),
      ctx.pin(tx, 'item_protected_policy', false),
      ctx.pin(tx, 'item_policy', false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::scribe_rune` — TERMINAL (&Random): last command of its transaction.
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg gear_id — ID
 * @arg gear_template — &ItemTemplate
 * @arg rune_item_id — ID
 */
export const scribe_rune = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    kiosk: Resolvable
    cap: Resolvable
    character_id: string
    gear_id: string
    gear_template: Resolvable
    rune_item_id: string
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::scribe_rune`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.id(tx, args.gear_id),
      ctx.obj(tx, args.gear_template, false),
      ctx.pure.id(tx, args.rune_item_id),
      ctx.pin(tx, 'item_protected_policy', false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::crush_gear` — TERMINAL (&Random): last command of its transaction.
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg gear_ids — vector<ID>
 */
export const crush_gear = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; gear_ids: readonly string[] }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::crush_gear`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.vector(tx, 'id', args.gear_ids),
      ctx.pin(tx, 'item_protected_policy', false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::redeem_rune`
 * @arg claim — &mut CrushClaim
 * @arg template — &ItemTemplate
 * @arg existing — Option<ID>
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 */
export const redeem_rune = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    claim: Resolvable
    template: Resolvable
    existing: string | null | undefined
    kiosk: Resolvable
    cap: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::redeem_rune`,
    arguments: [
      ctx.obj(tx, args.claim, true),
      ctx.obj(tx, args.template, false),
      ctx.pure.option(tx, 'id', args.existing ?? null),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'item_policy', false),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::discard_crush_claim`
 * @arg claim — CrushClaim
 */
export const discard_crush_claim = (tx: Transaction, ctx: DoorCtx, args: { claim: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::discard_crush_claim`,
    arguments: [ctx.obj(tx, args.claim, true), ctx.pin(tx, 'version', false)],
  })

/**
 * `api::open_loot_box` — TERMINAL (&Random): last command of its transaction.
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg box_item_id — ID
 * @arg box_template — &ItemTemplate
 */
export const open_loot_box = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; box_item_id: string; box_template: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::open_loot_box`,
    arguments: [
      ctx.pin(tx, 'loot_registry', false),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.box_item_id),
      ctx.obj(tx, args.box_template, false),
      ctx.pin(tx, 'item_protected_policy', false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::claim_loot` — TERMINAL (&Random): last command of its transaction.
 * @arg claim — BoxClaim
 * @arg rolled_template — &ItemTemplate
 * @arg existing — Option<ID>
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 */
export const claim_loot = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    claim: Resolvable
    rolled_template: Resolvable
    existing: string | null | undefined
    kiosk: Resolvable
    cap: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::claim_loot`,
    arguments: [
      ctx.obj(tx, args.claim, true),
      ctx.obj(tx, args.rolled_template, false),
      ctx.pure.option(tx, 'id', args.existing ?? null),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'item_policy', false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::burn_item`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg item_id — ID
 * @arg amount — u32
 */
export const burn_item = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; item_id: string; amount: number }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::burn_item`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'item_protected_policy', false),
      ctx.pure.id(tx, args.item_id),
      ctx.pure.u32(tx, args.amount),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::buy`
 * @arg sale — &mut Sale
 * @arg template — &ItemTemplate
 * @arg quantity — u32
 * @arg payment — Coin<SUI>
 * @arg existing — Option<ID>
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 */
export const buy = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    sale: Resolvable
    template: Resolvable
    quantity: number
    payment: Resolvable
    existing: string | null | undefined
    kiosk: Resolvable
    cap: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::buy`,
    arguments: [
      ctx.obj(tx, args.sale, true),
      ctx.obj(tx, args.template, false),
      ctx.pure.u32(tx, args.quantity),
      ctx.obj(tx, args.payment, true),
      ctx.pure.option(tx, 'id', args.existing ?? null),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'item_policy', false),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::claim_airdrop`
 * @arg drop — &mut Airdrop
 * @arg template — &ItemTemplate
 * @arg existing — Option<ID>
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 */
export const claim_airdrop = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    drop: Resolvable
    template: Resolvable
    existing: string | null | undefined
    kiosk: Resolvable
    cap: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::claim_airdrop`,
    arguments: [
      ctx.obj(tx, args.drop, true),
      ctx.obj(tx, args.template, false),
      ctx.pure.option(tx, 'id', args.existing ?? null),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'item_policy', false),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::redeem_giftcard`
 * @arg card — Giftcard
 * @arg template — &ItemTemplate
 * @arg existing — Option<ID>
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 */
export const redeem_giftcard = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    card: Resolvable
    template: Resolvable
    existing: string | null | undefined
    kiosk: Resolvable
    cap: Resolvable
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::redeem_giftcard`,
    arguments: [
      ctx.obj(tx, args.card, true),
      ctx.obj(tx, args.template, false),
      ctx.pure.option(tx, 'id', args.existing ?? null),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'item_policy', false),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::enter_dungeon` — TERMINAL (&Random): last command of its transaction.
 * @arg w — &World
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg zx — u32
 * @arg zz — u32
 * @arg key_id — ID
 */
export const enter_dungeon = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    w: Resolvable
    kiosk: Resolvable
    cap: Resolvable
    character_id: string
    zx: number
    zz: number
    key_id: string
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::enter_dungeon`,
    arguments: [
      ctx.obj(tx, args.w, false),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.u32(tx, args.zx),
      ctx.pure.u32(tx, args.zz),
      ctx.pure.id(tx, args.key_id),
      ctx.pin(tx, 'item_protected_policy', false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::engage_dungeon_room`
 * @arg w — &World
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg access — u8
 */
export const engage_dungeon_room = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { w: Resolvable; kiosk: Resolvable; cap: Resolvable; character_id: string; access: number }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::engage_dungeon_room`,
    arguments: [
      ctx.obj(tx, args.w, false),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pure.u8(tx, args.access),
      ctx.pin(tx, 'character_protected_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::join_dungeon_room`
 * @arg f — &mut Fight
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 */
export const join_dungeon_room = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { f: Resolvable; kiosk: Resolvable; cap: Resolvable; character_id: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::join_dungeon_room`,
    arguments: [
      ctx.obj(tx, args.f, true),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pin(tx, 'character_protected_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::join_dungeon_room_grouped`
 * @arg f — &mut Fight
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 * @arg shared_party — &Party
 */
export const join_dungeon_room_grouped = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { f: Resolvable; kiosk: Resolvable; cap: Resolvable; character_id: string; shared_party: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::join_dungeon_room_grouped`,
    arguments: [
      ctx.obj(tx, args.f, true),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.obj(tx, args.shared_party, false),
      ctx.pin(tx, 'character_protected_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::settle_dungeon_room` — TERMINAL (&Random): last command of its transaction.
 * @arg w — &World
 * @arg f — &mut Fight
 * @arg fighter_idx — u64
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 */
export const settle_dungeon_room = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { w: Resolvable; f: Resolvable; fighter_idx: bigint | number | string; kiosk: Resolvable; cap: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::settle_dungeon_room`,
    arguments: [
      ctx.obj(tx, args.w, false),
      ctx.obj(tx, args.f, true),
      ctx.pure.u64(tx, args.fighter_idx),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'character_policy', false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::give_up_dungeon_room`
 * @arg f — &mut Fight
 * @arg fighter_idx — u64
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 */
export const give_up_dungeon_room = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { f: Resolvable; fighter_idx: bigint | number | string; kiosk: Resolvable; cap: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::give_up_dungeon_room`,
    arguments: [
      ctx.obj(tx, args.f, true),
      ctx.pure.u64(tx, args.fighter_idx),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'character_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::abandon_dungeon_run`
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 */
export const abandon_dungeon_run = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { kiosk: Resolvable; cap: Resolvable; character_id: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::abandon_dungeon_run`,
    arguments: [
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::create_kolizeum` — TERMINAL (&Random): last command of its transaction.
 * @arg pledge — Coin<SUI>
 * @arg format — u64
 * @arg level_min — u16
 * @arg level_max — u16
 * @arg access — u8
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 */
export const create_kolizeum = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    pledge: Resolvable
    format: bigint | number | string
    level_min: number
    level_max: number
    access: number
    kiosk: Resolvable
    cap: Resolvable
    character_id: string
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::create_kolizeum`,
    arguments: [
      ctx.obj(tx, args.pledge, true),
      ctx.pure.u64(tx, args.format),
      ctx.pure.u16(tx, args.level_min),
      ctx.pure.u16(tx, args.level_max),
      ctx.pure.u8(tx, args.access),
      ctx.pin(tx, 'character_protected_policy', false),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::create_kolizeum_friends` — TERMINAL (&Random): last command of its transaction.
 * @arg pledge — Coin<SUI>
 * @arg format — u64
 * @arg level_min — u16
 * @arg level_max — u16
 * @arg access — u8
 * @arg list — &FriendList
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 */
export const create_kolizeum_friends = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    pledge: Resolvable
    format: bigint | number | string
    level_min: number
    level_max: number
    access: number
    list: Resolvable
    kiosk: Resolvable
    cap: Resolvable
    character_id: string
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::create_kolizeum_friends`,
    arguments: [
      ctx.obj(tx, args.pledge, true),
      ctx.pure.u64(tx, args.format),
      ctx.pure.u16(tx, args.level_min),
      ctx.pure.u16(tx, args.level_max),
      ctx.pure.u8(tx, args.access),
      ctx.obj(tx, args.list, false),
      ctx.pin(tx, 'character_protected_policy', false),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::join_kolizeum`
 * @arg lobby — &mut Kolizeum
 * @arg f — &mut Fight
 * @arg pledge — Coin<SUI>
 * @arg side — u8
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 * @arg character_id — ID
 */
export const join_kolizeum = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    lobby: Resolvable
    f: Resolvable
    pledge: Resolvable
    side: number
    kiosk: Resolvable
    cap: Resolvable
    character_id: string
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::join_kolizeum`,
    arguments: [
      ctx.obj(tx, args.lobby, true),
      ctx.obj(tx, args.f, true),
      ctx.obj(tx, args.pledge, true),
      ctx.pure.u8(tx, args.side),
      ctx.pin(tx, 'character_protected_policy', false),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pure.id(tx, args.character_id),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::start_kolizeum` — TERMINAL (&Random): last command of its transaction.
 * @arg lobby — &mut Kolizeum
 * @arg f — &mut Fight
 */
export const start_kolizeum = (tx: Transaction, ctx: DoorCtx, args: { lobby: Resolvable; f: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::start_kolizeum`,
    arguments: [
      ctx.obj(tx, args.lobby, true),
      ctx.obj(tx, args.f, true),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::settle_kolizeum` — TERMINAL (&Random): last command of its transaction.
 * @arg lobby — &mut Kolizeum
 * @arg f — &mut Fight
 * @arg fighter_idx — u64
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 */
export const settle_kolizeum = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { lobby: Resolvable; f: Resolvable; fighter_idx: bigint | number | string; kiosk: Resolvable; cap: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::settle_kolizeum`,
    arguments: [
      ctx.obj(tx, args.lobby, true),
      ctx.obj(tx, args.f, true),
      ctx.pure.u64(tx, args.fighter_idx),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'character_policy', false),
      tx.object.random(),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::exit_kolizeum`
 * @arg lobby — &mut Kolizeum
 * @arg f — &mut Fight
 * @arg fighter_idx — u64
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 */
export const exit_kolizeum = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { lobby: Resolvable; f: Resolvable; fighter_idx: bigint | number | string; kiosk: Resolvable; cap: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::exit_kolizeum`,
    arguments: [
      ctx.obj(tx, args.lobby, true),
      ctx.obj(tx, args.f, true),
      ctx.pure.u64(tx, args.fighter_idx),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'character_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::forfeit_kolizeum`
 * @arg f — &mut Fight
 * @arg fighter_idx — u64
 * @arg kiosk — &mut Kiosk
 * @arg cap — &KioskOwnerCap
 */
export const forfeit_kolizeum = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { f: Resolvable; fighter_idx: bigint | number | string; kiosk: Resolvable; cap: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::forfeit_kolizeum`,
    arguments: [
      ctx.obj(tx, args.f, true),
      ctx.pure.u64(tx, args.fighter_idx),
      ctx.obj(tx, args.kiosk, true),
      ctx.obj(tx, args.cap, false),
      ctx.pin(tx, 'character_policy', false),
      ctx.pin(tx, 'version', false),
      tx.object.clock(),
    ],
  })

/**
 * `api::sweep_kolizeum`
 * @arg lobby — Kolizeum
 */
export const sweep_kolizeum = (tx: Transaction, ctx: DoorCtx, args: { lobby: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::sweep_kolizeum`,
    arguments: [ctx.obj(tx, args.lobby, true), ctx.pin(tx, 'version', false)],
  })

/**
 * `api::create_friend_list`
 * (no caller arguments)
 */
export const create_friend_list = (tx: Transaction, ctx: DoorCtx, args: Record<string, never>) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::create_friend_list`,
    arguments: [ctx.pin(tx, 'friend_registry', true), ctx.pin(tx, 'version', false)],
  })

/**
 * `api::add_friend`
 * @arg list — &mut FriendList
 * @arg addr — address
 */
export const add_friend = (tx: Transaction, ctx: DoorCtx, args: { list: Resolvable; addr: string }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::add_friend`,
    arguments: [ctx.obj(tx, args.list, true), ctx.pure.address(tx, args.addr), ctx.pin(tx, 'version', false)],
  })

/**
 * `api::remove_friend`
 * @arg list — &mut FriendList
 * @arg addr — address
 */
export const remove_friend = (tx: Transaction, ctx: DoorCtx, args: { list: Resolvable; addr: string }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::remove_friend`,
    arguments: [ctx.obj(tx, args.list, true), ctx.pure.address(tx, args.addr), ctx.pin(tx, 'version', false)],
  })

/**
 * `api::trade_create`
 * @arg counterparty — address
 */
export const trade_create = (tx: Transaction, ctx: DoorCtx, args: { counterparty: string }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::trade_create`,
    arguments: [ctx.pure.address(tx, args.counterparty), ctx.pin(tx, 'version', false)],
  })

/**
 * `api::trade_deposit_item_cap`
 * @arg t — &mut Trade
 * @arg cap — PurchaseCap<Item>
 */
export const trade_deposit_item_cap = (tx: Transaction, ctx: DoorCtx, args: { t: Resolvable; cap: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::trade_deposit_item_cap`,
    arguments: [ctx.obj(tx, args.t, true), ctx.obj(tx, args.cap, true), ctx.pin(tx, 'version', false)],
  })

/**
 * `api::trade_deposit_character_cap`
 * @arg t — &mut Trade
 * @arg cap — PurchaseCap<Character>
 * @arg kiosk — &Kiosk
 * @arg kiosk_cap — &KioskOwnerCap
 */
export const trade_deposit_character_cap = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { t: Resolvable; cap: Resolvable; kiosk: Resolvable; kiosk_cap: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::trade_deposit_character_cap`,
    arguments: [
      ctx.obj(tx, args.t, true),
      ctx.obj(tx, args.cap, true),
      ctx.obj(tx, args.kiosk, false),
      ctx.obj(tx, args.kiosk_cap, false),
      ctx.pin(tx, 'version', false),
    ],
  })

/**
 * `api::trade_withdraw_item_cap`
 * @arg t — &mut Trade
 * @arg item — ID
 */
export const trade_withdraw_item_cap = (tx: Transaction, ctx: DoorCtx, args: { t: Resolvable; item: string }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::trade_withdraw_item_cap`,
    arguments: [ctx.obj(tx, args.t, true), ctx.pure.id(tx, args.item), ctx.pin(tx, 'version', false)],
  })

/**
 * `api::trade_withdraw_character_cap`
 * @arg t — &mut Trade
 * @arg item — ID
 */
export const trade_withdraw_character_cap = (tx: Transaction, ctx: DoorCtx, args: { t: Resolvable; item: string }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::trade_withdraw_character_cap`,
    arguments: [ctx.obj(tx, args.t, true), ctx.pure.id(tx, args.item), ctx.pin(tx, 'version', false)],
  })

/**
 * `api::trade_deposit_sui`
 * @arg t — &mut Trade
 * @arg coin — Coin<SUI>
 */
export const trade_deposit_sui = (tx: Transaction, ctx: DoorCtx, args: { t: Resolvable; coin: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::trade_deposit_sui`,
    arguments: [ctx.obj(tx, args.t, true), ctx.obj(tx, args.coin, true), ctx.pin(tx, 'version', false)],
  })

/**
 * `api::trade_withdraw_sui`
 * @arg t — &mut Trade
 * @arg amount — u64
 */
export const trade_withdraw_sui = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { t: Resolvable; amount: bigint | number | string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::trade_withdraw_sui`,
    arguments: [ctx.obj(tx, args.t, true), ctx.pure.u64(tx, args.amount), ctx.pin(tx, 'version', false)],
  })

/**
 * `api::trade_accept`
 * @arg t — &mut Trade
 * @arg seen_version — u64
 */
export const trade_accept = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { t: Resolvable; seen_version: bigint | number | string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::trade_accept`,
    arguments: [ctx.obj(tx, args.t, true), ctx.pure.u64(tx, args.seen_version), ctx.pin(tx, 'version', false)],
  })

/**
 * `api::trade_claim_item_cap`
 * @arg t — &mut Trade
 * @arg item — ID
 */
export const trade_claim_item_cap = (tx: Transaction, ctx: DoorCtx, args: { t: Resolvable; item: string }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::trade_claim_item_cap`,
    arguments: [ctx.obj(tx, args.t, true), ctx.pure.id(tx, args.item), ctx.pin(tx, 'version', false)],
  })

/**
 * `api::trade_claim_character_cap`
 * @arg t — &mut Trade
 * @arg item — ID
 */
export const trade_claim_character_cap = (tx: Transaction, ctx: DoorCtx, args: { t: Resolvable; item: string }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::trade_claim_character_cap`,
    arguments: [ctx.obj(tx, args.t, true), ctx.pure.id(tx, args.item), ctx.pin(tx, 'version', false)],
  })

/**
 * `api::trade_claim_sui`
 * @arg t — &mut Trade
 */
export const trade_claim_sui = (tx: Transaction, ctx: DoorCtx, args: { t: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::trade_claim_sui`,
    arguments: [ctx.obj(tx, args.t, true), ctx.pin(tx, 'version', false)],
  })

/**
 * `api::trade_destroy`
 * @arg t — Trade
 */
export const trade_destroy = (tx: Transaction, ctx: DoorCtx, args: { t: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::api::trade_destroy`,
    arguments: [ctx.obj(tx, args.t, true), ctx.pin(tx, 'version', false)],
  })

/** Every door, by name — { params: caller-facing names, terminal: carries &Random }. */
export const DOORS = {
  create_character: {
    params: ['payment', 'kiosk', 'cap', 'raw_name', 'classe', 'male', 'color_1', 'color_2', 'color_3'],
    terminal: false,
  },
  join_world: { params: ['kiosk', 'cap', 'character_id', 'world'], terminal: false },
  search_zone: { params: ['kiosk', 'cap', 'character_id', 'x', 'z', 'w'], terminal: true },
  raise_stat: { params: ['kiosk', 'cap', 'character_id', 'stat', 'amount'], terminal: false },
  raise_spell: { params: ['kiosk', 'cap', 'character_id', 'spell'], terminal: false },
  equip_item: { params: ['kiosk', 'cap', 'character_id', 'slot', 'item_id'], terminal: false },
  unequip_item: { params: ['kiosk', 'cap', 'character_id', 'slot', 'receiving'], terminal: false },
  feed_kiosk_pet: { params: ['kiosk', 'cap', 'pet_template', 'pet_id', 'food_id'], terminal: false },
  delete_character: { params: ['kiosk', 'cap', 'character_id'], terminal: false },
  engage_fight: { params: ['kiosk', 'cap', 'character_id', 'w', 'zx', 'zz', 'group_index', 'access'], terminal: false },
  add_fight_mob: { params: ['build', 'template'], terminal: false },
  launch_fight: { params: ['build'], terminal: false },
  challenge_duel: { params: ['kiosk', 'cap', 'character_id', 'x', 'z', 'access'], terminal: true },
  join_fight: { params: ['f', 'kiosk', 'cap', 'character_id', 'team', 'access'], terminal: false },
  join_fight_grouped: { params: ['f', 'kiosk', 'cap', 'character_id', 'team', 'shared_party'], terminal: false },
  place_fighter: { params: ['f', 'fighter_idx', 'cell'], terminal: false },
  ready_fighter: { params: ['f', 'fighter_idx'], terminal: false },
  start_fight: { params: ['f'], terminal: true },
  cast_spell: { params: ['f', 'fighter_idx', 'spell', 'target_cell'], terminal: false },
  weapon_strike: { params: ['f', 'fighter_idx', 'target_cell'], terminal: false },
  move_fighter: { params: ['f', 'path'], terminal: false },
  end_fight_turn: { params: ['f'], terminal: true },
  crank_fight: { params: ['f'], terminal: true },
  forfeit_fight: { params: ['f', 'fighter_idx', 'kiosk', 'cap'], terminal: false },
  settle_fight: { params: ['f', 'fighter_idx', 'kiosk', 'cap'], terminal: true },
  claim_fight_drop: { params: ['f', 'fighter_idx', 'template', 'existing', 'kiosk', 'cap'], terminal: true },
  close_fight: { params: ['f'], terminal: false },
  create_party: { params: ['kiosk', 'cap', 'character_id'], terminal: false },
  party_invite: { params: ['p', 'kiosk', 'cap', 'leader_id', 'invited_character'], terminal: false },
  party_accept: { params: ['p', 'kiosk', 'cap', 'character_id'], terminal: false },
  party_decline: { params: ['p', 'kiosk', 'cap', 'character_id'], terminal: false },
  party_rescind: { params: ['p', 'kiosk', 'cap', 'leader_id', 'invited_character'], terminal: false },
  party_leave: { params: ['p', 'kiosk', 'cap', 'character_id'], terminal: false },
  party_kick: { params: ['p', 'kiosk', 'cap', 'leader_id', 'target_character'], terminal: false },
  party_disband: { params: ['p', 'kiosk', 'cap', 'leader_id'], terminal: false },
  use_consumable: { params: ['kiosk', 'cap', 'character_id', 'item_id', 'template'], terminal: false },
  gather: {
    params: [
      'w',
      'kiosk',
      'cap',
      'character_id',
      'zx',
      'zz',
      'pack_index',
      'template',
      'rare_template',
      'existing',
      'existing_rare',
    ],
    terminal: true,
  },
  resolve_ambush: { params: ['kiosk', 'cap', 'character_id', 'protector_template'], terminal: false },
  craft: {
    params: ['recipe', 'kiosk', 'cap', 'character_id', 'input_item_ids', 'output_template', 'existing'],
    terminal: true,
  },
  scribe_rune: { params: ['kiosk', 'cap', 'character_id', 'gear_id', 'gear_template', 'rune_item_id'], terminal: true },
  crush_gear: { params: ['kiosk', 'cap', 'gear_ids'], terminal: true },
  redeem_rune: { params: ['claim', 'template', 'existing', 'kiosk', 'cap'], terminal: false },
  discard_crush_claim: { params: ['claim'], terminal: false },
  open_loot_box: { params: ['kiosk', 'cap', 'box_item_id', 'box_template'], terminal: true },
  claim_loot: { params: ['claim', 'rolled_template', 'existing', 'kiosk', 'cap'], terminal: true },
  burn_item: { params: ['kiosk', 'cap', 'item_id', 'amount'], terminal: false },
  buy: { params: ['sale', 'template', 'quantity', 'payment', 'existing', 'kiosk', 'cap'], terminal: false },
  claim_airdrop: { params: ['drop', 'template', 'existing', 'kiosk', 'cap'], terminal: false },
  redeem_giftcard: { params: ['card', 'template', 'existing', 'kiosk', 'cap'], terminal: false },
  enter_dungeon: { params: ['w', 'kiosk', 'cap', 'character_id', 'zx', 'zz', 'key_id'], terminal: true },
  engage_dungeon_room: { params: ['w', 'kiosk', 'cap', 'character_id', 'access'], terminal: false },
  join_dungeon_room: { params: ['f', 'kiosk', 'cap', 'character_id'], terminal: false },
  join_dungeon_room_grouped: { params: ['f', 'kiosk', 'cap', 'character_id', 'shared_party'], terminal: false },
  settle_dungeon_room: { params: ['w', 'f', 'fighter_idx', 'kiosk', 'cap'], terminal: true },
  give_up_dungeon_room: { params: ['f', 'fighter_idx', 'kiosk', 'cap'], terminal: false },
  abandon_dungeon_run: { params: ['kiosk', 'cap', 'character_id'], terminal: false },
  create_kolizeum: {
    params: ['pledge', 'format', 'level_min', 'level_max', 'access', 'kiosk', 'cap', 'character_id'],
    terminal: true,
  },
  create_kolizeum_friends: {
    params: ['pledge', 'format', 'level_min', 'level_max', 'access', 'list', 'kiosk', 'cap', 'character_id'],
    terminal: true,
  },
  join_kolizeum: { params: ['lobby', 'f', 'pledge', 'side', 'kiosk', 'cap', 'character_id'], terminal: false },
  start_kolizeum: { params: ['lobby', 'f'], terminal: true },
  settle_kolizeum: { params: ['lobby', 'f', 'fighter_idx', 'kiosk', 'cap'], terminal: true },
  exit_kolizeum: { params: ['lobby', 'f', 'fighter_idx', 'kiosk', 'cap'], terminal: false },
  forfeit_kolizeum: { params: ['f', 'fighter_idx', 'kiosk', 'cap'], terminal: false },
  sweep_kolizeum: { params: ['lobby'], terminal: false },
  create_friend_list: { params: [], terminal: false },
  add_friend: { params: ['list', 'addr'], terminal: false },
  remove_friend: { params: ['list', 'addr'], terminal: false },
  trade_create: { params: ['counterparty'], terminal: false },
  trade_deposit_item_cap: { params: ['t', 'cap'], terminal: false },
  trade_deposit_character_cap: { params: ['t', 'cap', 'kiosk', 'kiosk_cap'], terminal: false },
  trade_withdraw_item_cap: { params: ['t', 'item'], terminal: false },
  trade_withdraw_character_cap: { params: ['t', 'item'], terminal: false },
  trade_deposit_sui: { params: ['t', 'coin'], terminal: false },
  trade_withdraw_sui: { params: ['t', 'amount'], terminal: false },
  trade_accept: { params: ['t', 'seen_version'], terminal: false },
  trade_claim_item_cap: { params: ['t', 'item'], terminal: false },
  trade_claim_character_cap: { params: ['t', 'item'], terminal: false },
  trade_claim_sui: { params: ['t'], terminal: false },
  trade_destroy: { params: ['t'], terminal: false },
}
