// SPDX-License-Identifier: LicenseRef-AresRPG-Source-Available
// © 2026 Sceat — All rights reserved. See LICENSE.
// GENERATED by scripts/generate_seed_doors.mjs from Move String key structs — DO NOT EDIT.

export const SEED_STRING_KEYS = Object.freeze({
  WorldSeedKey: Object.freeze({ module: 'seed', name: 'WorldSeedKey' }),
  SealKey: Object.freeze({ module: 'seed', name: 'SealKey' }),
  MobKey: Object.freeze({ module: 'mob_template', name: 'MobKey' }),
  SpellKey: Object.freeze({ module: 'spell_template', name: 'SpellKey' }),
  RecipeKey: Object.freeze({ module: 'crafting', name: 'RecipeKey' }),
  SaleKey: Object.freeze({ module: 'shop', name: 'SaleKey' }),
  AirdropKey: Object.freeze({ module: 'shop', name: 'AirdropKey' }),
  GiftcardKey: Object.freeze({ module: 'shop', name: 'GiftcardKey' }),
})
