// SPDX-License-Identifier: LicenseRef-AresRPG-Source-Available
// © 2026 Sceat — All rights reserved. See LICENSE.
// GENERATED by scripts/generate_doors.mjs from seed.move and its Move value constructors — DO NOT EDIT.
// One builder per seeding door: door(tx, ctx, args) composes the move call onto the given
// Transaction and returns its Move result for further composition.
// `ctx` is the SDK's bound context ({ pins, obj, pin, receiving }) — every object input is
// emitted PRE-RESOLVED (objectRef / sharedObjectRef / offline system helpers), so building the
// transaction costs ZERO RPC roundtrips. Doors marked terminal take &Random: THE TERMINAL LAW —
// such a call must be the LAST command of its transaction (an inspectable roll is a free re-roll).
/* eslint-disable max-lines -- generated projection: one builder per door, size follows the Move contract */

import type { Transaction, TransactionObjectArgument } from '@mysten/sui/transactions'

import type { DoorCtx, Resolvable } from './client.ts'

/**
 * `seed::begin_batch`
 * @arg publisher — &Publisher
 */
export const begin_batch = (tx: Transaction, ctx: DoorCtx, args: { publisher: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::begin_batch`,
    arguments: [ctx.obj(tx, args.publisher, false), ctx.pin(tx, 'template_registry', true)],
  })

/**
 * `seed::new_item_template`
 * @arg _ — &SeedCap
 * @arg name — String
 * @arg item_type — String
 * @arg category — String
 * @arg level — u8
 */
export const new_item_template = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { _: Resolvable; name: string; item_type: string; category: string; level: number }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::new_item_template`,
    arguments: [
      ctx.obj(tx, args._, false),
      ctx.pin(tx, 'template_registry', true),
      tx.pure.string(args.name),
      tx.pure.string(args.item_type),
      tx.pure.string(args.category),
      tx.pure.u8(args.level),
    ],
  })

/**
 * `seed::set_stats`
 * @arg template — &mut ItemTemplate
 * @arg min — ItemStatistics
 * @arg max — ItemStatistics
 */
export const set_stats = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { template: Resolvable; min: Resolvable; max: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::set_stats`,
    arguments: [ctx.obj(tx, args.template, true), ctx.obj(tx, args.min, true), ctx.obj(tx, args.max, true)],
  })

/**
 * `seed::set_damages`
 * @arg template — &mut ItemTemplate
 * @arg lines — vector<ItemDamages>
 */
export const set_damages = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { template: Resolvable; lines: readonly TransactionObjectArgument[] }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::set_damages`,
    arguments: [ctx.obj(tx, args.template, true), tx.makeMoveVec({ elements: [...args.lines] })],
  })

/**
 * `seed::set_consumable_heal`
 * @arg template — &mut ItemTemplate
 * @arg amount — u32
 */
export const set_consumable_heal = (tx: Transaction, ctx: DoorCtx, args: { template: Resolvable; amount: number }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::set_consumable_heal`,
    arguments: [ctx.obj(tx, args.template, true), tx.pure.u32(args.amount)],
  })

/**
 * `seed::set_consumable_reset_stats`
 * @arg template — &mut ItemTemplate
 */
export const set_consumable_reset_stats = (tx: Transaction, ctx: DoorCtx, args: { template: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::set_consumable_reset_stats`,
    arguments: [ctx.obj(tx, args.template, true)],
  })

/**
 * `seed::set_consumable_reset_spells`
 * @arg template — &mut ItemTemplate
 */
export const set_consumable_reset_spells = (tx: Transaction, ctx: DoorCtx, args: { template: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::set_consumable_reset_spells`,
    arguments: [ctx.obj(tx, args.template, true)],
  })

/**
 * `seed::set_consumable_recall`
 * @arg template — &mut ItemTemplate
 */
export const set_consumable_recall = (tx: Transaction, ctx: DoorCtx, args: { template: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::set_consumable_recall`,
    arguments: [ctx.obj(tx, args.template, true)],
  })

/**
 * `seed::set_consumable_loot_box`
 * @arg template — &mut ItemTemplate
 */
export const set_consumable_loot_box = (tx: Transaction, ctx: DoorCtx, args: { template: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::set_consumable_loot_box`,
    arguments: [ctx.obj(tx, args.template, true)],
  })

/**
 * `seed::freeze_item_template`
 * @arg template — ItemTemplate
 */
export const freeze_item_template = (tx: Transaction, ctx: DoorCtx, args: { template: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::freeze_item_template`,
    arguments: [ctx.obj(tx, args.template, true)],
  })

/**
 * `seed::freeze_loot_box_template`
 * @arg template — ItemTemplate
 */
export const freeze_loot_box_template = (tx: Transaction, ctx: DoorCtx, args: { template: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::freeze_loot_box_template`,
    arguments: [ctx.obj(tx, args.template, true), ctx.pin(tx, 'loot_registry', true)],
  })

/**
 * `seed::new_mob_template`
 * @arg _ — &SeedCap
 * @arg name — String
 * @arg mob_type — String
 * @arg element — String
 * @arg level_min — u8
 * @arg level_max — u8
 * @arg hp — u64
 * @arg ap — u8
 * @arg mp — u8
 * @arg agility — u16
 * @arg wisdom — u16
 * @arg earth_resistance — u16
 * @arg fire_resistance — u16
 * @arg water_resistance — u16
 * @arg air_resistance — u16
 * @arg spells — vector<MobSpell>
 * @arg loot — vector<LootEntry>
 * @arg xp — u64
 */
export const new_mob_template = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    _: Resolvable
    name: string
    mob_type: string
    element: string
    level_min: number
    level_max: number
    hp: bigint | number | string
    ap: number
    mp: number
    agility: number
    wisdom: number
    earth_resistance: number
    fire_resistance: number
    water_resistance: number
    air_resistance: number
    spells: readonly TransactionObjectArgument[]
    loot: readonly TransactionObjectArgument[]
    xp: bigint | number | string
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::new_mob_template`,
    arguments: [
      ctx.obj(tx, args._, false),
      ctx.pin(tx, 'template_registry', true),
      tx.pure.string(args.name),
      tx.pure.string(args.mob_type),
      tx.pure.string(args.element),
      tx.pure.u8(args.level_min),
      tx.pure.u8(args.level_max),
      tx.pure.u64(args.hp),
      tx.pure.u8(args.ap),
      tx.pure.u8(args.mp),
      tx.pure.u16(args.agility),
      tx.pure.u16(args.wisdom),
      tx.pure.u16(args.earth_resistance),
      tx.pure.u16(args.fire_resistance),
      tx.pure.u16(args.water_resistance),
      tx.pure.u16(args.air_resistance),
      tx.makeMoveVec({ elements: [...args.spells] }),
      tx.makeMoveVec({ elements: [...args.loot] }),
      tx.pure.u64(args.xp),
    ],
  })

/**
 * `seed::freeze_mob_template`
 * @arg template — MobTemplate
 */
export const freeze_mob_template = (tx: Transaction, ctx: DoorCtx, args: { template: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::freeze_mob_template`,
    arguments: [ctx.obj(tx, args.template, true)],
  })

/**
 * `seed::new_spell`
 * @arg _ — &SeedCap
 * @arg name — String
 * @arg classe — String
 * @arg unlock_level — u8
 * @arg levels — vector<SpellLevel>
 */
export const new_spell = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    _: Resolvable
    name: string
    classe: string
    unlock_level: number
    levels: readonly TransactionObjectArgument[]
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::new_spell`,
    arguments: [
      ctx.obj(tx, args._, false),
      ctx.pin(tx, 'template_registry', true),
      tx.pure.string(args.name),
      tx.pure.string(args.classe),
      tx.pure.u8(args.unlock_level),
      tx.makeMoveVec({ elements: [...args.levels] }),
    ],
  })

/**
 * `seed::freeze_spell`
 * @arg template — SpellTemplate
 */
export const freeze_spell = (tx: Transaction, ctx: DoorCtx, args: { template: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::freeze_spell`,
    arguments: [ctx.obj(tx, args.template, true)],
  })

/**
 * `seed::new_recipe`
 * @arg _ — &SeedCap
 * @arg output_type — String
 * @arg output_template — ID
 * @arg input_templates — vector<ID>
 * @arg input_quantities — vector<u64>
 * @arg job — String
 */
export const new_recipe = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    _: Resolvable
    output_type: string
    output_template: string
    input_templates: readonly string[]
    input_quantities: readonly (bigint | number | string)[]
    job: string
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::new_recipe`,
    arguments: [
      ctx.obj(tx, args._, false),
      ctx.pin(tx, 'template_registry', true),
      tx.pure.string(args.output_type),
      tx.pure.id(args.output_template),
      tx.pure.vector('id', args.input_templates),
      tx.pure.vector('u64', args.input_quantities),
      tx.pure.string(args.job),
    ],
  })

/**
 * `seed::freeze_recipe`
 * @arg recipe — Recipe
 */
export const freeze_recipe = (tx: Transaction, ctx: DoorCtx, args: { recipe: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::freeze_recipe`,
    arguments: [ctx.obj(tx, args.recipe, true)],
  })

/**
 * `seed::new_sale`
 * @arg _ — &SeedCap
 * @arg item_type — String
 * @arg template — ID
 * @arg price — u64
 * @arg supply — u64
 */
export const new_sale = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    _: Resolvable
    item_type: string
    template: string
    price: bigint | number | string
    supply: bigint | number | string
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::new_sale`,
    arguments: [
      ctx.obj(tx, args._, false),
      ctx.pin(tx, 'template_registry', true),
      tx.pure.string(args.item_type),
      tx.pure.id(args.template),
      tx.pure.u64(args.price),
      tx.pure.u64(args.supply),
    ],
  })

/**
 * `seed::add_loot_reward`
 * @arg _ — &SeedCap
 * @arg box_template — &ItemTemplate
 * @arg reward_template — &ItemTemplate
 * @arg weight — u64
 * @arg amount — u32
 */
export const add_loot_reward = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    _: Resolvable
    box_template: Resolvable
    reward_template: Resolvable
    weight: bigint | number | string
    amount: number
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::add_loot_reward`,
    arguments: [
      ctx.obj(tx, args._, false),
      ctx.pin(tx, 'loot_registry', true),
      ctx.obj(tx, args.box_template, false),
      ctx.obj(tx, args.reward_template, false),
      tx.pure.u64(args.weight),
      tx.pure.u32(args.amount),
    ],
  })

/**
 * `seed::new_airdrop`
 * @arg _ — &SeedCap
 * @arg drop_id — String
 * @arg template — &ItemTemplate
 * @arg amount_each — u32
 * @arg whitelist — vector<address>
 */
export const new_airdrop = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { _: Resolvable; drop_id: string; template: Resolvable; amount_each: number; whitelist: readonly string[] }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::new_airdrop`,
    arguments: [
      ctx.obj(tx, args._, false),
      ctx.pin(tx, 'template_registry', true),
      tx.pure.string(args.drop_id),
      ctx.obj(tx, args.template, false),
      tx.pure.u32(args.amount_each),
      tx.pure.vector('address', args.whitelist),
    ],
  })

/**
 * `seed::new_giftcard`
 * @arg _ — &SeedCap
 * @arg card_id — String
 * @arg template — &ItemTemplate
 * @arg amount — u32
 */
export const new_giftcard = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { _: Resolvable; card_id: string; template: Resolvable; amount: number }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::new_giftcard`,
    arguments: [
      ctx.obj(tx, args._, false),
      ctx.pin(tx, 'template_registry', true),
      tx.pure.string(args.card_id),
      ctx.obj(tx, args.template, false),
      tx.pure.u32(args.amount),
    ],
  })

/**
 * `seed::set_world_mobs`
 * @arg _ — &SeedCap
 * @arg world — &mut World
 * @arg rows — vector<MobRow>
 */
export const set_world_mobs = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { _: Resolvable; world: Resolvable; rows: readonly TransactionObjectArgument[] }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::set_world_mobs`,
    arguments: [
      ctx.obj(tx, args._, false),
      ctx.obj(tx, args.world, true),
      tx.makeMoveVec({ elements: [...args.rows] }),
    ],
  })

/**
 * `seed::set_world_biome_window`
 * @arg _ — &SeedCap
 * @arg world — &mut World
 * @arg zone_x0 — u32
 * @arg zone_z0 — u32
 * @arg side — u16
 */
export const set_world_biome_window = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { _: Resolvable; world: Resolvable; zone_x0: number; zone_z0: number; side: number }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::set_world_biome_window`,
    arguments: [
      ctx.obj(tx, args._, false),
      ctx.obj(tx, args.world, true),
      tx.pure.u32(args.zone_x0),
      tx.pure.u32(args.zone_z0),
      tx.pure.u16(args.side),
    ],
  })

/**
 * `seed::append_world_biome_cells`
 * @arg _ — &SeedCap
 * @arg world — &mut World
 * @arg cells — vector<u8>
 */
export const append_world_biome_cells = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { _: Resolvable; world: Resolvable; cells: readonly number[] }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::append_world_biome_cells`,
    arguments: [ctx.obj(tx, args._, false), ctx.obj(tx, args.world, true), tx.pure.vector('u8', args.cells)],
  })

/**
 * `seed::set_world_resources`
 * @arg _ — &SeedCap
 * @arg world — &mut World
 * @arg rows — vector<ResourceRow>
 */
export const set_world_resources = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { _: Resolvable; world: Resolvable; rows: readonly TransactionObjectArgument[] }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::set_world_resources`,
    arguments: [
      ctx.obj(tx, args._, false),
      ctx.obj(tx, args.world, true),
      tx.makeMoveVec({ elements: [...args.rows] }),
    ],
  })

/**
 * `seed::set_world_dungeon_key`
 * @arg _ — &SeedCap
 * @arg world — &mut World
 * @arg item_type — String
 */
export const set_world_dungeon_key = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { _: Resolvable; world: Resolvable; item_type: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::set_world_dungeon_key`,
    arguments: [ctx.obj(tx, args._, false), ctx.obj(tx, args.world, true), tx.pure.string(args.item_type)],
  })

/**
 * `seed::set_world_dungeon_rooms`
 * @arg _ — &SeedCap
 * @arg world — &mut World
 * @arg rooms — vector<DungeonRoom>
 */
export const set_world_dungeon_rooms = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { _: Resolvable; world: Resolvable; rooms: readonly TransactionObjectArgument[] }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::set_world_dungeon_rooms`,
    arguments: [
      ctx.obj(tx, args._, false),
      ctx.obj(tx, args.world, true),
      tx.makeMoveVec({ elements: [...args.rooms] }),
    ],
  })

/**
 * `seed::mark_world_seeded`
 * @arg _ — &SeedCap
 * @arg world_name — String
 */
export const mark_world_seeded = (tx: Transaction, ctx: DoorCtx, args: { _: Resolvable; world_name: string }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::mark_world_seeded`,
    arguments: [ctx.obj(tx, args._, false), ctx.pin(tx, 'template_registry', true), tx.pure.string(args.world_name)],
  })

/**
 * `seed::destroy_seed_cap`
 * @arg cap — SeedCap
 */
export const destroy_seed_cap = (tx: Transaction, ctx: DoorCtx, args: { cap: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::destroy_seed_cap`,
    arguments: [ctx.obj(tx, args.cap, true)],
  })

/**
 * `seed::seal`
 * @arg publisher — &Publisher
 */
export const seal = (tx: Transaction, ctx: DoorCtx, args: { publisher: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::seed::seal`,
    arguments: [ctx.obj(tx, args.publisher, false), ctx.pin(tx, 'template_registry', true)],
  })

/**
 * `item_stats::new`
 * @arg vitality — u16
 * @arg wisdom — u16
 * @arg strength — u16
 * @arg intelligence — u16
 * @arg chance — u16
 * @arg agility — u16
 * @arg range — u16
 * @arg movement — u16
 * @arg action — u16
 * @arg critical — u16
 * @arg raw_damage — u16
 * @arg earth_resistance — u16
 * @arg fire_resistance — u16
 * @arg water_resistance — u16
 * @arg air_resistance — u16
 */
export const new_item_stats = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    vitality: number
    wisdom: number
    strength: number
    intelligence: number
    chance: number
    agility: number
    range: number
    movement: number
    action: number
    critical: number
    raw_damage: number
    earth_resistance: number
    fire_resistance: number
    water_resistance: number
    air_resistance: number
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.math_package}::item_stats::new`,
    arguments: [
      tx.pure.u16(args.vitality),
      tx.pure.u16(args.wisdom),
      tx.pure.u16(args.strength),
      tx.pure.u16(args.intelligence),
      tx.pure.u16(args.chance),
      tx.pure.u16(args.agility),
      tx.pure.u16(args.range),
      tx.pure.u16(args.movement),
      tx.pure.u16(args.action),
      tx.pure.u16(args.critical),
      tx.pure.u16(args.raw_damage),
      tx.pure.u16(args.earth_resistance),
      tx.pure.u16(args.fire_resistance),
      tx.pure.u16(args.water_resistance),
      tx.pure.u16(args.air_resistance),
    ],
  })

/**
 * `item_damages::new`
 * @arg from — u16
 * @arg to — u16
 * @arg damage_type — String
 * @arg element — String
 */
export const new_item_damages = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { from: number; to: number; damage_type: string; element: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.math_package}::item_damages::new`,
    arguments: [
      tx.pure.u16(args.from),
      tx.pure.u16(args.to),
      tx.pure.string(args.damage_type),
      tx.pure.string(args.element),
    ],
  })

/**
 * `spell_effect::new_effect`
 * @arg kind — u8
 * @arg element — String
 * @arg value — u32
 * @arg value_max — u32
 * @arg area_shape — u8
 * @arg area_size — u8
 * @arg target_filter — u8
 * @arg chance_bp — u16
 * @arg turns — u8
 * @arg stat — u8
 */
export const new_effect = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    kind: number
    element: string
    value: number
    value_max: number
    area_shape: number
    area_size: number
    target_filter: number
    chance_bp: number
    turns: number
    stat: number
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.math_package}::spell_effect::new_effect`,
    arguments: [
      tx.pure.u8(args.kind),
      tx.pure.string(args.element),
      tx.pure.u32(args.value),
      tx.pure.u32(args.value_max),
      tx.pure.u8(args.area_shape),
      tx.pure.u8(args.area_size),
      tx.pure.u8(args.target_filter),
      tx.pure.u16(args.chance_bp),
      tx.pure.u8(args.turns),
      tx.pure.u8(args.stat),
    ],
  })

/**
 * `spell_effect::new_spell_level`
 * @arg ap_cost — u8
 * @arg range_min — u8
 * @arg range_max — u8
 * @arg modifiable_range — bool
 * @arg line_of_sight — bool
 * @arg line_launch — bool
 * @arg free_cell — bool
 * @arg casts_per_turn — u8
 * @arg casts_per_target — u8
 * @arg cooldown_turns — u8
 * @arg crit_1_in — u16
 * @arg effects — vector<Effect>
 * @arg crit_effects — vector<Effect>
 */
export const new_spell_level = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    ap_cost: number
    range_min: number
    range_max: number
    modifiable_range: boolean
    line_of_sight: boolean
    line_launch: boolean
    free_cell: boolean
    casts_per_turn: number
    casts_per_target: number
    cooldown_turns: number
    crit_1_in: number
    effects: readonly TransactionObjectArgument[]
    crit_effects: readonly TransactionObjectArgument[]
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.math_package}::spell_effect::new_spell_level`,
    arguments: [
      tx.pure.u8(args.ap_cost),
      tx.pure.u8(args.range_min),
      tx.pure.u8(args.range_max),
      tx.pure.bool(args.modifiable_range),
      tx.pure.bool(args.line_of_sight),
      tx.pure.bool(args.line_launch),
      tx.pure.bool(args.free_cell),
      tx.pure.u8(args.casts_per_turn),
      tx.pure.u8(args.casts_per_target),
      tx.pure.u8(args.cooldown_turns),
      tx.pure.u16(args.crit_1_in),
      tx.makeMoveVec({ elements: [...args.effects] }),
      tx.makeMoveVec({ elements: [...args.crit_effects] }),
    ],
  })

/**
 * `mob_template::new_loot_entry`
 * @arg item_type — String
 * @arg chance_bp — u16
 * @arg min_qty — u8
 * @arg max_qty — u8
 */
export const new_mob_loot_entry = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { item_type: string; chance_bp: number; min_qty: number; max_qty: number }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::mob_template::new_loot_entry`,
    arguments: [
      tx.pure.string(args.item_type),
      tx.pure.u16(args.chance_bp),
      tx.pure.u8(args.min_qty),
      tx.pure.u8(args.max_qty),
    ],
  })

/**
 * `mob_template::new_mob_spell`
 * @arg name — String
 * @arg levels — vector<SpellLevel>
 */
export const new_mob_spell = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { name: string; levels: readonly TransactionObjectArgument[] }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::mob_template::new_mob_spell`,
    arguments: [tx.pure.string(args.name), tx.makeMoveVec({ elements: [...args.levels] })],
  })

/**
 * `world::new_mob_row`
 * @arg mob_type — String
 * @arg weight_bp — u16
 * @arg biomes — vector<u8>
 */
export const new_mob_row = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { mob_type: string; weight_bp: number; biomes: readonly number[] }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::world::new_mob_row`,
    arguments: [tx.pure.string(args.mob_type), tx.pure.u16(args.weight_bp), tx.pure.vector('u8', args.biomes)],
  })

/**
 * `world::new_resource_row`
 * @arg item_type — String
 * @arg job — String
 * @arg tier — u8
 * @arg protector — String
 * @arg rare_item_type — String
 * @arg biomes — vector<u8>
 */
export const new_resource_row = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    item_type: string
    job: string
    tier: number
    protector: string
    rare_item_type: string
    biomes: readonly number[]
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::world::new_resource_row`,
    arguments: [
      tx.pure.string(args.item_type),
      tx.pure.string(args.job),
      tx.pure.u8(args.tier),
      tx.pure.string(args.protector),
      tx.pure.string(args.rare_item_type),
      tx.pure.vector('u8', args.biomes),
    ],
  })

/**
 * `world::new_room_mob`
 * @arg mob_type — String
 * @arg level_scalar — u8
 */
export const new_room_mob = (tx: Transaction, ctx: DoorCtx, args: { mob_type: string; level_scalar: number }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::world::new_room_mob`,
    arguments: [tx.pure.string(args.mob_type), tx.pure.u8(args.level_scalar)],
  })

/**
 * `world::new_dungeon_room`
 * @arg mobs — vector<RoomMob>
 */
export const new_dungeon_room = (tx: Transaction, ctx: DoorCtx, args: { mobs: readonly TransactionObjectArgument[] }) =>
  tx.moveCall({
    target: `${ctx.pins.package}::world::new_dungeon_room`,
    arguments: [tx.makeMoveVec({ elements: [...args.mobs] })],
  })

/** Every door, by name — { params: caller-facing names, terminal: carries &Random }. */
export const DOORS = {
  begin_batch: { params: ['publisher'], terminal: false },
  new_item_template: { params: ['_', 'name', 'item_type', 'category', 'level'], terminal: false },
  set_stats: { params: ['template', 'min', 'max'], terminal: false },
  set_damages: { params: ['template', 'lines'], terminal: false },
  set_consumable_heal: { params: ['template', 'amount'], terminal: false },
  set_consumable_reset_stats: { params: ['template'], terminal: false },
  set_consumable_reset_spells: { params: ['template'], terminal: false },
  set_consumable_recall: { params: ['template'], terminal: false },
  set_consumable_loot_box: { params: ['template'], terminal: false },
  freeze_item_template: { params: ['template'], terminal: false },
  freeze_loot_box_template: { params: ['template'], terminal: false },
  new_mob_template: {
    params: [
      '_',
      'name',
      'mob_type',
      'element',
      'level_min',
      'level_max',
      'hp',
      'ap',
      'mp',
      'agility',
      'wisdom',
      'earth_resistance',
      'fire_resistance',
      'water_resistance',
      'air_resistance',
      'spells',
      'loot',
      'xp',
    ],
    terminal: false,
  },
  freeze_mob_template: { params: ['template'], terminal: false },
  new_spell: { params: ['_', 'name', 'classe', 'unlock_level', 'levels'], terminal: false },
  freeze_spell: { params: ['template'], terminal: false },
  new_recipe: {
    params: ['_', 'output_type', 'output_template', 'input_templates', 'input_quantities', 'job'],
    terminal: false,
  },
  freeze_recipe: { params: ['recipe'], terminal: false },
  new_sale: { params: ['_', 'item_type', 'template', 'price', 'supply'], terminal: false },
  add_loot_reward: { params: ['_', 'box_template', 'reward_template', 'weight', 'amount'], terminal: false },
  new_airdrop: { params: ['_', 'drop_id', 'template', 'amount_each', 'whitelist'], terminal: false },
  new_giftcard: { params: ['_', 'card_id', 'template', 'amount'], terminal: false },
  set_world_mobs: { params: ['_', 'world', 'rows'], terminal: false },
  set_world_biome_window: { params: ['_', 'world', 'zone_x0', 'zone_z0', 'side'], terminal: false },
  append_world_biome_cells: { params: ['_', 'world', 'cells'], terminal: false },
  set_world_resources: { params: ['_', 'world', 'rows'], terminal: false },
  set_world_dungeon_key: { params: ['_', 'world', 'item_type'], terminal: false },
  set_world_dungeon_rooms: { params: ['_', 'world', 'rooms'], terminal: false },
  mark_world_seeded: { params: ['_', 'world_name'], terminal: false },
  destroy_seed_cap: { params: ['cap'], terminal: false },
  seal: { params: ['publisher'], terminal: false },
  new_item_stats: {
    params: [
      'vitality',
      'wisdom',
      'strength',
      'intelligence',
      'chance',
      'agility',
      'range',
      'movement',
      'action',
      'critical',
      'raw_damage',
      'earth_resistance',
      'fire_resistance',
      'water_resistance',
      'air_resistance',
    ],
    terminal: false,
  },
  new_item_damages: { params: ['from', 'to', 'damage_type', 'element'], terminal: false },
  new_effect: {
    params: [
      'kind',
      'element',
      'value',
      'value_max',
      'area_shape',
      'area_size',
      'target_filter',
      'chance_bp',
      'turns',
      'stat',
    ],
    terminal: false,
  },
  new_spell_level: {
    params: [
      'ap_cost',
      'range_min',
      'range_max',
      'modifiable_range',
      'line_of_sight',
      'line_launch',
      'free_cell',
      'casts_per_turn',
      'casts_per_target',
      'cooldown_turns',
      'crit_1_in',
      'effects',
      'crit_effects',
    ],
    terminal: false,
  },
  new_mob_loot_entry: { params: ['item_type', 'chance_bp', 'min_qty', 'max_qty'], terminal: false },
  new_mob_spell: { params: ['name', 'levels'], terminal: false },
  new_mob_row: { params: ['mob_type', 'weight_bp', 'biomes'], terminal: false },
  new_resource_row: { params: ['item_type', 'job', 'tier', 'protector', 'rare_item_type', 'biomes'], terminal: false },
  new_room_mob: { params: ['mob_type', 'level_scalar'], terminal: false },
  new_dungeon_room: { params: ['mobs'], terminal: false },
}
