// SPDX-License-Identifier: LicenseRef-AresRPG-Source-Available
// © 2026 Sceat — All rights reserved. See LICENSE.
// GENERATED by scripts/generate_seed_doors.mjs from Move String key structs — DO NOT EDIT.

export const SEED_STRING_KEYS = Object.freeze({
  AirdropKey: Object.freeze({ module: 'distribution', name: 'AirdropKey' }),
  GiftcardKey: Object.freeze({ module: 'distribution', name: 'GiftcardKey' }),
  MasteryOfferKey: Object.freeze({ module: 'mastery', name: 'MasteryOfferKey' }),
  WorldKey: Object.freeze({ module: 'world', name: 'WorldKey' }),
  CheckpointKey: Object.freeze({ module: 'world', name: 'CheckpointKey' }),
  ItemKey: Object.freeze({ module: 'item_rows', name: 'ItemKey' }),
  MobKey: Object.freeze({ module: 'mob_rows', name: 'MobKey' }),
  SpellKey: Object.freeze({ module: 'spell_rows', name: 'SpellKey' }),
  RecipeKey: Object.freeze({ module: 'recipe_rows', name: 'RecipeKey' }),
  WorldContentKey: Object.freeze({ module: 'world_content', name: 'WorldContentKey' }),
  DungeonContentKey: Object.freeze({ module: 'dungeon_content', name: 'DungeonContentKey' }),
})
