// SPDX-License-Identifier: LicenseRef-AresRPG-Source-Available
// © 2026 Sceat — All rights reserved. See LICENSE.
// GENERATED by scripts/generate_doors.mjs from the living content doors and their Move value constructors — DO NOT EDIT.
// One builder per seeding door: door(tx, ctx, args) composes the move call onto the given
// Transaction and returns its Move result for further composition.
// `ctx` is the SDK's bound context ({ pins, obj, pin, receiving, pure }) — every input is
// emitted PRE-RESOLVED (objectRef / sharedObjectRef / offline system helpers), so building the
// transaction costs ZERO RPC roundtrips. Doors marked terminal take &Random: THE TERMINAL LAW —
// such a call must be the LAST command of its transaction (an inspectable roll is a free re-roll).
/* eslint-disable max-lines -- generated projection: one builder per door, size follows the Move contract */

import type { Transaction, TransactionObjectArgument } from '@mysten/sui/transactions'

import type { DoorCtx, Resolvable } from './client.ts'

/**
 * `world::create`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg content — &WorldContent
 */
export const create_world = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; content: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::world::create`,
    arguments: [ctx.obj(tx, args.cap, false), ctx.obj(tx, args.root, true), ctx.obj(tx, args.content, false)],
  })

/**
 * `shop::new_sale`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg template — &ItemTemplate
 * @arg price — u64
 * @arg supply — u64
 * @arg infinite — bool
 * @arg enabled — bool
 */
export const new_sale = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    cap: Resolvable
    root: Resolvable
    template: Resolvable
    price: bigint | number | string
    supply: bigint | number | string
    infinite: boolean
    enabled: boolean
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::shop::new_sale`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.obj(tx, args.template, false),
      ctx.pure.u64(tx, args.price),
      ctx.pure.u64(tx, args.supply),
      ctx.pure.bool(tx, args.infinite),
      ctx.pure.bool(tx, args.enabled),
    ],
  })

/**
 * `shop::set_sale`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg sale — &mut Sale
 * @arg price — u64
 * @arg enabled — bool
 */
export const set_sale = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; sale: Resolvable; price: bigint | number | string; enabled: boolean }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::shop::set_sale`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.obj(tx, args.sale, true),
      ctx.pure.u64(tx, args.price),
      ctx.pure.bool(tx, args.enabled),
    ],
  })

/**
 * `shop::new_airdrop`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg drop_id — String
 * @arg template — &ItemTemplate
 * @arg amount_each — u32
 * @arg whitelist — vector<address>
 */
export const new_airdrop = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    cap: Resolvable
    root: Resolvable
    drop_id: string
    template: Resolvable
    amount_each: number
    whitelist: readonly string[]
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::shop::new_airdrop`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.pure.string(tx, args.drop_id),
      ctx.obj(tx, args.template, false),
      ctx.pure.u32(tx, args.amount_each),
      ctx.pure.vector(tx, 'address', args.whitelist),
    ],
  })

/**
 * `shop::new_giftcard`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg card_id — String
 * @arg template — &ItemTemplate
 * @arg amount — u32
 */
export const new_giftcard = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; card_id: string; template: Resolvable; amount: number }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::shop::new_giftcard`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.pure.string(tx, args.card_id),
      ctx.obj(tx, args.template, false),
      ctx.pure.u32(tx, args.amount),
    ],
  })

/**
 * `loot_box::add_loot_reward`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg box_template — &ItemTemplate
 * @arg reward_template — &ItemTemplate
 * @arg weight — u64
 * @arg amount — u32
 */
export const add_loot_reward = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    cap: Resolvable
    root: Resolvable
    box_template: Resolvable
    reward_template: Resolvable
    weight: bigint | number | string
    amount: number
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::loot_box::add_loot_reward`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.pin(tx, 'loot_registry', true),
      ctx.obj(tx, args.box_template, false),
      ctx.obj(tx, args.reward_template, false),
      ctx.pure.u64(tx, args.weight),
      ctx.pure.u32(tx, args.amount),
    ],
  })

/**
 * `loot_box::clear_loot_table`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg box_template — &ItemTemplate
 */
export const clear_loot_table = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; box_template: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.package}::loot_box::clear_loot_table`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.pin(tx, 'loot_registry', true),
      ctx.obj(tx, args.box_template, false),
    ],
  })

/**
 * `world_content::create`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg name — String
 * @arg entry_level — u16
 */
export const create = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; name: string; entry_level: number }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::world_content::create`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.pure.string(tx, args.name),
      ctx.pure.u16(tx, args.entry_level),
    ],
  })

/**
 * `world_content::share`
 * @arg wc — WorldContent
 */
export const share = (tx: Transaction, ctx: DoorCtx, args: { wc: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::world_content::share`,
    arguments: [ctx.obj(tx, args.wc, true)],
  })

/**
 * `world_content::set_mobs`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg wc — &mut WorldContent
 * @arg rows — vector<MobRow>
 */
export const set_mobs = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; wc: Resolvable; rows: readonly TransactionObjectArgument[] }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::world_content::set_mobs`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.obj(tx, args.wc, true),
      tx.makeMoveVec({ type: `${ctx.math_type_package}::world_map::MobRow`, elements: [...args.rows] }),
    ],
  })

/**
 * `world_content::set_entry_level`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg wc — &mut WorldContent
 * @arg entry_level — u16
 */
export const set_entry_level = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; wc: Resolvable; entry_level: number }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::world_content::set_entry_level`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.obj(tx, args.wc, true),
      ctx.pure.u16(tx, args.entry_level),
    ],
  })

/**
 * `world_content::set_biome_window`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg wc — &mut WorldContent
 * @arg zone_x0 — u32
 * @arg zone_z0 — u32
 * @arg side — u16
 */
export const set_biome_window = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; wc: Resolvable; zone_x0: number; zone_z0: number; side: number }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::world_content::set_biome_window`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.obj(tx, args.wc, true),
      ctx.pure.u32(tx, args.zone_x0),
      ctx.pure.u32(tx, args.zone_z0),
      ctx.pure.u16(tx, args.side),
    ],
  })

/**
 * `world_content::append_biome_cells`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg wc — &mut WorldContent
 * @arg cells — vector<u8>
 */
export const append_biome_cells = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; wc: Resolvable; cells: readonly number[] }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::world_content::append_biome_cells`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.obj(tx, args.wc, true),
      ctx.pure.vector(tx, 'u8', args.cells),
    ],
  })

/**
 * `world_content::clear_biome_map`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg wc — &mut WorldContent
 */
export const clear_biome_map = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; wc: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::world_content::clear_biome_map`,
    arguments: [ctx.obj(tx, args.cap, false), ctx.obj(tx, args.root, true), ctx.obj(tx, args.wc, true)],
  })

/**
 * `world_content::set_resources`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg wc — &mut WorldContent
 * @arg rows — vector<ResourceRow>
 */
export const set_resources = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; wc: Resolvable; rows: readonly TransactionObjectArgument[] }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::world_content::set_resources`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.obj(tx, args.wc, true),
      tx.makeMoveVec({ type: `${ctx.math_type_package}::world_map::ResourceRow`, elements: [...args.rows] }),
    ],
  })

/**
 * `world_content::set_dungeon_key`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg wc — &mut WorldContent
 * @arg item_type — String
 */
export const set_dungeon_key = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; wc: Resolvable; item_type: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::world_content::set_dungeon_key`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.obj(tx, args.wc, true),
      ctx.pure.string(tx, args.item_type),
    ],
  })

/**
 * `world_content::set_dungeon_rooms`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg wc — &mut WorldContent
 * @arg rooms — vector<DungeonRoom>
 */
export const set_dungeon_rooms = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; wc: Resolvable; rooms: readonly TransactionObjectArgument[] }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::world_content::set_dungeon_rooms`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.obj(tx, args.wc, true),
      tx.makeMoveVec({ type: `${ctx.math_type_package}::world_map::DungeonRoom`, elements: [...args.rooms] }),
    ],
  })

/**
 * `mob_rows::add_mob`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg data — MobData
 */
export const add_mob = (tx: Transaction, ctx: DoorCtx, args: { cap: Resolvable; root: Resolvable; data: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::mob_rows::add_mob`,
    arguments: [ctx.obj(tx, args.cap, false), ctx.obj(tx, args.root, true), ctx.obj(tx, args.data, true)],
  })

/**
 * `mob_rows::overwrite_mob`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg template — &mut MobTemplate
 * @arg data — MobData
 */
export const overwrite_mob = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; template: Resolvable; data: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::mob_rows::overwrite_mob`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.obj(tx, args.template, true),
      ctx.obj(tx, args.data, true),
    ],
  })

/**
 * `spell_rows::add_spell`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg name — String
 * @arg classe — String
 * @arg unlock_level — u8
 * @arg levels — vector<SpellLevel>
 */
export const add_spell = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    cap: Resolvable
    root: Resolvable
    name: string
    classe: string
    unlock_level: number
    levels: readonly TransactionObjectArgument[]
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::spell_rows::add_spell`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.pure.string(tx, args.name),
      ctx.pure.string(tx, args.classe),
      ctx.pure.u8(tx, args.unlock_level),
      tx.makeMoveVec({ type: `${ctx.math_type_package}::spell_effect::SpellLevel`, elements: [...args.levels] }),
    ],
  })

/**
 * `spell_rows::overwrite_spell`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg template — &mut SpellTemplate
 * @arg levels — vector<SpellLevel>
 */
export const overwrite_spell = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; template: Resolvable; levels: readonly TransactionObjectArgument[] }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::spell_rows::overwrite_spell`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.obj(tx, args.template, true),
      tx.makeMoveVec({ type: `${ctx.math_type_package}::spell_effect::SpellLevel`, elements: [...args.levels] }),
    ],
  })

/**
 * `item_rows::add_item`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg name — String
 * @arg item_type — String
 * @arg category — String
 * @arg level — u8
 * @arg pet_foods — vector<String>
 */
export const add_item = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    cap: Resolvable
    root: Resolvable
    name: string
    item_type: string
    category: string
    level: number
    pet_foods: readonly string[]
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::item_rows::add_item`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.pure.string(tx, args.name),
      ctx.pure.string(tx, args.item_type),
      ctx.pure.string(tx, args.category),
      ctx.pure.u8(tx, args.level),
      ctx.pure.vector(tx, 'string', args.pet_foods),
    ],
  })

/**
 * `item_rows::share_item`
 * @arg template — ItemTemplate
 */
export const share_item = (tx: Transaction, ctx: DoorCtx, args: { template: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::item_rows::share_item`,
    arguments: [ctx.obj(tx, args.template, true)],
  })

/**
 * `item_rows::overwrite_item`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg template — &mut ItemTemplate
 * @arg name — String
 * @arg level — u8
 * @arg pet_foods — vector<String>
 */
export const overwrite_item = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    cap: Resolvable
    root: Resolvable
    template: Resolvable
    name: string
    level: number
    pet_foods: readonly string[]
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::item_rows::overwrite_item`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.obj(tx, args.template, true),
      ctx.pure.string(tx, args.name),
      ctx.pure.u8(tx, args.level),
      ctx.pure.vector(tx, 'string', args.pet_foods),
    ],
  })

/**
 * `item_rows::set_stats`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg template — &mut ItemTemplate
 * @arg min — ItemStatistics
 * @arg max — ItemStatistics
 */
export const set_stats = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; template: Resolvable; min: Resolvable; max: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::item_rows::set_stats`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.obj(tx, args.template, true),
      ctx.obj(tx, args.min, true),
      ctx.obj(tx, args.max, true),
    ],
  })

/**
 * `item_rows::clear_stats`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg template — &mut ItemTemplate
 */
export const clear_stats = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; template: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::item_rows::clear_stats`,
    arguments: [ctx.obj(tx, args.cap, false), ctx.obj(tx, args.root, true), ctx.obj(tx, args.template, true)],
  })

/**
 * `item_rows::set_damages`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg template — &mut ItemTemplate
 * @arg lines — vector<ItemDamages>
 */
export const set_damages = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; template: Resolvable; lines: readonly TransactionObjectArgument[] }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::item_rows::set_damages`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.obj(tx, args.template, true),
      tx.makeMoveVec({ type: `${ctx.math_type_package}::item_damages::ItemDamages`, elements: [...args.lines] }),
    ],
  })

/**
 * `item_rows::clear_damages`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg template — &mut ItemTemplate
 */
export const clear_damages = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; template: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::item_rows::clear_damages`,
    arguments: [ctx.obj(tx, args.cap, false), ctx.obj(tx, args.root, true), ctx.obj(tx, args.template, true)],
  })

/**
 * `item_rows::set_effect`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg template — &mut ItemTemplate
 * @arg effect — Effect
 */
export const set_effect = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; template: Resolvable; effect: TransactionObjectArgument }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::item_rows::set_effect`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.obj(tx, args.template, true),
      args.effect,
    ],
  })

/**
 * `item_rows::clear_effect`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg template — &mut ItemTemplate
 */
export const clear_effect = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; template: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::item_rows::clear_effect`,
    arguments: [ctx.obj(tx, args.cap, false), ctx.obj(tx, args.root, true), ctx.obj(tx, args.template, true)],
  })

/**
 * `recipe_rows::add_recipe`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg output_type — String
 * @arg output_template — ID
 * @arg input_templates — vector<ID>
 * @arg input_quantities — vector<u64>
 * @arg job — String
 */
export const add_recipe = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    cap: Resolvable
    root: Resolvable
    output_type: string
    output_template: string
    input_templates: readonly string[]
    input_quantities: readonly (bigint | number | string)[]
    job: string
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::recipe_rows::add_recipe`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.pure.string(tx, args.output_type),
      ctx.pure.id(tx, args.output_template),
      ctx.pure.vector(tx, 'id', args.input_templates),
      ctx.pure.vector(tx, 'u64', args.input_quantities),
      ctx.pure.string(tx, args.job),
    ],
  })

/**
 * `recipe_rows::overwrite_recipe`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg recipe — &mut Recipe
 * @arg input_templates — vector<ID>
 * @arg input_quantities — vector<u64>
 * @arg job — String
 */
export const overwrite_recipe = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    cap: Resolvable
    root: Resolvable
    recipe: Resolvable
    input_templates: readonly string[]
    input_quantities: readonly (bigint | number | string)[]
    job: string
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::recipe_rows::overwrite_recipe`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.obj(tx, args.recipe, true),
      ctx.pure.vector(tx, 'id', args.input_templates),
      ctx.pure.vector(tx, 'u64', args.input_quantities),
      ctx.pure.string(tx, args.job),
    ],
  })

/**
 * `recipe_rows::retire_recipe`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg recipe — &mut Recipe
 */
export const retire_recipe = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; recipe: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::recipe_rows::retire_recipe`,
    arguments: [ctx.obj(tx, args.cap, false), ctx.obj(tx, args.root, true), ctx.obj(tx, args.recipe, true)],
  })

/**
 * `board_catalog::create_catalog`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 */
export const create_catalog = (tx: Transaction, ctx: DoorCtx, args: { cap: Resolvable; root: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::board_catalog::create_catalog`,
    arguments: [ctx.obj(tx, args.cap, false), ctx.obj(tx, args.root, true)],
  })

/**
 * `board_catalog::add_board`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg catalog — &mut BoardCatalog
 * @arg board — GridSpec
 */
export const add_board = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; catalog: Resolvable; board: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::board_catalog::add_board`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.obj(tx, args.catalog, true),
      ctx.obj(tx, args.board, true),
    ],
  })

/**
 * `board_catalog::replace_board`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg catalog — &mut BoardCatalog
 * @arg index — u64
 * @arg board — GridSpec
 */
export const replace_board = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; catalog: Resolvable; index: bigint | number | string; board: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::board_catalog::replace_board`,
    arguments: [
      ctx.obj(tx, args.cap, false),
      ctx.obj(tx, args.root, true),
      ctx.obj(tx, args.catalog, true),
      ctx.pure.u64(tx, args.index),
      ctx.obj(tx, args.board, true),
    ],
  })

/**
 * `board_catalog::remove_last_board`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 * @arg catalog — &mut BoardCatalog
 */
export const remove_last_board = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { cap: Resolvable; root: Resolvable; catalog: Resolvable }
) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::board_catalog::remove_last_board`,
    arguments: [ctx.obj(tx, args.cap, false), ctx.obj(tx, args.root, true), ctx.obj(tx, args.catalog, true)],
  })

/**
 * `registry::freeze_forever`
 * @arg cap — &AdminCap
 * @arg root — &mut Registry
 */
export const freeze_forever = (tx: Transaction, ctx: DoorCtx, args: { cap: Resolvable; root: Resolvable }) =>
  tx.moveCall({
    target: `${ctx.pins.seed_package}::registry::freeze_forever`,
    arguments: [ctx.obj(tx, args.cap, false), ctx.obj(tx, args.root, true)],
  })

/**
 * `item_stats::new`
 * @arg vitality — u16
 * @arg wisdom — u16
 * @arg strength — u16
 * @arg intelligence — u16
 * @arg chance — u16
 * @arg agility — u16
 * @arg range — u16
 * @arg movement — u16
 * @arg action — u16
 * @arg critical — u16
 * @arg raw_damage — u16
 * @arg earth_resistance — u16
 * @arg fire_resistance — u16
 * @arg water_resistance — u16
 * @arg air_resistance — u16
 */
export const new_item_stats = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    vitality: number
    wisdom: number
    strength: number
    intelligence: number
    chance: number
    agility: number
    range: number
    movement: number
    action: number
    critical: number
    raw_damage: number
    earth_resistance: number
    fire_resistance: number
    water_resistance: number
    air_resistance: number
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.math_package}::item_stats::new`,
    arguments: [
      ctx.pure.u16(tx, args.vitality),
      ctx.pure.u16(tx, args.wisdom),
      ctx.pure.u16(tx, args.strength),
      ctx.pure.u16(tx, args.intelligence),
      ctx.pure.u16(tx, args.chance),
      ctx.pure.u16(tx, args.agility),
      ctx.pure.u16(tx, args.range),
      ctx.pure.u16(tx, args.movement),
      ctx.pure.u16(tx, args.action),
      ctx.pure.u16(tx, args.critical),
      ctx.pure.u16(tx, args.raw_damage),
      ctx.pure.u16(tx, args.earth_resistance),
      ctx.pure.u16(tx, args.fire_resistance),
      ctx.pure.u16(tx, args.water_resistance),
      ctx.pure.u16(tx, args.air_resistance),
    ],
  })

/**
 * `consumable_effect::heal`
 * @arg amount — u32
 */
export const consumable_heal = (tx: Transaction, ctx: DoorCtx, args: { amount: number }) =>
  tx.moveCall({
    target: `${ctx.pins.math_package}::consumable_effect::heal`,
    arguments: [ctx.pure.u32(tx, args.amount)],
  })

/**
 * `consumable_effect::reset_stats`
 * (no caller arguments)
 */
export const consumable_reset_stats = (tx: Transaction, ctx: DoorCtx, args: Record<string, never>) =>
  tx.moveCall({
    target: `${ctx.pins.math_package}::consumable_effect::reset_stats`,
    arguments: [],
  })

/**
 * `consumable_effect::reset_spells`
 * (no caller arguments)
 */
export const consumable_reset_spells = (tx: Transaction, ctx: DoorCtx, args: Record<string, never>) =>
  tx.moveCall({
    target: `${ctx.pins.math_package}::consumable_effect::reset_spells`,
    arguments: [],
  })

/**
 * `consumable_effect::recall`
 * (no caller arguments)
 */
export const consumable_recall = (tx: Transaction, ctx: DoorCtx, args: Record<string, never>) =>
  tx.moveCall({
    target: `${ctx.pins.math_package}::consumable_effect::recall`,
    arguments: [],
  })

/**
 * `consumable_effect::loot_box`
 * (no caller arguments)
 */
export const consumable_loot_box = (tx: Transaction, ctx: DoorCtx, args: Record<string, never>) =>
  tx.moveCall({
    target: `${ctx.pins.math_package}::consumable_effect::loot_box`,
    arguments: [],
  })

/**
 * `item_damages::new`
 * @arg from — u16
 * @arg to — u16
 * @arg damage_type — String
 * @arg element — String
 */
export const new_item_damages = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { from: number; to: number; damage_type: string; element: string }
) =>
  tx.moveCall({
    target: `${ctx.pins.math_package}::item_damages::new`,
    arguments: [
      ctx.pure.u16(tx, args.from),
      ctx.pure.u16(tx, args.to),
      ctx.pure.string(tx, args.damage_type),
      ctx.pure.string(tx, args.element),
    ],
  })

/**
 * `spell_effect::new_effect`
 * @arg kind — u8
 * @arg element — String
 * @arg value — u32
 * @arg value_max — u32
 * @arg area_shape — u8
 * @arg area_size — u8
 * @arg target_filter — u8
 * @arg chance_bp — u16
 * @arg turns — u8
 * @arg stat — u8
 */
export const new_effect = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    kind: number
    element: string
    value: number
    value_max: number
    area_shape: number
    area_size: number
    target_filter: number
    chance_bp: number
    turns: number
    stat: number
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.math_package}::spell_effect::new_effect`,
    arguments: [
      ctx.pure.u8(tx, args.kind),
      ctx.pure.string(tx, args.element),
      ctx.pure.u32(tx, args.value),
      ctx.pure.u32(tx, args.value_max),
      ctx.pure.u8(tx, args.area_shape),
      ctx.pure.u8(tx, args.area_size),
      ctx.pure.u8(tx, args.target_filter),
      ctx.pure.u16(tx, args.chance_bp),
      ctx.pure.u8(tx, args.turns),
      ctx.pure.u8(tx, args.stat),
    ],
  })

/**
 * `spell_effect::new_spell_level`
 * @arg ap_cost — u8
 * @arg range_min — u8
 * @arg range_max — u8
 * @arg modifiable_range — bool
 * @arg line_of_sight — bool
 * @arg line_launch — bool
 * @arg free_cell — bool
 * @arg casts_per_turn — u8
 * @arg casts_per_target — u8
 * @arg cooldown_turns — u8
 * @arg crit_1_in — u16
 * @arg effects — vector<Effect>
 * @arg crit_effects — vector<Effect>
 */
export const new_spell_level = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    ap_cost: number
    range_min: number
    range_max: number
    modifiable_range: boolean
    line_of_sight: boolean
    line_launch: boolean
    free_cell: boolean
    casts_per_turn: number
    casts_per_target: number
    cooldown_turns: number
    crit_1_in: number
    effects: readonly TransactionObjectArgument[]
    crit_effects: readonly TransactionObjectArgument[]
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.math_package}::spell_effect::new_spell_level`,
    arguments: [
      ctx.pure.u8(tx, args.ap_cost),
      ctx.pure.u8(tx, args.range_min),
      ctx.pure.u8(tx, args.range_max),
      ctx.pure.bool(tx, args.modifiable_range),
      ctx.pure.bool(tx, args.line_of_sight),
      ctx.pure.bool(tx, args.line_launch),
      ctx.pure.bool(tx, args.free_cell),
      ctx.pure.u8(tx, args.casts_per_turn),
      ctx.pure.u8(tx, args.casts_per_target),
      ctx.pure.u8(tx, args.cooldown_turns),
      ctx.pure.u16(tx, args.crit_1_in),
      tx.makeMoveVec({ type: `${ctx.math_type_package}::spell_effect::Effect`, elements: [...args.effects] }),
      tx.makeMoveVec({ type: `${ctx.math_type_package}::spell_effect::Effect`, elements: [...args.crit_effects] }),
    ],
  })

/**
 * `mob_data::new_mob_data`
 * @arg name — String
 * @arg mob_type — String
 * @arg element — String
 * @arg level_min — u8
 * @arg level_max — u8
 * @arg hp — u64
 * @arg ap — u8
 * @arg mp — u8
 * @arg agility — u16
 * @arg wisdom — u16
 * @arg earth_resistance — u16
 * @arg fire_resistance — u16
 * @arg water_resistance — u16
 * @arg air_resistance — u16
 * @arg spells — vector<MobSpell>
 * @arg loot — vector<LootEntry>
 * @arg xp — u64
 */
export const new_mob_data = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    name: string
    mob_type: string
    element: string
    level_min: number
    level_max: number
    hp: bigint | number | string
    ap: number
    mp: number
    agility: number
    wisdom: number
    earth_resistance: number
    fire_resistance: number
    water_resistance: number
    air_resistance: number
    spells: readonly TransactionObjectArgument[]
    loot: readonly TransactionObjectArgument[]
    xp: bigint | number | string
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.math_package}::mob_data::new_mob_data`,
    arguments: [
      ctx.pure.string(tx, args.name),
      ctx.pure.string(tx, args.mob_type),
      ctx.pure.string(tx, args.element),
      ctx.pure.u8(tx, args.level_min),
      ctx.pure.u8(tx, args.level_max),
      ctx.pure.u64(tx, args.hp),
      ctx.pure.u8(tx, args.ap),
      ctx.pure.u8(tx, args.mp),
      ctx.pure.u16(tx, args.agility),
      ctx.pure.u16(tx, args.wisdom),
      ctx.pure.u16(tx, args.earth_resistance),
      ctx.pure.u16(tx, args.fire_resistance),
      ctx.pure.u16(tx, args.water_resistance),
      ctx.pure.u16(tx, args.air_resistance),
      tx.makeMoveVec({ type: `${ctx.math_type_package}::mob_data::MobSpell`, elements: [...args.spells] }),
      tx.makeMoveVec({ type: `${ctx.math_type_package}::mob_data::LootEntry`, elements: [...args.loot] }),
      ctx.pure.u64(tx, args.xp),
    ],
  })

/**
 * `mob_data::new_loot_entry`
 * @arg item_type — String
 * @arg chance_bp — u16
 * @arg min_qty — u8
 * @arg max_qty — u8
 */
export const new_mob_loot_entry = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { item_type: string; chance_bp: number; min_qty: number; max_qty: number }
) =>
  tx.moveCall({
    target: `${ctx.pins.math_package}::mob_data::new_loot_entry`,
    arguments: [
      ctx.pure.string(tx, args.item_type),
      ctx.pure.u16(tx, args.chance_bp),
      ctx.pure.u8(tx, args.min_qty),
      ctx.pure.u8(tx, args.max_qty),
    ],
  })

/**
 * `mob_data::new_mob_spell`
 * @arg name — String
 * @arg level — SpellLevel
 */
export const new_mob_spell = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { name: string; level: TransactionObjectArgument }
) =>
  tx.moveCall({
    target: `${ctx.pins.math_package}::mob_data::new_mob_spell`,
    arguments: [ctx.pure.string(tx, args.name), args.level],
  })

/**
 * `combat_grid::grid_spec`
 * @arg width — u64
 * @arg height — u64
 * @arg shape_mask — vector<u64>
 * @arg obstacles — vector<u64>
 * @arg holes — vector<u64>
 * @arg start_cells_a — vector<u64>
 * @arg start_cells_b — vector<u64>
 */
export const new_grid_spec = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    width: bigint | number | string
    height: bigint | number | string
    shape_mask: readonly (bigint | number | string)[]
    obstacles: readonly (bigint | number | string)[]
    holes: readonly (bigint | number | string)[]
    start_cells_a: readonly (bigint | number | string)[]
    start_cells_b: readonly (bigint | number | string)[]
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.math_package}::combat_grid::grid_spec`,
    arguments: [
      ctx.pure.u64(tx, args.width),
      ctx.pure.u64(tx, args.height),
      ctx.pure.vector(tx, 'u64', args.shape_mask),
      ctx.pure.vector(tx, 'u64', args.obstacles),
      ctx.pure.vector(tx, 'u64', args.holes),
      ctx.pure.vector(tx, 'u64', args.start_cells_a),
      ctx.pure.vector(tx, 'u64', args.start_cells_b),
    ],
  })

/**
 * `world_map::new_mob_row`
 * @arg mob_type — String
 * @arg weight_bp — u16
 * @arg biomes — vector<u8>
 */
export const new_mob_row = (
  tx: Transaction,
  ctx: DoorCtx,
  args: { mob_type: string; weight_bp: number; biomes: readonly number[] }
) =>
  tx.moveCall({
    target: `${ctx.pins.math_package}::world_map::new_mob_row`,
    arguments: [
      ctx.pure.string(tx, args.mob_type),
      ctx.pure.u16(tx, args.weight_bp),
      ctx.pure.vector(tx, 'u8', args.biomes),
    ],
  })

/**
 * `world_map::new_resource_row`
 * @arg item_type — String
 * @arg job — String
 * @arg tier — u8
 * @arg protector — String
 * @arg rare_item_type — String
 * @arg biomes — vector<u8>
 */
export const new_resource_row = (
  tx: Transaction,
  ctx: DoorCtx,
  args: {
    item_type: string
    job: string
    tier: number
    protector: string
    rare_item_type: string
    biomes: readonly number[]
  }
) =>
  tx.moveCall({
    target: `${ctx.pins.math_package}::world_map::new_resource_row`,
    arguments: [
      ctx.pure.string(tx, args.item_type),
      ctx.pure.string(tx, args.job),
      ctx.pure.u8(tx, args.tier),
      ctx.pure.string(tx, args.protector),
      ctx.pure.string(tx, args.rare_item_type),
      ctx.pure.vector(tx, 'u8', args.biomes),
    ],
  })

/**
 * `world_map::new_room_mob`
 * @arg mob_type — String
 */
export const new_room_mob = (tx: Transaction, ctx: DoorCtx, args: { mob_type: string }) =>
  tx.moveCall({
    target: `${ctx.pins.math_package}::world_map::new_room_mob`,
    arguments: [ctx.pure.string(tx, args.mob_type)],
  })

/**
 * `world_map::new_dungeon_room`
 * @arg mobs — vector<RoomMob>
 */
export const new_dungeon_room = (tx: Transaction, ctx: DoorCtx, args: { mobs: readonly TransactionObjectArgument[] }) =>
  tx.moveCall({
    target: `${ctx.pins.math_package}::world_map::new_dungeon_room`,
    arguments: [tx.makeMoveVec({ type: `${ctx.math_type_package}::world_map::RoomMob`, elements: [...args.mobs] })],
  })

/** Every door, by name — { params: caller-facing names, terminal: carries &Random }. */
export const DOORS = {
  create_world: { params: ['cap', 'root', 'content'], terminal: false },
  new_sale: { params: ['cap', 'root', 'template', 'price', 'supply', 'infinite', 'enabled'], terminal: false },
  set_sale: { params: ['cap', 'root', 'sale', 'price', 'enabled'], terminal: false },
  new_airdrop: { params: ['cap', 'root', 'drop_id', 'template', 'amount_each', 'whitelist'], terminal: false },
  new_giftcard: { params: ['cap', 'root', 'card_id', 'template', 'amount'], terminal: false },
  add_loot_reward: { params: ['cap', 'root', 'box_template', 'reward_template', 'weight', 'amount'], terminal: false },
  clear_loot_table: { params: ['cap', 'root', 'box_template'], terminal: false },
  create: { params: ['cap', 'root', 'name', 'entry_level'], terminal: false },
  share: { params: ['wc'], terminal: false },
  set_mobs: { params: ['cap', 'root', 'wc', 'rows'], terminal: false },
  set_entry_level: { params: ['cap', 'root', 'wc', 'entry_level'], terminal: false },
  set_biome_window: { params: ['cap', 'root', 'wc', 'zone_x0', 'zone_z0', 'side'], terminal: false },
  append_biome_cells: { params: ['cap', 'root', 'wc', 'cells'], terminal: false },
  clear_biome_map: { params: ['cap', 'root', 'wc'], terminal: false },
  set_resources: { params: ['cap', 'root', 'wc', 'rows'], terminal: false },
  set_dungeon_key: { params: ['cap', 'root', 'wc', 'item_type'], terminal: false },
  set_dungeon_rooms: { params: ['cap', 'root', 'wc', 'rooms'], terminal: false },
  add_mob: { params: ['cap', 'root', 'data'], terminal: false },
  overwrite_mob: { params: ['cap', 'root', 'template', 'data'], terminal: false },
  add_spell: { params: ['cap', 'root', 'name', 'classe', 'unlock_level', 'levels'], terminal: false },
  overwrite_spell: { params: ['cap', 'root', 'template', 'levels'], terminal: false },
  add_item: { params: ['cap', 'root', 'name', 'item_type', 'category', 'level', 'pet_foods'], terminal: false },
  share_item: { params: ['template'], terminal: false },
  overwrite_item: { params: ['cap', 'root', 'template', 'name', 'level', 'pet_foods'], terminal: false },
  set_stats: { params: ['cap', 'root', 'template', 'min', 'max'], terminal: false },
  clear_stats: { params: ['cap', 'root', 'template'], terminal: false },
  set_damages: { params: ['cap', 'root', 'template', 'lines'], terminal: false },
  clear_damages: { params: ['cap', 'root', 'template'], terminal: false },
  set_effect: { params: ['cap', 'root', 'template', 'effect'], terminal: false },
  clear_effect: { params: ['cap', 'root', 'template'], terminal: false },
  add_recipe: {
    params: ['cap', 'root', 'output_type', 'output_template', 'input_templates', 'input_quantities', 'job'],
    terminal: false,
  },
  overwrite_recipe: {
    params: ['cap', 'root', 'recipe', 'input_templates', 'input_quantities', 'job'],
    terminal: false,
  },
  retire_recipe: { params: ['cap', 'root', 'recipe'], terminal: false },
  create_catalog: { params: ['cap', 'root'], terminal: false },
  add_board: { params: ['cap', 'root', 'catalog', 'board'], terminal: false },
  replace_board: { params: ['cap', 'root', 'catalog', 'index', 'board'], terminal: false },
  remove_last_board: { params: ['cap', 'root', 'catalog'], terminal: false },
  freeze_forever: { params: ['cap', 'root'], terminal: false },
  new_item_stats: {
    params: [
      'vitality',
      'wisdom',
      'strength',
      'intelligence',
      'chance',
      'agility',
      'range',
      'movement',
      'action',
      'critical',
      'raw_damage',
      'earth_resistance',
      'fire_resistance',
      'water_resistance',
      'air_resistance',
    ],
    terminal: false,
  },
  consumable_heal: { params: ['amount'], terminal: false },
  consumable_reset_stats: { params: [], terminal: false },
  consumable_reset_spells: { params: [], terminal: false },
  consumable_recall: { params: [], terminal: false },
  consumable_loot_box: { params: [], terminal: false },
  new_item_damages: { params: ['from', 'to', 'damage_type', 'element'], terminal: false },
  new_effect: {
    params: [
      'kind',
      'element',
      'value',
      'value_max',
      'area_shape',
      'area_size',
      'target_filter',
      'chance_bp',
      'turns',
      'stat',
    ],
    terminal: false,
  },
  new_spell_level: {
    params: [
      'ap_cost',
      'range_min',
      'range_max',
      'modifiable_range',
      'line_of_sight',
      'line_launch',
      'free_cell',
      'casts_per_turn',
      'casts_per_target',
      'cooldown_turns',
      'crit_1_in',
      'effects',
      'crit_effects',
    ],
    terminal: false,
  },
  new_mob_data: {
    params: [
      'name',
      'mob_type',
      'element',
      'level_min',
      'level_max',
      'hp',
      'ap',
      'mp',
      'agility',
      'wisdom',
      'earth_resistance',
      'fire_resistance',
      'water_resistance',
      'air_resistance',
      'spells',
      'loot',
      'xp',
    ],
    terminal: false,
  },
  new_mob_loot_entry: { params: ['item_type', 'chance_bp', 'min_qty', 'max_qty'], terminal: false },
  new_mob_spell: { params: ['name', 'level'], terminal: false },
  new_grid_spec: {
    params: ['width', 'height', 'shape_mask', 'obstacles', 'holes', 'start_cells_a', 'start_cells_b'],
    terminal: false,
  },
  new_mob_row: { params: ['mob_type', 'weight_bp', 'biomes'], terminal: false },
  new_resource_row: { params: ['item_type', 'job', 'tier', 'protector', 'rare_item_type', 'biomes'], terminal: false },
  new_room_mob: { params: ['mob_type'], terminal: false },
  new_dungeon_room: { params: ['mobs'], terminal: false },
}
