// SPDX-License-Identifier: LicenseRef-AresRPG-Source-Available
// © 2026 Sceat — All rights reserved. See LICENSE.
// §7b IN NODE (M1 / D768: "the presentation BEAT STREAM is a first-class output so §7b conformance runs in
// node"): the core's paced wave, converted to the SAME BeatTraceRow shape the browser probe emits, evaluated by
// the SAME machine twin (test/gold/specs_anchor/pacing_envelopes.ts evaluate_trace) — no browser, no renderer.
// The trace clock is the stream's own contract: beat start = T0 + beat.at (segment-absolute), exactly how the
// serial render queue plays a turn's slots. Deaths are asserted core-natively in scenario_solo.test.js (the
// hold-until-ack law); this file owns the grammar + envelope numbers over a multi-mob wave.
//
// NOTE (right-home): pacing_envelopes.ts still lives in test/gold/specs_anchor/ — imported here relatively.
// Its natural home post-M1 is INSIDE @aresrpg/fight (the machine twin of the core's own output contract),
// with the gold suite importing it FROM the package — flagged in the lane report, not moved unilaterally.
import { existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { describe, test, expect } from 'bun:test'

import { create_fight_store } from './store.js'
import { MOB_TURN_MS } from './present.js'
import { FIGHT_RENDER_TIMINGS, produce_receipt_render_turns } from './fight_render_events.js'

// MISSING-ARTIFACT (#96): test/gold/specs_anchor/pacing_envelopes.ts is generated by the content pipeline
// (private repo) from authored specs and is absent by design in this public repo.
const PACING_ENVELOPES_PATH = fileURLToPath(
  new URL('../../../test/gold/specs_anchor/pacing_envelopes.ts', import.meta.url)
)
const PACING_ENVELOPES_AVAILABLE = existsSync(PACING_ENVELOPES_PATH)
const { evaluate_trace, envelope, JITTER_MS } = PACING_ENVELOPES_AVAILABLE
  ? await import('../../../test/gold/specs_anchor/pacing_envelopes.ts')
  : { evaluate_trace: undefined, envelope: undefined, JITTER_MS: undefined }

const FIGHT = '0xf1647'
const ME = '0xchar_a'
const PEER = '0xchar_b'
const T0 = 1_000_000

const ev = (kind, json) => ({ type: `0xpkg::fight_events::${kind}`, parsedJson: { fight: FIGHT, ...json } })

const participant = (owner, character, cell) => ({
  owner,
  character,
  class: 'warrior',
  team: 0,
  hp: 50,
  max_hp: 50,
  ap: 12,
  mp: 3,
  base_ap: 12,
  base_mp: 3,
  cell,
  ready: true,
  casts_this_turn: 0,
  weapon: null,
})

const two_mob_fight = () => ({
  id: FIGHT,
  status: 1,
  width: 20,
  height: 19,
  participants: [participant('0xa11ce', ME, 21), participant('0xb0b', PEER, 22)],
  group_template: '0xmob_t',
  group_base_ap: 6,
  group_base_mp: 3,
  mobs: [
    { template: '0xmob_t', level: 3, hp: 20, max_hp: 20, cell: 45, ap: 6, mp: 3 },
    { template: '0xmob_t', level: 3, hp: 20, max_hp: 20, cell: 55, ap: 6, mp: 3 },
  ],
  obstacles: [],
  holes: [],
  shape_mask: [],
  start_cells_a: [21, 22],
  start_cells_b: [],
  turn_ptr: 0,
  queue: [],
  turn_deadline_ms: T0 + 30_000,
  placement_deadline_ms: 0,
  world_seed: null,
  spawn_id: null,
  last_action_ms: 0,
})

/** One mob turn: move 4 cells (past the run threshold ⇒ the RUN gait, 4×198) → cast → two victims'
 *  floaters. Raw 2892ms ≤ the 3s slot ⇒ the natural branch: every beat at clip pace, the last beat
 *  absorbing the slack so the slot still spans E10's 3000 exactly. */
const mob_turn = (idx, to_cell) => [
  ev('TurnStarted', { is_mob: true, idx }),
  ev('MobMoved', { idx, to_cell }),
  ev('Cast', { caster_is_mob: true, caster_idx: idx, target_cell: 21 }),
  ev('Hit', { victim_is_mob: false, victim_idx: 0, amount: 6, remaining_hp: 44, caster_is_mob: true, caster_idx: idx }),
  ev('Hit', { victim_is_mob: false, victim_idx: 1, amount: 6, remaining_hp: 44, caster_is_mob: true, caster_idx: idx }),
  ev('TurnEnded', { is_mob: true, idx }),
]

/** The core wave → the browser probe's BeatTraceRow shape, clocked EXACTLY like the serial render queue
 *  (fight_render_queue run_event): each turn opens at its own head (the previous turn's completion, +1ms for
 *  the between-turns promise tick) and every slot fires at head + slot.at. The render contract says the
 *  renderer computes nothing — so the stream's `at` MUST be turn-local for this clock to pace correctly. */
const trace_of = (wave) => {
  const rows = []
  let head = T0
  for (const t of wave.filter((t) => !t.is_local)) {
    for (const b of t.beats)
      rows.push({
        t: head + b.at,
        lane: /** @type {const} */ ('beat'),
        kind: b.kind,
        id: b.payload?.entity_id ?? b.payload?.target_id ?? null,
      })
    head += t.duration + 1 // serial completion + the queue's next-turn tick
  }
  return rows
}

const drive = () => {
  const store = create_fight_store()
  store
    .getState()
    .input(
      { type: 'init', fight_id: FIGHT, ctx: { my_entity_id: ME, address: '0xa11ce', beat_ctx: { grid_width: 20 } } },
      T0
    )
  store.getState().input({ type: 'snapshot', fight: two_mob_fight(), version: 1 }, T0 + 10)
  store
    .getState()
    .input({ type: 'receipt', receipt: { events: [...mob_turn(0, 41), ...mob_turn(1, 51)] }, version: 2 }, T0 + 100)
  return store.getState()
}

describe.skipIf(!PACING_ENVELOPES_AVAILABLE)(
  '§7b — the shipped beat constants obey the envelope table (the canon bridge)',
  () => {
    // The 2026-07-18 emulator verification found the gap this block closes: the envelope table agreed with
    // canon while the SHIPPED constant disagreed, and nothing mechanical tied the two. Each ruled constant
    // must sit inside its own envelope row — retunes move BOTH or red here.
    test('E5: the shipped death hold is the retro-1.29 reference hold (client die-anim block = server hold)', () => {
      const row = envelope('E5')
      expect(FIGHT_RENDER_TIMINGS.death).toBeGreaterThanOrEqual(row.min_ms)
      expect(FIGHT_RENDER_TIMINGS.death).toBeLessThanOrEqual(row.max_ms)
    })

    // E6 — the move cadence is TWO gaits from the vendored reference arrays, switched by path length:
    // paths past the reference fight threshold (3 cells) RUN at the envelope min, shorter paths WALK at the
    // envelope max. A flat cadence that never delivers the promised run gait is exactly the red this locks.
    const path_of = (cells) => Array.from({ length: cells }, (_, i) => ({ x: i + 1, y: 1 }))
    const move_beats = (cells) => {
      const { turns } = produce_receipt_render_turns(
        [
          ev('TurnStarted', { is_mob: false, idx: 0 }),
          ev('Moved', { character: ME, to_cell: cells + 20 /* {x:cells, y:1} on the 20-wide grid */ }),
        ],
        { fight_id: FIGHT, grid_width: 20, move_path: () => path_of(cells) }
      )
      return turns.flatMap((t) => t.events).find((b) => b.kind === 'move')
    }

    test('E6: a fight path past the run threshold plays the RUN gait per cell (the envelope min)', () => {
      expect(move_beats(4).duration).toBe(4 * envelope('E6').min_ms)
    })

    test('E6: a path AT the threshold (3 cells) still WALKS — the reference switch is strictly past 3', () => {
      expect(move_beats(3).duration).toBe(3 * envelope('E6').max_ms)
    })

    test('E6: a short path walks at the reference walk gait per cell (the envelope max)', () => {
      expect(move_beats(2).duration).toBe(2 * envelope('E6').max_ms)
    })

    test('E7: the shipped displacement slide is the reference flat slide (0.25 px/ms ≈ 119ms/cell)', () => {
      const row = envelope('E7')
      expect(FIGHT_RENDER_TIMINGS.displacement_cell).toBeGreaterThanOrEqual(row.min_ms)
      expect(FIGHT_RENDER_TIMINGS.displacement_cell).toBeLessThanOrEqual(row.max_ms)
    })
  }
)

describe.skipIf(!PACING_ENVELOPES_AVAILABLE)(
  '§7b envelope conformance over the core beat stream (node, zero browser)',
  () => {
    test('a two-mob wave: 2 slots × 3s, every measured envelope in range, zero violations', () => {
      const s = drive()
      const remote = s.wave.filter((t) => !t.is_local)
      expect(remote.length).toBe(2)
      for (const t of remote) expect(t.duration).toBe(MOB_TURN_MS)

      const verdict = evaluate_trace(trace_of(s.wave))
      expect(verdict.windows.length).toBe(2)
      for (const w of verdict.windows) expect(w.actor).toBe('mob')
      expect(verdict.order_violations).toEqual([])
      expect(verdict.dead_air_violations).toEqual([]) // E12: no gap > 3000 inside a turn
      expect(verdict.teleport_violations).toEqual([])
      expect(verdict.envelope_violations).toEqual([]) // every measured pair inside its envelope ± jitter

      // E10 — the mob presentation slot: measured twice, both ≈ the tuned 3s slot (compress lands it exactly).
      const slots = verdict.measures.filter((m) => m.key === 'E10')
      expect(slots.length).toBe(2)
      for (const slot of slots) {
        expect(slot.interval_ms).toBeGreaterThanOrEqual(envelope('E10').min_ms - JITTER_MS)
        expect(slot.interval_ms).toBeLessThanOrEqual(envelope('E10').max_ms + JITTER_MS)
      }

      // E8 — the handoff between the two mob turns is seamless (segment-contiguous slots).
      const handoffs = verdict.measures.filter((m) => m.key === 'E8')
      expect(handoffs.length).toBe(1)
      expect(handoffs[0].verdict).toBe('in')

      // E3 — the two victims' floaters of one cast pop serially inside [100, 1000].
      const serial = verdict.measures.filter((m) => m.key === 'E3')
      expect(serial.length).toBe(2) // one pair per mob cast
      for (const m of serial) expect(m.verdict).toBe('in')
    })

    test('the stream is renderer-complete: rows carry {kind, at, duration, payload} and nothing needs computing', () => {
      const s = drive()
      for (const t of s.wave.filter((t) => !t.is_local)) {
        expect(typeof t.seq).toBe('number')
        expect(typeof t.duration).toBe('number')
        for (const b of t.beats) {
          expect(typeof b.kind).toBe('string')
          expect(typeof b.at).toBe('number')
          expect(typeof b.duration).toBe('number')
          expect('payload' in b).toBe(true) // the render contract: consumers bind the payload, decide nothing
        }
        // beats are contiguous inside the slot: each starts exactly where the previous ended.
        const starts = t.beats.map((b) => b.at)
        const ends = t.beats.map((b) => b.at + b.duration)
        for (let i = 1; i < starts.length; i++) expect(starts[i]).toBe(ends[i - 1])
      }
    })
  }
)
