// SPDX-License-Identifier: LicenseRef-AresRPG-Source-Available
// © 2026 Sceat — All rights reserved. See LICENSE.
// api/test/generate_composed_fixture.mjs — captures the SDK's composed-PTB corpus as serialized
// transaction payloads so the sponsor's command-graph test can decode them with api's OWN
// `@mysten/sui` instead of importing live sdk-tree code.
//
// WHY THIS EXISTS: the `tests (api)` CI job installs ONLY `api/` (its own bun.lock). A test that
// imports `packages/sdk/test/_composed_transactions.js` drags the whole sdk source tree into the
// api process, and those modules resolve `@mysten/sui` from sdk/root `node_modules` — absent in
// that job. The root hoist masks it locally; CI does not have one. Captured payloads cross the
// install boundary; live code does not.
//
// WHY toJSON AND NOT BCS KIND BYTES: 44 of the 47 compositions carry unresolved object inputs
// (`tx.object(id)` with no version/digest), so `tx.build({ onlyTransactionKind: true })` refuses
// offline — "No sui client passed to Transaction#build". `toJSON()` is the SDK's canonical
// serialization for exactly that state, and `Transaction.from(json)` is the same decode door.
// Round-trip is lossless for every field the sponsor reads: the only delta is the transient
// `type: 'object'` hint on Input arguments, which `assert_command_graph` never looks at (it
// switches on `$kind`).
//
// WHY BASE64 AND NOT INLINE JSON: the payloads carry the corpus's synthetic placeholder object ids
// (`_onchain_fixtures.js` manufactures them offline from a tag — they name nothing on any chain).
// Inlined as text they read as 358 hardcoded 64-hex ids to `scripts/check-chain-ids.mjs`, whose
// whole point is that a *human* never writes an id into source instead of reading it off /v1.
// Base64 keeps the capture what it is — an opaque generated payload, regenerated by this script,
// never hand-edited — instead of enrolling synthetic ids in that gate's captured-chain-data registry.
//
// REGENERATE (repo root, after `bun install --frozen-lockfile` so the sdk tree resolves):
//   bun api/test/generate_composed_fixture.mjs

import { execFileSync } from 'node:child_process'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { composed_transactions } from '../../packages/sdk/test/_composed_transactions.js'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = join(HERE, '..', '..')
const SOURCE = 'packages/sdk/test/_composed_transactions.js'
const OUT = join(HERE, 'fixtures', 'composed_transactions.json')

/** What the composition is, for a readable failure line — the MoveCall doors it opens. */
const label_of = (transaction) => {
  const calls = transaction
    .getData()
    .commands.filter((command) => command.$kind === 'MoveCall')
    .map((command) => `${command.MoveCall.module}::${command.MoveCall.function}`)
  return [...new Set(calls)].join(' + ') || '(kiosk-composed — no explicit target)'
}

const source_sha = execFileSync('git', ['log', '-1', '--format=%h', '--', SOURCE], {
  cwd: REPO_ROOT,
  encoding: 'utf8',
}).trim()

const corpus = composed_transactions()
const cases = await Promise.all(
  corpus.map(async (transaction, index) => ({
    index,
    label: label_of(transaction),
    // The captured payload, verbatim — the test base64-decodes it and hands it to `Transaction.from`.
    serialized_b64: Buffer.from(await transaction.toJSON(), 'utf8').toString('base64'),
  }))
)

const fixture = {
  provenance: {
    source: SOURCE,
    source_sha,
    captured_on: new Date().toISOString().slice(0, 10),
    format: '@mysten/sui Transaction#toJSON, base64 — decode with Transaction.from(atob(case.serialized_b64))',
    regenerate: 'bun install --frozen-lockfile && bun api/test/generate_composed_fixture.mjs',
  },
  cases,
}

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(OUT, `${JSON.stringify(fixture, null, 2)}\n`)
console.log(`captured ${cases.length} composed transactions from ${SOURCE}@${source_sha} → ${OUT}`)
