// SPDX-License-Identifier: LicenseRef-AresRPG-Source-Available
// © 2026 Sceat — All rights reserved. See LICENSE.
// M0 seam glue (§brief RENDER↔CORE SEAM): loads the demo island by driving the REAL world
// generator (gen/world_gen.js — terrain + biomes + surface decoration) through WS3/WS4's
// synchronous mesh→upload pipeline on the main thread. This is an M0-only shortcut — M1 replaces
// it with the real streaming ring manager over the worker pools (pool.js is already wired +
// unit-tested, just not in this loop yet). Kept as its own module so engine.js stays a thin
// facade instead of embedding a generation loop.
//
// Also hosts the §7/§8 bench SYNTHETIC hook (`load_synthetic_chunks`): lays out an arbitrary chunk
// COUNT (not just a fixed radius) in an expanding square-ring grid, single Y layer. It deliberately
// stays on the lightweight, self-contained generate_test_chunk generator (not world_gen) so the
// bench measures the render/bundle path at scale without world-gen cost skewing the numbers —
// still the same mesh_chunk → terrain_renderer.upload_chunk seam as the island loader.

import { generate_test_chunk } from '../chunks/test_gen.js'
import { generate_world_chunk, world_surface_y } from '../gen/world_gen.js'
import { mesh_chunk } from '../mesh/mesher.js'
import { create_chunk_store } from '../chunks/store.js'

/** @typedef {import('../chunks/format.js').ChunkRecord} ChunkRecord */

/** Vertical chunk slots loaded per demo column — cy 0..5 (world y 0..191): covers ocean floor
 *  (~90), sea level (128) and the rolling/hill terrain band around the spawn. */
const DEMO_VERTICAL_CHUNKS = 6

/** Candidate chunk offsets probed (in order) for a demo spawn on a coastline/plains cell. We want
 *  the center column's surface near sea level (128) with a land+water mix around it so the island
 *  shows both shoreline and terrain. Deterministic — same seed ⇒ same pick; [0,0] wins for the
 *  hardcoded "aresrpg" seed (center surface y≈134, ocean within 64 blocks). */
const SPAWN_CANDIDATES = /** @type {Array<[number, number]>} */ ([
  [0, 0],
  [8, 0],
  [0, 8],
  [16, 16],
  [-12, 6],
  [24, -10],
  [6, 20],
  [-20, -20],
  [40, 40],
  [3, -3],
])

/** @type {[number, number] | null} memoized spawn offset (chunk coords), scanned on first use. */
let spawn_offset = null

/**
 * Picks the demo spawn chunk offset: the first candidate whose center-column surface height is in
 * [126,140] (just around sea level = coastline / low plains) AND which has both land (≥128) and
 * water (<128) within a 64-block ring, so the island is neither all-ocean nor all-inland. Falls
 * back to the origin if none qualify. Pure/deterministic for the fixed seed — memoized.
 * @returns {[number, number]} [cx, cz] chunk offset the island is centered on
 */
function pick_spawn_offset() {
  if (spawn_offset !== null) return spawn_offset
  for (const [ccx, ccz] of SPAWN_CANDIDATES) {
    const wx = ccx * 32 + 16
    const wz = ccz * 32 + 16
    const height = world_surface_y(wx, wz)
    if (height < 126 || height > 140) continue
    let has_land = false
    let has_water = false
    for (const [dx, dz] of [
      [64, 0],
      [-64, 0],
      [0, 64],
      [0, -64],
      [48, 48],
      [-48, -48],
    ]) {
      if (world_surface_y(wx + dx, wz + dz) >= 128) has_land = true
      else has_water = true
    }
    if (has_land && has_water) {
      spawn_offset = [ccx, ccz]
      return spawn_offset
    }
  }
  spawn_offset = [0, 0]
  return spawn_offset
}

/**
 * Loads the demo island: an (2*radius+1)² grid of world columns (vertical stack cy 0..5) centered
 * on a scanned coastline/plains spawn, generated by the REAL world generator (terrain + biomes +
 * surface decoration), meshed and uploaded synchronously. §M0 seam — M1 swaps in the streaming
 * ring manager. Default radius 5 ⇒ an 11×11 column island.
 * @param {object} params
 * @param {import('../render/pool_renderer.js').TerrainRenderer} params.terrain_renderer
 * @param {number} [params.radius] chunk radius around the spawn; 11×11 island = radius 5
 * @returns {{ chunks_loaded: number }}
 */
export function load_test_island({ terrain_renderer, radius = 5 }) {
  const [spawn_cx, spawn_cz] = pick_spawn_offset()

  // Real neighbor halos need each meshed chunk's boundary neighbors resident, so we generate the
  // island box PLUS a one-chunk outward horizontal ring (cached, never meshed) into a store, then
  // mesh in a second pass reading across the seams. That culls the interior seam walls (a solid
  // column's face against an equally-solid neighbor column — ~23 spurious +x quads/surface-chunk in
  // isolation) and gives boundary AO/light parity with the interior. Vertical neighbors within the
  // loaded stack are box chunks (already resident); above/below the stack is sky/unseen bedrock, so
  // only the horizontal ring needs extra generation. generate_world_chunk is pure + deterministic,
  // so ring generation has no side effects and shared edges are generated once via the store.
  const footprint = 2 * (radius + 1) + 1 // box (2r+1) + a 1-chunk ring on each horizontal side
  const store = create_chunk_store({ capacity: footprint * footprint * DEMO_VERTICAL_CHUNKS })

  // Pass 1 — generate the expanded footprint (box + outward ring) into the store. (cx,cz) OUTER,
  // cy INNER so each column's six stacked chunks reuse world_gen's cached column profile.
  for (let dx = -radius - 1; dx <= radius + 1; dx += 1) {
    for (let dz = -radius - 1; dz <= radius + 1; dz += 1) {
      for (let cy = 0; cy < DEMO_VERTICAL_CHUNKS; cy += 1) {
        store.put(generate_world_chunk(spawn_cx + dx, cy, spawn_cz + dz))
      }
    }
  }

  // Pass 2 — mesh + upload ONLY the box; the ring exists solely as halo neighbors.
  let chunks_loaded = 0
  for (let dx = -radius; dx <= radius; dx += 1) {
    for (let dz = -radius; dz <= radius; dz += 1) {
      const cx = spawn_cx + dx
      const cz = spawn_cz + dz
      for (let cy = 0; cy < DEMO_VERTICAL_CHUNKS; cy += 1) {
        const chunk_record = /** @type {ChunkRecord} */ (store.get(cx, cy, cz))
        const { quad_buffer, quad_count } = mesh_chunk(chunk_record, store.neighbor_halos(cx, cy, cz))
        if (quad_count > 0) {
          terrain_renderer.upload_chunk([cx, cy, cz], quad_buffer, quad_count)
          chunks_loaded += 1
        }
      }
    }
  }

  return { chunks_loaded }
}

/**
 * Generates `[cx, cz]` coords for an expanding square ring/grid, single Y layer, centered on the
 * origin — ring 0 is just the origin, ring k adds the square annulus at Chebyshev distance k.
 * Deterministic order (ring-by-ring, row-major within a ring) so a given `chunk_count` always
 * yields the same layout (§3.7 determinism law — this is a bench fixture, but reproducibility
 * still matters for comparable bench runs).
 * @param {number} chunk_count total coords to produce
 * @returns {Array<[number, number]>}
 */
function ring_grid_coords(chunk_count) {
  /** @type {Array<[number, number]>} */
  const coords = []
  if (chunk_count <= 0) return coords

  coords.push([0, 0])
  for (let ring = 1; coords.length < chunk_count; ring += 1) {
    for (let x = -ring; x <= ring && coords.length < chunk_count; x += 1) {
      for (let z = -ring; z <= ring && coords.length < chunk_count; z += 1) {
        // Only the outer edge of this ring (Chebyshev distance === ring) — interior coords were
        // already emitted by smaller rings.
        if (Math.max(Math.abs(x), Math.abs(z)) !== ring) continue
        coords.push([x, z])
      }
    }
  }
  return coords
}

/**
 * §7/§8 bench SYNTHETIC hook: loads exactly `chunk_count` test chunks in a ring/grid layout
 * (single Y layer, cy=0) instead of the fixed 7×7 island, via the same real gen→mesh→upload
 * pipeline as `load_test_island` — so `synthetic-2000.spec.js` exercises the actual sector
 * BundleGroup path at scale, not a synthetic stat injected after the fact. Used by
 * `create_engine({ synthetic_chunks })` (see engine.js).
 * @param {object} params
 * @param {import('../render/pool_renderer.js').TerrainRenderer} params.terrain_renderer
 * @param {number} params.chunk_count total chunks to generate/mesh/upload
 * @returns {{ chunks_loaded: number }}
 */
export function load_synthetic_chunks({ terrain_renderer, chunk_count }) {
  let chunks_loaded = 0

  for (const [cx, cz] of ring_grid_coords(chunk_count)) {
    const chunk_record = generate_test_chunk(cx, 0, cz)
    const { quad_buffer, quad_count } = mesh_chunk(chunk_record)
    if (quad_count > 0) {
      terrain_renderer.upload_chunk([cx, 0, cz], quad_buffer, quad_count)
      chunks_loaded += 1
    }
  }

  return { chunks_loaded }
}
