// SPDX-License-Identifier: LicenseRef-AresRPG-Source-Available
// © 2026 Sceat — All rights reserved. See LICENSE.
/// PROGRESSION MATH — the frozen character-progression kernels as PURE transforms over plain scalars (S-70 size
/// split: moved VERBATIM from core `aresrpg::progression`, which stays as thin delegates — the core package sits
/// against the 102,400-byte protocol cap and foundation is the library home for stateless calculators). Zero
/// objects, zero events, zero state — the quarantine law.
///
/// FROZEN LAWS, not dials (they ride WITH the immutable XP curve): SPEC §3 fixes the per-level point grants and
/// ANNEX §4c/§5.4 fix the HP growth slope + the natural-regen rate "verbatim". §17.31's tunable surface is the
/// per-CLASS BASE rows (core GameConfig), never these shared slopes.
module aresrpg_foundation::progression_math;

use aresrpg_foundation::character_xp;

/// SPEC §3: "Each level from 2 grants 5 stat points to assign freely and 1 spell point."
const STAT_POINTS_PER_LEVEL: u64 = 5;
const SPELL_POINTS_PER_LEVEL: u64 = 1;

/// ANNEX §4c: `max_hp = class_base + max(0, level−1) × 5 + vitality` (reference corpus `Combat.HEALTH_PER_LEVEL`).
const HP_PER_LEVEL: u64 = 5;

/// ANNEX §5.4 — natural HP regen rate, reference-corpus `Combat.computeRegenPerSecond` VERBATIM:
/// `2.0 + (level×0.4 + wisdom/7.5)/5` HP per second. Rearranged to an EXACT integer rational (no floats on
/// chain): HP/sec = `(REGEN_BASE + level×REGEN_PER_LEVEL + wisdom×REGEN_PER_WIS) / 75`, so HP accrued over an
/// elapsed span = `elapsed_ms × num / REGEN_DEN_MS`.
const REGEN_BASE: u64 = 150; // 2.0 HP/s × 75
const REGEN_PER_LEVEL: u64 = 6; // 0.08 HP/s per level × 75
const REGEN_PER_WIS: u64 = 2; // (1/37.5) HP/s per wisdom × 75
const REGEN_DEN_MS: u64 = 75_000; // 75 (the per-second denominator) × 1000 ms/s

/// Stat + spell points newly granted by leveling from `from_level` to `to_level`: 5 stat / 1 spell per level
/// gained (every level from 2 grants, so any positive gain grants — §3). Returns `(stat_points, spell_points)`;
/// `(0, 0)` when no level was gained (`to_level <= from_level`). Pure — the caller banks the points on-chain.
public fun points_for_level_range(from_level: u64, to_level: u64): (u64, u64) {
  if (to_level <= from_level) return (0, 0);
  let gained = to_level - from_level;
  (gained * STAT_POINTS_PER_LEVEL, gained * SPELL_POINTS_PER_LEVEL)
}

/// Add `delta` xp to `current_xp` and return the new total: the gain scales by `xp_multiplier_hundredths`
/// (100 = 1.00×, §17.20) and the total clamps to `max_reachable_level`'s threshold — XP earned AT the cap is
/// DISCARDED, never banked (§17.20 "zeroed"); a lowered cap pins the total back down (the cap is
/// authoritative). Move's checked arithmetic makes any overflow ABORT (never silently wrap). The core wrapper
/// owns the freeze gate + the GameConfig reads.
public fun xp_add_capped(current_xp: u64, delta: u64, xp_multiplier_hundredths: u64, max_reachable_level: u64): u64 {
  let boosted = delta * xp_multiplier_hundredths / 100;
  let cap = character_xp::xp_for_level(max_reachable_level);
  let total = current_xp + boosted;
  if (total > cap) cap else total
}

/// Max HP over a class BASE at `level` with `vitality` — ANNEX §4c frozen formula. The per-class base is the
/// core GameConfig row's tunable; the per-level slope (`HP_PER_LEVEL`) and the shape are frozen here.
public fun max_hp_from_base(base_hp: u64, level: u64, vitality: u64): u64 {
  let growth = if (level > 1) (level - 1) * HP_PER_LEVEL else 0;
  base_hp + growth + vitality
}

/// Lazy natural HP regen. From the stored `hp` + its `hp_updated_ms` last-touch, the character's `max_hp`, and
/// the rate inputs (`level`, `wisdom`), compute the HP regenerated BY `now_ms` and the NEW last-touch stamp,
/// returned as `(new_hp, new_hp_updated_ms)`. Callers that only READ effective HP discard the stamp; a caller
/// that MATERIALIZES (writes the block back — a heal) stores BOTH.
///
/// REMAINDER-CARRY LAW (the house regen law): the stamp advances only by the time that produced WHOLE HP
/// (`consumed_ms`), NEVER straight to `now_ms` — the sub-unit fraction stays on the clock, so slow ticks never
/// starve. Total function:
///  • already full (`hp >= max_hp`) ⇒ pin to max, stamp `now` (no overheal banked).
///  • no time elapsed / clock skew (`now_ms <= hp_updated_ms`) ⇒ unchanged.
///  • sub-unit accrual (`accrued == 0`) ⇒ HP unchanged AND stamp UNCHANGED (the whole span rolls forward).
///  • reaches max ⇒ pin to max, stamp `now` (the overshoot fraction is discarded at full HP).
public fun regen_hp(hp: u64, hp_updated_ms: u64, max_hp: u64, level: u64, wisdom: u64, now_ms: u64): (u64, u64) {
  if (hp >= max_hp) return (max_hp, now_ms);
  if (now_ms <= hp_updated_ms) return (hp, hp_updated_ms);
  let elapsed = now_ms - hp_updated_ms;
  let num = REGEN_BASE + level * REGEN_PER_LEVEL + wisdom * REGEN_PER_WIS; // ≥ REGEN_BASE, never 0
  let accrued = elapsed * num / REGEN_DEN_MS;
  if (accrued == 0) return (hp, hp_updated_ms); // sub-unit only — keep the stamp so the fraction carries forward
  if (hp + accrued >= max_hp) return (max_hp, now_ms); // reached full — no remainder to bank
  let consumed_ms = accrued * REGEN_DEN_MS / num; // the ms that produced WHOLE hp (≤ elapsed)
  (hp + accrued, hp_updated_ms + consumed_ms) // carry the leftover fraction as un-consumed time
}

// ═══ Tests — the kernel truths (the core delegates are covered by the aresrpg suite's live paths) ═══

#[test]
fun points_grants_per_level() {
  let (s, p) = points_for_level_range(1, 5);
  assert!(s == 20 && p == 4, 0); // 4 levels gained → 20 stat / 4 spell
  let (s0, p0) = points_for_level_range(5, 5);
  assert!(s0 == 0 && p0 == 0, 1); // no gain → no grant
}

#[test]
fun max_hp_slope_and_floor() {
  assert!(max_hp_from_base(70, 1, 0) == 70, 0); // level 1 → base verbatim
  assert!(max_hp_from_base(70, 10, 0) == 115, 1); // +9 × 5
  assert!(max_hp_from_base(70, 10, 25) == 140, 2); // + vitality
}

#[test]
fun regen_carries_remainder() {
  // senshi L1 (num 56): 5000ms → +3 whole HP, stamp advances by the CONSUMED ms only (4017), not to now.
  let (hp, stamp) = regen_hp(25, 5_000, 70, 1, 0, 10_000);
  assert!(hp == 28, 0);
  assert!(stamp == 5_000 + 3 * 75_000 / 56, 1); // 9017 — the fraction stays on the clock
  // sub-unit window → both unchanged (the carry law).
  let (hp2, stamp2) = regen_hp(25, 5_000, 70, 1, 0, 5_400);
  assert!(hp2 == 25 && stamp2 == 5_000, 2);
  // tops out → pin to max, stamp now.
  let (hp3, stamp3) = regen_hp(69, 0, 70, 1, 0, 1_000_000);
  assert!(hp3 == 70 && stamp3 == 1_000_000, 3);
}

#[test]
fun xp_cap_discards() {
  assert!(xp_add_capped(0, 1000, 100, 200) == 1000, 0); // 1.00× plain add under the cap
  assert!(xp_add_capped(0, 1000, 200, 200) == 2000, 1); // 2.00× boost
  let cap = character_xp::xp_for_level(200);
  assert!(xp_add_capped(cap - 1, 1_000_000_000, 100, 200) == cap, 2); // clamped AT the cap — excess discarded
}
