// SPDX-License-Identifier: LicenseRef-AresRPG-Source-Available
// © 2026 Sceat — All rights reserved. See LICENSE.
// FIXTURE PROVENANCE: GET https://rpc.aresrpg.world/v1/encyclopedia, captured 2026-07-17 in
// packages/frontend/src/rpc/fixtures/encyclopedia.json; this array is its 374 unique .mobs[].name values, sorted.
// Refresh from the scoped live endpoint with scripts/refresh_mob_slugs_fixture.mjs.
export default [
  'Aberrant Hulk',
  'Abyss Eel',
  'Alley Bunny',
  'Aloe Gaia',
  'Ambrine',
  'Ancient Hermit',
  'Ancient Tusk',
  'Anglerqueen',
  'Aragog Spawnling',
  'Aragog the Matriarch',
  "Aragog's child",
  'Arcane Bricheton',
  'Arcane Gaia',
  'Arcanine',
  'Archaeo',
  'Armorscale',
  'Ash Prophet',
  'Ashraptor',
  'Ashskin',
  'Banner Wraith',
  'Bannerwatch',
  'Barley Bricheton',
  'Basalt Shambler',
  'Bear Patriarch',
  'Bisonbrute',
  'Bjorn',
  'Bjorn Prime',
  'Black Piranha King',
  'Blood Bricheton',
  'Boar',
  'Bone Choir',
  'Bonegorger',
  'Boneguard',
  'Boneherald',
  'Bonelet',
  'Bonelord',
  'Broodfather',
  'Broodling',
  'Burnt Effigy',
  'Campcaw',
  'Cauldron Imp',
  'Cave Raptor',
  'Chant Leader',
  'Chief Wooligan',
  'Choir Apostate',
  'Choir Sentinel',
  'Cinder Acolyte',
  'Cinder Bonelord',
  'Cinderwhisker',
  'Clawlord',
  'Cluckling',
  'Cocoon King',
  'Crabito The Drowned',
  'Crabito the Crowned',
  'Crazy Goblin',
  'Crownkeeper',
  'Crystal Golem',
  'Cursed Bricheton',
  'Cursed Gaia',
  'Deathless Paragon',
  'Deep Auditor',
  'Deep Leviathan',
  'Deep Oracle',
  'Diamantine',
  'Ditch Koaletin',
  'Draconic Bricheton',
  'Draconine',
  'Dragon Gaia',
  'Dread Lancer',
  'Drowned Buccaneer',
  'Drownlure Tyrant',
  'Duke the Insolvent',
  'Duskine',
  'Elder Sloth',
  'Ember Kweebec',
  'Ember Silkweaver',
  'Emberbat',
  'Emberwulf',
  'Empress of Widows',
  'Ensable Hatchling',
  'Ensable Warden',
  'Eternwool',
  'Fen Dread',
  'Fen Stalker',
  'Fen the Silent',
  'Fenrik the Dire',
  'Fenrik the Moonlit',
  'Feran Cub',
  'Feran Elder Warrior',
  'Feran Scout',
  'Feran the Whisperer',
  'Fire Goblin',
  'Firekoa',
  'Firesteel Golem',
  'Flareling',
  'Flarewolf',
  'Frost Silkweaver',
  'Frostclaw',
  'Frostkoa',
  'Frostling',
  'Frostshamble',
  'Frostwolf',
  'Gate Watcher',
  'Gilded Apostate',
  'Glacial Sovereign',
  'Glass Snail',
  'Glasskin Chorister',
  'Glimmer Shade',
  'Gloom Piper',
  'Gloomwing',
  'Gobadoc the Gourmand',
  'Gobadoc the Starved',
  'Goblin Brute',
  'Goblin Duke',
  'Goblin Runt',
  'Goblin Sous-Chef',
  'Goblin Taster',
  'Godbone Colossus',
  'Goldhen Matilda',
  'Gopnik',
  'Gopnik Blyat',
  'Grainfox',
  'Great Razmo',
  'Green Goblin',
  'Green Walker',
  'Grimfang',
  'Grizzly',
  'Grizzly the Undying',
  'Hadean Hound',
  'Hades Keeper',
  'Halo Judge',
  'Halo Zealot',
  'Hammerhead',
  'Hanged Effigy',
  'Heartwood Ancient',
  'Hermitude',
  'Hornhead',
  'Ivory Gaia',
  'Jadine',
  'Koa',
  'Koa the Bloated',
  'Koa the Eternal',
  'Koagulant',
  'Koaletin',
  'Koard',
  'Koloss',
  'Kraken Leviathan',
  'Kweebec Grove Heart',
  'Kweebec Heartwood',
  'Lantern Wraith',
  'Lava Hound',
  'Light Bearer',
  'Lightless Frog',
  'Lunarine',
  'Lure Tyrant',
  'Magmaclaw',
  'Magmalug',
  'Magmalug the Gorged',
  'Magmaweaver',
  'Magmooligan',
  'Maledictine',
  'Malt Bricheton',
  'Mammoth King',
  'Marrow Acolyte',
  'Maw Gnat',
  'Mire Creeper',
  'Mire Titan',
  'Moldrot',
  'Moonclaw Empress',
  'Moonfang Alpha',
  'Moonfang Ancient',
  'Moss Bear',
  'Nerak Priest',
  'Nerak the Marrow King',
  'Nerakling Marrow',
  'Nightcap Gaia',
  'Nine-Tails Kitsune',
  'Noggin the Chief',
  'Obsidian Tokek',
  'Obsidian Wisp',
  'Obsidine',
  'Orchid Gaia',
  'Pale Mare',
  'Pale Weaver',
  'Palebones',
  'Parasite',
  'Pecker the Widow',
  'Phacoch Cultist',
  'Phacochef',
  'Phantom Gaia',
  'Piglet',
  'Pike',
  'Pilgrim Husk',
  'Piranha School',
  'Piranha Tyrant',
  'Plague Razmo',
  'Plaguemo',
  'Plaza Chicklet',
  'Polar Reaver',
  'Primal Tyrant',
  'Primordial Koa',
  'Pterodon',
  'Pyre Colossus',
  'Pyre Moth',
  'Pyre Tender',
  'Pyre Titan',
  'Pyre Warthog',
  'Pyre Wraith',
  'Quartzine',
  'Queen of the Crater',
  'Quill Fledgling',
  'Ramrage Eternal',
  'Ramrage the Ancient',
  'Rapido the Plague King',
  'Razkin',
  'Razlord Prime',
  'Razmaster',
  'Razmo',
  'Razmo the Crowned',
  'Razord',
  'Reef Pike',
  'Retarded Draugr',
  'Rex Alpha',
  'Rex Primordial',
  'Rex the Elder',
  'Rex the World Eater',
  'Rift Matriarch',
  'Rift Toad',
  'Riftmaw Devourer',
  'Risen Prime',
  'Rooftop Pecker',
  'Rootlord Ancient',
  'Runt Piglet',
  'Saberfang the Ageless',
  'Sabertooth',
  'Sand Lich',
  'Sandskip',
  'Sandwraith',
  'Sanguine',
  'Sapling Warden',
  'Saurian Scout',
  'Saurian Warden',
  'Saurian Warlord',
  'Scar Borer',
  'Scar Chanter',
  'Scarak Defender',
  'Scarak Fighter',
  'Scarak Hive Prime',
  'Scarak Louse',
  'Scarak Overlord',
  'Scarak Seeker',
  'Scarbound Auditor',
  'Scarhound',
  'Scorched Bricheton',
  'Scuttler',
  'Seedkin',
  'Seraph Herald',
  'Shadow Knight',
  'Shadow Vulture',
  'Shore Crab',
  'Shore Gull',
  'Shrooms Gaia',
  'Silk Lancer',
  'Silk Warden',
  'Silkling',
  'Silklord Ageless',
  'Sir Deathless',
  'Sir Rattlebone',
  'Skyfin',
  'Skyray',
  'Skywarden',
  'Slothling',
  'Slothmaster',
  'Snapjaw',
  'Soul Auditor',
  'Soulking',
  'Sparkling',
  'Sparrowdart',
  'Spinner Prime',
  'Sporeback',
  'Sproutkin',
  'Stormhawk',
  'Strawman',
  'Stray Kit',
  'Suize Bricheton',
  'Suture Priest',
  'Swamp Firekoa',
  'Swamp Sentinel',
  'Talokan Aero',
  'Talokan Ancient',
  'Talokan Nakwa',
  'Talokan Tidelord',
  'Tanjirize Bricheton',
  'Tentacle Horror',
  'The Abbot of Ends',
  'The Anglerdeep Matron',
  'The Ashsinger',
  'The Banner of Silence',
  'The Choirmaster',
  'The Crown Regent',
  'The Crownless Seraph',
  "The Dead God's Eye",
  'The Dissonant',
  'The Ember King',
  'The First Hollow',
  'The First Ward',
  'The Golden Matron',
  'The Hadean Gatekeeper',
  'The Last Guardian',
  'The Patient Elder',
  'The Saurian God-King',
  'The Silent Abbot',
  'The Soulless Regent',
  'The Sunken Claw',
  'The Tempest Lord',
  'The Titan Bear',
  'The Void Dragon',
  'The White Widow',
  'The Wound Oracle',
  'Thunder Owl',
  'Thunderlord',
  'Thunderscorn',
  'Tikling',
  'Timber Wolf',
  'Titan Bear',
  'Titan Claw',
  'Titan Koa',
  'Tokek',
  'Tokek the Sunking',
  'Trillo',
  'Truffle Gaia',
  'Truffle Wraith',
  'Tuskarr the Eternal',
  'Tuskarr the Oldest',
  'Tusklet',
  'Ukranize Bricheton',
  'Velkarion',
  'Void Crawler',
  'Void Eye',
  'Void Harrier',
  'Void Necromancer',
  'Void Spawn',
  'Void Spawnling',
  'Wall Fragment',
  'Wallow Grub',
  'Wanilla the Pretty',
  'Warthog',
  'Weak Snapthorn',
  'Weald Shade',
  'Weaver',
  'Webling',
  'Wheat Bricheton',
  'Wheat Slither',
  'Widow Consort',
  'Widow Matron',
  'Widow of Widows',
  'Wildling Huntress',
  'Wildling Spearling',
  'Wildlord',
  'Wither Gaia',
  'Wolfling',
  'Woolice',
  'Wooligan',
  'Wooling',
  'Woolkin Celestial',
  'Woolly Doom',
  'Wound Leech',
  'Wraithling',
  'Yeti',
  'Yeti the Deathless',
  'Young Parasite',
  'Yurei Abbot',
  'Zephyr Silklord',
  'Zephyr Silkweaver',
] as const
