// SPDX-License-Identifier: LicenseRef-AresRPG-Source-Available
// © 2026 Sceat — All rights reserved. See LICENSE.

export {
  experience_curve,
  experience_progress,
  craft_max_ingredients,
  craft_required_level,
  craft_slot_capacity,
  craft_success_percent,
  craft_xp_at_level,
  craft_xp_from_ingredient_count,
  gather_quantity_bounds,
  gather_time_ms,
  gather_xp,
  job_experience_curve,
  job_level_from_xp,
  job_max_level,
  job_xp_for_level,
  level_from_xp,
  max_level,
  tier_unlock_level,
  xp_for_level,
} from './experience.ts'
export { MODEL_VARIANT_SEPARATOR, model_variant_identity, type ModelVariantIdentity } from './model_variant.ts'
export {
  characteristic_allocation_quote,
  characteristic_cost_step,
  characteristic_ladders,
  characteristic_spending_quote,
  characteristic_value_cost,
  characteristic_values_cost,
  type CharacteristicCostStep,
  type CharacteristicLadder,
  type CharacteristicQuote,
  type CharacteristicValues,
} from './characteristics.ts'
export {
  gatherable_catalog,
  gatherable_item_types,
  gatherable_of,
  protector_level_range,
  type Gatherable,
  type GatheringJob,
  type ProtectorLevelRange,
} from './gathering.ts'
export {
  characteristic_names,
  class_names,
  class_spell_shape_errors,
  class_spell_unlocks,
  is_class_name,
  is_job_slug,
  is_stat_name,
  job_groups,
  job_kind_of,
  job_slugs,
  stat_names,
  type ClassName,
  type CharacteristicName,
  type JobSlug,
  type JobKind,
  type StatName,
} from './identity.ts'
export { pet_max_feeds } from './pet.ts'
export {
  rune_effect,
  rune_max_apps,
  rune_unit_weight,
  rune_unit_weights,
  rune_weight_scale,
  type RuneEffect,
  type RuneTier,
} from './rune.ts'
export {
  dofus_weapon_damage_envelope,
  item_budget_envelope,
  item_budget_standing,
  item_budget_stat_weight,
  item_budget_stat_weights,
  type ItemBudgetEnvelope,
  type ItemBudgetStanding,
  type WeaponDamageEnvelope,
} from './item_power.ts'
export {
  dofus_mob_power_envelope,
  mob_power_cohort_of_role,
  type MobPowerBand,
  type MobPowerCohort,
  type MobPowerEnvelope,
} from './mob_power.ts'
export {
  character_consumable_types,
  craft_job_of,
  accessory_categories,
  armor_categories,
  consumable_types,
  element_names,
  equipment_categories,
  item_categories,
  item_is_stackable,
  craft_batch_limit,
  craft_stackable_batch_limit,
  craft_unique_batch_limit,
  item_stat_center,
  is_item_category,
  is_equipment_category,
  is_tool_category,
  is_weapon_category,
  stackable_item_categories,
  tool_categories,
  weapon_categories,
  type CharacterConsumableType,
  type ConsumableType,
  type ElementName,
  type EquipmentCategory,
  type ItemCategory,
  type WeaponCategory,
} from './item.ts'
export { chain_to_client_coordinate, client_to_chain_coordinate, world_center, world_size } from './world.ts'
export {
  character_equipment_slots,
  combat_equipment_slots,
  equipment_slot_accepts,
  relic_slots,
  rig_slots,
  type CharacterEquipmentSlot,
} from './equipment.ts'
