#!/usr/bin/env node
// SPDX-License-Identifier: LicenseRef-AresRPG-Source-Available
// © 2026 Sceat — All rights reserved. See LICENSE.

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import prettier from 'prettier'

import { generate_projected_doors, parse_doors } from './generate_doors.mjs'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
export const SEED_DOORS_OUT_PATH = join(root, 'src/seed_doors.gen.ts')
export const SEED_CONTRACT_OUT_PATH = join(root, 'src/seed_contract.gen.ts')

const modules = [
  {
    path: join(root, '../move/sources/seed.move'),
    module: 'seed',
    package_key: 'package',
  },
  {
    path: join(root, '../move-math/sources/item_stats.move'),
    module: 'item_stats',
    package_key: 'math_package',
    selected: { new: 'new_item_stats' },
  },
  {
    path: join(root, '../move-math/sources/item_damages.move'),
    module: 'item_damages',
    package_key: 'math_package',
    selected: { new: 'new_item_damages' },
  },
  {
    path: join(root, '../move-math/sources/spell_effect.move'),
    module: 'spell_effect',
    package_key: 'math_package',
    selected: { new_effect: 'new_effect', new_spell_level: 'new_spell_level' },
  },
  {
    path: join(root, '../move-math/sources/mob_data.move'),
    module: 'mob_data',
    package_key: 'math_package',
    selected: { new_loot_entry: 'new_mob_loot_entry', new_mob_spell: 'new_mob_spell' },
  },
  {
    path: join(root, '../move-math/sources/world_map.move'),
    module: 'world_map',
    package_key: 'math_package',
    selected: {
      new_mob_row: 'new_mob_row',
      new_resource_row: 'new_resource_row',
      new_room_mob: 'new_room_mob',
      new_dungeon_room: 'new_dungeon_room',
    },
  },
]

export const seed_doors = () =>
  modules.flatMap(({ path, module, package_key, selected }) => {
    const parsed = parse_doors(readFileSync(path, 'utf8'), selected ? new Set(Object.keys(selected)) : null)
    return parsed
      .filter(({ name }) => !selected || selected[name])
      .map((door) => ({
        ...door,
        module,
        package_key,
        export_name: selected?.[door.name] ?? door.name,
      }))
  })

export const generate_seed_doors = () =>
  generate_projected_doors(seed_doors(), SEED_DOORS_OUT_PATH, {
    source: 'seed.move and its Move value constructors',
    description: 'seeding door',
  })

const key_sources = ['seed', 'mob_template', 'spell_template', 'crafting', 'shop'].map((module) => ({
  module,
  path: join(root, `../move/sources/${module}.move`),
}))

export const seed_string_keys = () =>
  key_sources.flatMap(({ path, module }) =>
    [...readFileSync(path, 'utf8').matchAll(/public struct (\w+Key)\(String\)\s+has[^;]*;/g)].map(([, name]) => ({
      name,
      module,
    }))
  )

export const generate_seed_contract = async () => {
  const rows = seed_string_keys()
  const raw = `// SPDX-License-Identifier: LicenseRef-AresRPG-Source-Available
// © 2026 Sceat — All rights reserved. See LICENSE.
// GENERATED by scripts/generate_seed_doors.mjs from Move String key structs — DO NOT EDIT.

export const SEED_STRING_KEYS = Object.freeze({
${rows.map(({ name, module }) => `  ${name}: Object.freeze({ module: '${module}', name: '${name}' }),`).join('\n')}
})
`
  return prettier.format(raw, { ...(await prettier.resolveConfig(SEED_CONTRACT_OUT_PATH)), parser: 'typescript' })
}

const invoked_directly = import.meta.main ?? (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1])
if (invoked_directly) {
  const [output, contract] = await Promise.all([generate_seed_doors(), generate_seed_contract()])
  writeFileSync(SEED_DOORS_OUT_PATH, output)
  writeFileSync(SEED_CONTRACT_OUT_PATH, contract)
  console.log(`seed_doors.gen.ts written — ${seed_doors().length} doors`)
}
