query get_player_infos($identity_id: Int!, $appId: Int!) {
  EnjinIdentity(id: $identity_id) {
    wallet {
      ethAddress
      balances(appId: $appId) {
        value
        token {
          id
          name
        }
      }
    }
  }
}
