mutation mint_fungible_tokens(
  $identityId: Int!
  $appId: Int!
  $tokenId: String!
  $recipients: [String!]!
  $values: [Int!]!
) {
  transaction: CreateEnjinRequest(
    identity_id: $identityId
    appId: $appId
    type: MINT
    mint_token_data: {
      token_id: $tokenId
      recipient_address_array: ["WALLET_ADDRESS_1", "WALLET_ADDRESS_2"]
      value_array: [5, 3]
    }
  ) {
    id
    encodedData
  }
}
