// SPDX-License-Identifier: LicenseRef-AresRPG-Source-Available
// © 2026 Sceat — All rights reserved. See LICENSE.

import { expect, test } from '@playwright/test'

test('Shift selection crushes the exact reviewed set with one SDK call', async ({ page }) => {
  await page.goto('/e2e/fixtures/inventory_actions.html')
  const cells = page.locator('.chr-equip__grid button')
  await cells.nth(0).click()
  await cells.nth(1).click({ modifiers: ['Shift'] })
  await expect(page.locator('.chr-equip__grid button[aria-pressed=true]')).toHaveCount(2)
  await cells.nth(1).click({ button: 'right' })
  await page.getByRole('button', { name: 'Crush (2)', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.locator('[data-crush-item]')).toHaveCount(2)
  await expect(dialog).toContainText('Test Hat 1')
  await expect(dialog).toContainText('Test Hat 2')
  await page.screenshot({ animations: 'disabled', path: test.info().outputPath('crush-selection.png') })
  await dialog.getByRole('button', { name: 'Crush (2)', exact: true }).click()
  await expect(page.locator('body')).toHaveAttribute('data-crush-calls', JSON.stringify([['gear-1', 'gear-2']]))
  await expect(page.locator('.chr-equip__grid button')).toHaveCount(1)
  await expect(page.locator('[data-crush-progress]')).toContainText('Crushing 2')
})

test('a changed selection disables confirmation without crushing a subset', async ({ page }) => {
  await page.goto('/e2e/fixtures/inventory_actions.html')
  const cells = page.locator('.chr-equip__grid button')
  await cells.nth(0).click()
  await cells.nth(1).click({ modifiers: ['Shift'] })
  await cells.nth(0).click({ button: 'right' })
  await page.getByRole('button', { name: 'Crush (2)', exact: true }).click()
  await page.evaluate(() => window.dispatchEvent(new Event('fixture-item-departs')))
  await expect(page.getByRole('dialog').getByRole('button', { name: 'Crush (2)', exact: true })).toBeDisabled()
  await expect(page.getByRole('alert')).toBeVisible()
  await expect(page.locator('body')).not.toHaveAttribute('data-crush-calls')
})

test('right-clicking an unselected item replaces the batch', async ({ page }) => {
  await page.goto('/e2e/fixtures/inventory_actions.html')
  const cells = page.locator('.chr-equip__grid button')
  await cells.nth(0).click()
  await cells.nth(1).click({ modifiers: ['Shift'] })
  await cells.nth(2).click({ button: 'right' })
  await page.getByRole('button', { name: 'Crush (1)', exact: true }).click()
  await expect(page.getByRole('dialog').locator('[data-crush-item]')).toHaveCount(1)
  await expect(page.getByRole('dialog')).toContainText('Test Hat 3')
})

for (const width of [1280, 590])
  test(`sale form shows selected item rolls and damages at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 700 })
    await page.goto('/e2e/fixtures/inventory_actions.html?sell')
    const inventory = page.locator('[data-marketplace-owned-item]')
    await inventory.nth(0).click()
    const form = page.locator('.market-sale-form')
    await expect(form.locator('[data-item-stats]')).toContainText('+11')
    await expect(form.locator('[data-item-stats]')).toContainText('-4')
    await expect(form.locator('[data-item-damages]')).toContainText('3 - 7')
    await page.evaluate(() => window.dispatchEvent(new Event('fixture-item-stats')))
    await expect(form.locator('[data-item-stats]')).toContainText('+55')
    await inventory.nth(1).click()
    await expect(form.locator('[data-item-stats]')).toContainText('+22')
    await expect(form.locator('[data-item-stats]')).not.toContainText('+11')
    await page.screenshot({ animations: 'disabled', path: test.info().outputPath('sale-details.png') })
    await form.locator('input').fill('1')
    const list = form.getByRole('button', { name: 'List for sale', exact: true })
    await list.scrollIntoViewIfNeeded()
    await expect(list).toBeInViewport()
    expect(await form.evaluate((el) => el.scrollWidth - el.clientWidth)).toBeLessThanOrEqual(1)
  })
