// SPDX-License-Identifier: LicenseRef-AresRPG-Source-Available
// © 2026 Sceat — All rights reserved. See LICENSE.

import { expect, test } from '@playwright/test'

test('different rolls retain their exact tooltip and individual buy action', async ({ page }) => {
  await page.goto('/e2e/fixtures/marketplace.html')
  await page
    .locator('[data-marketplace-item-types]')
    .getByRole('button', { name: /^hat\b/i })
    .click()
  await page.locator('[data-marketplace-template-options] button').first().click()
  const rows = page.locator('[data-marketplace-listings] [data-marketplace-listing-row]')
  await expect(rows).toHaveCount(3)
  await expect(page.locator('[data-marketplace-lot-market]')).toHaveCount(0)
  await expect(page.locator('[data-marketplace-listings]')).not.toContainText('×1')
  await rows.nth(2).locator('[data-marketplace-item]').hover()
  await expect(page.getByRole('tooltip')).toBeVisible()
  await expect(page.getByRole('tooltip')).toHaveCSS('pointer-events', 'none')
  await expect(page.getByRole('tooltip')).not.toContainText('unavailable')
  await rows.nth(0).locator('[data-marketplace-item]').hover()
  await expect(page.getByRole('tooltip')).toContainText('+11')
  await expect(page.getByRole('tooltip')).toContainText('3 - 7 damages Fire')
  await page.mouse.move(0, 0)
  await rows.nth(1).locator('[data-marketplace-item]').focus()
  await expect(page.getByRole('tooltip')).toContainText('+27')
  await expect(page.locator('body')).not.toHaveAttribute('data-read-item')
  await rows.nth(1).getByRole('button', { name: 'Buy', exact: true }).click()
  await expect(page.locator('[data-pending-listing]')).toHaveAttribute('data-pending-listing', '0xitem2')
})

test('identical rolls retain backup offers and advance after the cheapest is removed', async ({ page }) => {
  await page.goto('/e2e/fixtures/marketplace.html?duplicates')
  await page
    .locator('[data-marketplace-item-types]')
    .getByRole('button', { name: /^hat\b/i })
    .click()
  await page.locator('[data-marketplace-template-options] button').first().click()
  const rows = page.locator('[data-marketplace-listings] [data-marketplace-listing-row]')
  await expect(rows).toHaveCount(3)
  await expect(rows.first().locator('[data-marketplace-item]')).toHaveAttribute('data-marketplace-item', '0xduplicate')
  await rows.first().locator('[data-marketplace-item]').hover()
  await expect(page.getByRole('tooltip')).toContainText('+11')
  await page.mouse.move(0, 0)
  await rows.first().getByRole('button', { name: 'Buy', exact: true }).click()
  await expect(page.locator('[data-pending-listing]')).toHaveAttribute('data-pending-listing', '0xduplicate')
  await page.evaluate(() => window.dispatchEvent(new Event('market-fixture-remove-cheapest')))
  await expect(rows).toHaveCount(3)
  await expect(rows.first().locator('[data-marketplace-item]')).toHaveAttribute('data-marketplace-item', '0xitem1')
})

test('barley to quartz to barley restores offers immediately and waits for fresh buy authority', async ({ page }) => {
  await page.goto('/e2e/fixtures/marketplace.html?bags&all-types&delayed')
  const options = page.locator('[data-marketplace-template-options]')
  const barley = options.getByRole('button', { name: 'Bag of Barley', exact: true })
  const quartz = options.getByRole('button', { name: 'Bag of Quartz', exact: true })
  const unit = page.locator('[data-marketplace-cheapest-lot="1"]')
  await expect(unit.getByRole('button', { name: 'Buy', exact: true })).toBeEnabled()
  const request = await page.locator('body').getAttribute('data-market-request')
  await barley.click()
  await expect(page.locator('body')).toHaveAttribute('data-market-request', request!)
  await quartz.click()
  await expect(unit.getByRole('button', { name: 'Buy', exact: true })).toBeEnabled()
  await barley.click()
  await expect(page.locator('[data-marketplace-listings]')).toHaveAttribute('aria-busy', 'true')
  await expect(unit).toContainText('1.10')
  await expect(unit.getByRole('button', { name: 'Buy', exact: true })).toBeDisabled()
  await expect(unit.getByRole('button', { name: 'Buy', exact: true })).toBeEnabled()
  await expect(page.locator('[data-marketplace-listings]')).toHaveAttribute('aria-busy', 'false')
})
