import { expect, test } from '@playwright/test'

test.use({ hasTouch: true })
test('mobile character dropdown and compact map use the real actions', async ({ page }) => {
  await page.setViewportSize({ width: 844, height: 390 })
  await page.goto('/e2e/fixtures/ui_world_hud.html?mobile')
  await expect(page.locator('.aui-minimap')).toBeHidden()
  const trigger = page.locator('.character-switcher-trigger')
  await expect(trigger.locator('svg')).toBeVisible()
  await expect(page.locator('.world-map-trigger svg')).toBeVisible()
  await trigger.click()
  await expect(page.locator('[data-character-tabs]')).toBeVisible()
  await page.locator('[data-character-tab="character-1"]').click()
  await expect(page.locator('[data-character-tabs]')).toBeHidden()
  await trigger.click()
  await page.keyboard.press('Escape')
  await expect(page.locator('[data-character-tabs]')).toBeHidden()
  await expect(page.locator('dialog[open]')).toHaveCount(0)
  await page.locator('.world-map-trigger').click()
  await expect(page.locator('.aui-map-interaction')).toBeVisible()
})
