// SPDX-License-Identifier: LicenseRef-AresRPG-Source-Available
// © 2026 Sceat — All rights reserved. See LICENSE.

import { expect, test } from '@playwright/test'
import type {} from '../fixtures/adventure_quests.tsx'

for (const victory of [false, true])
  test(`the local quest ends in rebirth and login after boss ${victory ? 'victory' : 'defeat'}`, async ({ page }) => {
    await page.goto(`/e2e/fixtures/adventure_quests.html${victory ? '?victory' : ''}`)
    const heard = (source: string) =>
      page.evaluate((path) => window.adventure_audio.filter((record) => record.source === path), source)
    const quests = () => heard('/sound_effect/quest_completed.aac').then((records) => records.length)
    const levels = () => heard('/sound_effect/level_up.ogg')
    await expect(page.locator('[data-character-tab="adventure_senshi"]')).toContainText('199')
    await expect(page.locator('.journey-panel--compact .journey-art')).toBeVisible()
    await page.locator('[data-win]').click()
    await expect(page.locator('dialog[open]')).toContainText('200')
    await expect(page.locator('.fe-stage')).toBeAttached()
    await expect.poll(quests).toBe(1)
    await expect.poll(levels).toEqual([{ source: '/sound_effect/level_up.ogg', volume: 0.55 }])
    await page.getByRole('button', { name: 'Later', exact: true }).click()
    await expect(page.locator('dialog[open]')).toHaveCount(0)
    await page.getByRole('button', { name: 'Continue', exact: true }).click()
    // The normal inventory confirmation owns quest completion; staging and partial commits do not.
    const equipment = page.locator('dialog[open]')
    await expect(equipment.locator('[data-equipment-quest]')).toContainText('Sui transaction')
    const rewards = equipment.locator('[data-selection-id]')
    await expect(rewards.first()).toBeVisible()
    await rewards.first().dblclick()
    await equipment.getByRole('button', { name: 'Accept', exact: true }).click()
    expect(await page.evaluate(() => window.adventure_equipped())).toBe(false)
    expect(await quests()).toBe(1)
    while (await rewards.count()) await rewards.first().dblclick()
    expect(await page.evaluate(() => window.adventure_equipped())).toBe(false)
    await equipment.getByRole('button', { name: 'Accept', exact: true }).click()
    await expect.poll(() => page.evaluate(() => window.adventure_equipped())).toBe(true)
    await expect.poll(quests).toBe(2)
    await equipment.getByRole('button', { name: 'Close', exact: true }).first().click()
    await page.getByRole('button', { name: 'F Speak to Sceat' }).click()
    await expect(page.locator('[data-speech]')).toContainText('I’m Sceat')
    await page.keyboard.press('f')
    await expect(page.locator('[data-speech]')).toContainText('dangerous')
    await page.keyboard.press('f')
    await expect(page.locator('[data-speech]')).toContainText('relic')
    await page.keyboard.press('f')
    await page.keyboard.press('f')
    await expect(page.locator('[data-character-tab="adventure_sceat"]')).toHaveCount(0)
    await expect.poll(quests).toBe(3)
    await page.getByRole('button', { name: 'Invite Sceat', exact: true }).click({ button: 'right' })
    await page.getByRole('menuitem', { name: 'Invite to group', exact: true }).click()
    await expect(page.locator('[data-character-tab="adventure_sceat"]')).toBeVisible()
    await expect(page.locator('.world-social-dock .party-frame')).toBeVisible()
    await expect.poll(quests).toBe(4)
    await page.locator('[data-character-tab="adventure_sceat"]').click()
    await expect(page.locator('.journey-tracker .journey-copy')).toContainText('Select Senshi')
    await expect.poll(quests).toBe(5)
    await page.locator('[data-character-tab="adventure_senshi"]').click()
    await page.getByRole('switch').check()
    await expect(page.locator('.journey-tracker .journey-copy')).toContainText('The royal guard')
    await expect.poll(quests).toBe(6)
    await page.locator('.journey-tracker .journey-button').click()
    await expect(page.locator('dialog[open] .journey-checklist li')).toHaveCount(8)
    await page.locator('dialog[open]').getByRole('button', { name: 'Continue', exact: true }).click()
    expect(await quests()).toBe(6)
    await page.locator('[data-start]').click()
    await expect(page.locator('.world-social-dock .party-frame')).toBeVisible()
    await expect(page.locator('.world-social-dock .party-frame__member')).toHaveCount(2)
    await expect(page.getByRole('button', { name: 'Settings', exact: true })).toBeVisible()
    await page.locator('[data-win]').click()
    await expect.poll(quests).toBe(7)
    expect(await levels()).toHaveLength(1)
    await page.getByRole('button', { name: 'Continue', exact: true }).click()
    await expect(page.locator('.journey-tracker .journey-copy')).toContainText('Gobadoc')
    await page.locator('[data-boss]').click()
    const rebirth = page.getByRole('dialog', { name: 'You died of your wounds…', exact: true })
    await expect(rebirth.getByRole('heading', { name: 'You died of your wounds…' })).toBeVisible()
    await rebirth.locator('article').evaluate(async (node) => {
      await Promise.all(node.getAnimations().map((animation) => animation.finished))
    })
    await expect(rebirth).toContainText('Continue with Google to be reborn')
    await expect(rebirth.getByText(/You defeated Gobadoc/)).toHaveCount(victory ? 1 : 0)
    if (victory) await expect(rebirth).toContainText('his attack poisoned you')
    await page.keyboard.press('Escape')
    await expect(rebirth).toBeVisible()
    await expect.poll(quests).toBe(8)
    expect(await levels()).toHaveLength(1)
    expect((await heard('/sound_effect/quest_completed.aac')).every(({ volume }) => volume === 0.5)).toBe(true)
    await expect(page).toHaveURL(/adventure_quests\.html(?:\?victory)?$/)
    await rebirth.getByRole('button', { name: 'Continue with Google', exact: true }).click()
    await expect.poll(() => page.evaluate(() => window.adventure_auth())).toBe('google')
    await expect(rebirth).toBeVisible()
    await expect(page).toHaveURL(/adventure_quests\.html(?:\?victory)?$/)
    await expect(page.locator('[data-player-login]')).toHaveCount(0)
    await expect(page.getByText('Defeated by Gobadoc, the Goblin King.', { exact: true })).toHaveCount(0)
  })
