// SPDX-License-Identifier: LicenseRef-AresRPG-Source-Available
// © 2026 Sceat — All rights reserved. See LICENSE.
import { expect, test } from '@playwright/test'

test('tutorial tips are compact, non-blocking, and follow character modals', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/e2e/fixtures/ui_world_hud.html?tutorial')
  const tip = page.locator('.tutorial-tip')
  await expect(tip).toContainText('1 / 3')
  expect((await tip.boundingBox())!.width).toBeLessThanOrEqual(320)
  await expect(page.locator('[aria-modal="true"]')).toHaveCount(0)
  await tip.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(tip).toContainText('Your HUD')
  await tip.getByRole('button', { name: 'Skip tutorial' }).click()
  await expect(tip).toHaveCount(0)
  await page.getByRole('button', { name: 'Equipment', exact: true }).click()
  await expect(tip).toContainText('choose Equip')
  await expect.poll(() => tip.evaluate((node) => !!node.closest('dialog'))).toBe(true)
  await page.keyboard.press('Escape')
  await expect(tip).toHaveCount(0)
  await expect(page.locator('[data-character-panel="equipment"]')).toBeVisible()
})

test('mobile settings preserve the current tutorial step and only Reset restarts it', async ({ page }) => {
  await page.setViewportSize({ width: 844, height: 390 })
  await page.goto('/e2e/fixtures/ui_world_hud.html?tutorial&mobile')
  const tip = page.locator('.tutorial-tip')
  await expect(tip).toContainText('Find your way')
  await tip.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(tip).toContainText('Your HUD')
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  const settings = page.getByRole('dialog', { name: 'Settings', exact: true })
  await expect(tip).toHaveCount(0)
  await settings.getByRole('button', { name: 'Low', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(tip).toContainText('Your HUD')
  await expect(tip).toContainText('2 / 3')

  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await settings.getByRole('button', { name: 'Characters', exact: true }).click()
  await settings
    .locator('.aui-setting-row')
    .filter({ hasText: 'Tutorials' })
    .getByRole('button', { name: 'Reset', exact: true })
    .click()
  await page.keyboard.press('Escape')
  await expect(tip).toContainText('Find your way')
  await tip.getByRole('button', { name: 'Skip tutorial' }).click()
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await settings.getByRole('button', { name: 'High', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(tip).toHaveCount(0)
})
