// SPDX-License-Identifier: LicenseRef-AresRPG-Source-Available
// © 2026 Sceat — All rights reserved. See LICENSE.
// Vanilla block IDs extracted from Assets.zip BlockTypeLists
// Organized by gathering job category for the GatheringEditor picker

export type BlockEntry = { id: string; label: string }

// ─── Wood ───────────────────────────────────────────────────────────
// Trunk blocks are the primary harvestable wood types
export const WOOD_BLOCKS: BlockEntry[] = [
  { id: 'Wood_Amber_Trunk', label: 'Amber Trunk' },
  { id: 'Wood_Ash_Trunk', label: 'Ash Trunk' },
  { id: 'Wood_Aspen_Trunk', label: 'Aspen Trunk' },
  { id: 'Wood_Azure_Trunk', label: 'Azure Trunk' },
  { id: 'Wood_Bamboo_Trunk', label: 'Bamboo Trunk' },
  { id: 'Wood_Banyan_Trunk', label: 'Banyan Trunk' },
  { id: 'Wood_Beech_Trunk', label: 'Beech Trunk' },
  { id: 'Wood_Birch_Trunk', label: 'Birch Trunk' },
  { id: 'Wood_Bottletree_Trunk', label: 'Bottletree Trunk' },
  { id: 'Wood_Burnt_Trunk', label: 'Burnt Trunk' },
  { id: 'Wood_Camphor_Trunk', label: 'Camphor Trunk' },
  { id: 'Wood_Cedar_Trunk', label: 'Cedar Trunk' },
  { id: 'Wood_Crystal_Trunk', label: 'Crystal Trunk' },
  { id: 'Wood_Dry_Trunk', label: 'Dry Trunk' },
  { id: 'Wood_Fig_Blue_Trunk', label: 'Blue Fig Trunk' },
  { id: 'Wood_Fir_Trunk', label: 'Fir Trunk' },
  { id: 'Wood_Fire_Trunk', label: 'Fire Trunk' },
  { id: 'Wood_Gumboab_Trunk', label: 'Gumboab Trunk' },
  { id: 'Wood_Ice_Trunk', label: 'Ice Trunk' },
  { id: 'Wood_Jungle_Trunk', label: 'Jungle Trunk' },
  { id: 'Wood_Maple_Trunk', label: 'Maple Trunk' },
  { id: 'Wood_Oak_Trunk', label: 'Oak Trunk' },
  { id: 'Wood_Palm_Trunk', label: 'Palm Trunk' },
  { id: 'Wood_Palo_Trunk', label: 'Palo Trunk' },
  { id: 'Wood_Petrified_Trunk', label: 'Petrified Trunk' },
  { id: 'Wood_Poisoned_Trunk', label: 'Poisoned Trunk' },
  { id: 'Wood_Redwood_Trunk', label: 'Redwood Trunk' },
  { id: 'Wood_Sallow_Trunk', label: 'Sallow Trunk' },
  { id: 'Wood_Spiral_Trunk', label: 'Spiral Trunk' },
  { id: 'Wood_Stormbark_Trunk', label: 'Stormbark Trunk' },
  { id: 'Wood_Windwillow_Trunk', label: 'Windwillow Trunk' },
  { id: 'Wood_Wisteria_Wild_Trunk', label: 'Wild Wisteria Trunk' },
  // Roots
  { id: 'Wood_Amber_Roots', label: 'Amber Roots' },
  { id: 'Wood_Ash_Roots', label: 'Ash Roots' },
  { id: 'Wood_Aspen_Roots', label: 'Aspen Roots' },
  { id: 'Wood_Azure_Roots', label: 'Azure Roots' },
  { id: 'Wood_Banyan_Roots', label: 'Banyan Roots' },
  { id: 'Wood_Beech_Roots', label: 'Beech Roots' },
  { id: 'Wood_Birch_Roots', label: 'Birch Roots' },
  { id: 'Wood_Bottletree_Roots', label: 'Bottletree Roots' },
  { id: 'Wood_Burnt_Roots', label: 'Burnt Roots' },
  { id: 'Wood_Camphor_Roots', label: 'Camphor Roots' },
  { id: 'Wood_Cedar_Roots', label: 'Cedar Roots' },
  { id: 'Wood_Crystal_Roots', label: 'Crystal Roots' },
  { id: 'Wood_Dry_Roots', label: 'Dry Roots' },
  { id: 'Wood_Fig_Blue_Roots', label: 'Blue Fig Roots' },
  { id: 'Wood_Fir_Roots', label: 'Fir Roots' },
  { id: 'Wood_Gnarled_Roots', label: 'Gnarled Roots' },
  { id: 'Wood_Gumboab_Roots', label: 'Gumboab Roots' },
  { id: 'Wood_Jungle_Roots', label: 'Jungle Roots' },
  { id: 'Wood_Maple_Roots', label: 'Maple Roots' },
  { id: 'Wood_Oak_Roots', label: 'Oak Roots' },
  { id: 'Wood_Palm_Roots', label: 'Palm Roots' },
  { id: 'Wood_Palo_Roots', label: 'Palo Roots' },
  { id: 'Wood_Petrified_Roots', label: 'Petrified Roots' },
  { id: 'Wood_Poisoned_Roots', label: 'Poisoned Roots' },
  { id: 'Wood_Redwood_Roots', label: 'Redwood Roots' },
  { id: 'Wood_Sallow_Roots', label: 'Sallow Roots' },
  { id: 'Wood_Spiral_Roots', label: 'Spiral Roots' },
  { id: 'Wood_Stormbark_Roots', label: 'Stormbark Roots' },
  { id: 'Wood_Windwillow_Roots', label: 'Windwillow Roots' },
  { id: 'Wood_Wisteria_Wild_Roots', label: 'Wild Wisteria Roots' },
  // Full trunks
  { id: 'Wood_Amber_Trunk_Full', label: 'Amber Full Trunk' },
  { id: 'Wood_Ash_Trunk_Full', label: 'Ash Full Trunk' },
  { id: 'Wood_Aspen_Trunk_Full', label: 'Aspen Full Trunk' },
  { id: 'Wood_Azure_Trunk_Full', label: 'Azure Full Trunk' },
  { id: 'Wood_Banyan_Trunk_Full', label: 'Banyan Full Trunk' },
  { id: 'Wood_Beech_Trunk_Full', label: 'Beech Full Trunk' },
  { id: 'Wood_Birch_Trunk_Full', label: 'Birch Full Trunk' },
  { id: 'Wood_Bottletree_Trunk_Full', label: 'Bottletree Full Trunk' },
  { id: 'Wood_Burnt_Trunk_Full', label: 'Burnt Full Trunk' },
  { id: 'Wood_Camphor_Trunk_Full', label: 'Camphor Full Trunk' },
  { id: 'Wood_Cedar_Trunk_Full', label: 'Cedar Full Trunk' },
  { id: 'Wood_Crystal_Trunk_Full', label: 'Crystal Full Trunk' },
  { id: 'Wood_Dry_Trunk_Full', label: 'Dry Full Trunk' },
  { id: 'Wood_Fig_Blue_Trunk_Full', label: 'Blue Fig Full Trunk' },
  { id: 'Wood_Fir_Trunk_Full', label: 'Fir Full Trunk' },
  { id: 'Wood_Fire_Trunk_Full', label: 'Fire Full Trunk' },
  { id: 'Wood_Gumboab_Trunk_Full', label: 'Gumboab Full Trunk' },
  { id: 'Wood_Jungle_Trunk_Full', label: 'Jungle Full Trunk' },
  { id: 'Wood_Maple_Trunk_Full', label: 'Maple Full Trunk' },
  { id: 'Wood_Oak_Trunk_Full', label: 'Oak Full Trunk' },
  { id: 'Wood_Palm_Trunk_Full', label: 'Palm Full Trunk' },
  { id: 'Wood_Palo_Trunk_Full', label: 'Palo Full Trunk' },
  { id: 'Wood_Petrified_Trunk_Full', label: 'Petrified Full Trunk' },
  { id: 'Wood_Poisoned_Trunk_Full', label: 'Poisoned Full Trunk' },
  { id: 'Wood_Redwood_Trunk_Full', label: 'Redwood Full Trunk' },
  { id: 'Wood_Sallow_Trunk_Full', label: 'Sallow Full Trunk' },
  { id: 'Wood_Spiral_Trunk_Full', label: 'Spiral Full Trunk' },
  { id: 'Wood_Stormbark_Trunk_Full', label: 'Stormbark Full Trunk' },
  { id: 'Wood_Windwillow_Trunk_Full', label: 'Windwillow Full Trunk' },
  { id: 'Wood_Wisteria_Wild_Trunk_Full', label: 'Wild Wisteria Full Trunk' },
  // Branches
  { id: 'Wood_Amber_Branch_Long', label: 'Amber Branch Long' },
  { id: 'Wood_Amber_Branch_Short', label: 'Amber Branch Short' },
  { id: 'Wood_Amber_Branch_Corner', label: 'Amber Branch Corner' },
  { id: 'Wood_Ash_Branch_Long', label: 'Ash Branch Long' },
  { id: 'Wood_Ash_Branch_Short', label: 'Ash Branch Short' },
  { id: 'Wood_Ash_Branch_Corner', label: 'Ash Branch Corner' },
  { id: 'Wood_Aspen_Branch_Long', label: 'Aspen Branch Long' },
  { id: 'Wood_Aspen_Branch_Short', label: 'Aspen Branch Short' },
  { id: 'Wood_Aspen_Branch_Corner', label: 'Aspen Branch Corner' },
  { id: 'Wood_Azure_Branch_Long', label: 'Azure Branch Long' },
  { id: 'Wood_Azure_Branch_Short', label: 'Azure Branch Short' },
  { id: 'Wood_Azure_Branch_Corner', label: 'Azure Branch Corner' },
  { id: 'Wood_Bamboo_Branch_Long', label: 'Bamboo Branch Long' },
  { id: 'Wood_Banyan_Branch_Long', label: 'Banyan Branch Long' },
  { id: 'Wood_Banyan_Branch_Short', label: 'Banyan Branch Short' },
  { id: 'Wood_Banyan_Branch_Corner', label: 'Banyan Branch Corner' },
  { id: 'Wood_Beech_Branch_Long', label: 'Beech Branch Long' },
  { id: 'Wood_Beech_Branch_Short', label: 'Beech Branch Short' },
  { id: 'Wood_Beech_Branch_Corner', label: 'Beech Branch Corner' },
  { id: 'Wood_Birch_Branch_Long', label: 'Birch Branch Long' },
  { id: 'Wood_Birch_Branch_Short', label: 'Birch Branch Short' },
  { id: 'Wood_Birch_Branch_Corner', label: 'Birch Branch Corner' },
  { id: 'Wood_Bottletree_Branch_Long', label: 'Bottletree Branch Long' },
  { id: 'Wood_Bottletree_Branch_Short', label: 'Bottletree Branch Short' },
  { id: 'Wood_Bottletree_Branch_Corner', label: 'Bottletree Branch Corner' },
  { id: 'Wood_Burnt_Branch_Long', label: 'Burnt Branch Long' },
  { id: 'Wood_Burnt_Branch_Short', label: 'Burnt Branch Short' },
  { id: 'Wood_Burnt_Branch_Corner', label: 'Burnt Branch Corner' },
  { id: 'Wood_Camphor_Branch_Long', label: 'Camphor Branch Long' },
  { id: 'Wood_Camphor_Branch_Short', label: 'Camphor Branch Short' },
  { id: 'Wood_Camphor_Branch_Corner', label: 'Camphor Branch Corner' },
  { id: 'Wood_Cedar_Branch_Long', label: 'Cedar Branch Long' },
  { id: 'Wood_Cedar_Branch_Short', label: 'Cedar Branch Short' },
  { id: 'Wood_Cedar_Branch_Corner', label: 'Cedar Branch Corner' },
  { id: 'Wood_Crystal_Branch_Long', label: 'Crystal Branch Long' },
  { id: 'Wood_Crystal_Branch_Short', label: 'Crystal Branch Short' },
  { id: 'Wood_Crystal_Branch_Corner', label: 'Crystal Branch Corner' },
  { id: 'Wood_Dry_Branch_Long', label: 'Dry Branch Long' },
  { id: 'Wood_Dry_Branch_Short', label: 'Dry Branch Short' },
  { id: 'Wood_Dry_Branch_Corner', label: 'Dry Branch Corner' },
  { id: 'Wood_Fig_Blue_Branch_Long', label: 'Blue Fig Branch Long' },
  { id: 'Wood_Fig_Blue_Branch_Short', label: 'Blue Fig Branch Short' },
  { id: 'Wood_Fig_Blue_Branch_Corner', label: 'Blue Fig Branch Corner' },
  { id: 'Wood_Fir_Branch_Long', label: 'Fir Branch Long' },
  { id: 'Wood_Fir_Branch_Short', label: 'Fir Branch Short' },
  { id: 'Wood_Fir_Branch_Corner', label: 'Fir Branch Corner' },
  { id: 'Wood_Fire_Branch_Long', label: 'Fire Branch Long' },
  { id: 'Wood_Fire_Branch_Short', label: 'Fire Branch Short' },
  { id: 'Wood_Fire_Branch_Corner', label: 'Fire Branch Corner' },
  { id: 'Wood_Gumboab_Branch_Long', label: 'Gumboab Branch Long' },
  { id: 'Wood_Gumboab_Branch_Short', label: 'Gumboab Branch Short' },
  { id: 'Wood_Gumboab_Branch_Corner', label: 'Gumboab Branch Corner' },
  { id: 'Wood_Jungle_Branch_Long', label: 'Jungle Branch Long' },
  { id: 'Wood_Jungle_Branch_Short', label: 'Jungle Branch Short' },
  { id: 'Wood_Jungle_Branch_Corner', label: 'Jungle Branch Corner' },
  { id: 'Wood_Maple_Branch_Long', label: 'Maple Branch Long' },
  { id: 'Wood_Maple_Branch_Short', label: 'Maple Branch Short' },
  { id: 'Wood_Maple_Branch_Corner', label: 'Maple Branch Corner' },
  { id: 'Wood_Oak_Branch_Long', label: 'Oak Branch Long' },
  { id: 'Wood_Oak_Branch_Short', label: 'Oak Branch Short' },
  { id: 'Wood_Oak_Branch_Corner', label: 'Oak Branch Corner' },
  { id: 'Wood_Palm_Branch_Long', label: 'Palm Branch Long' },
  { id: 'Wood_Palm_Branch_Short', label: 'Palm Branch Short' },
  { id: 'Wood_Palm_Branch_Corner', label: 'Palm Branch Corner' },
  { id: 'Wood_Palo_Branch_Long', label: 'Palo Branch Long' },
  { id: 'Wood_Palo_Branch_Short', label: 'Palo Branch Short' },
  { id: 'Wood_Palo_Branch_Corner', label: 'Palo Branch Corner' },
  { id: 'Wood_Petrified_Branch_Long', label: 'Petrified Branch Long' },
  { id: 'Wood_Petrified_Branch_Short', label: 'Petrified Branch Short' },
  { id: 'Wood_Petrified_Branch_Corner', label: 'Petrified Branch Corner' },
  { id: 'Wood_Poisoned_Branch_Long', label: 'Poisoned Branch Long' },
  { id: 'Wood_Poisoned_Branch_Short', label: 'Poisoned Branch Short' },
  { id: 'Wood_Poisoned_Branch_Corner', label: 'Poisoned Branch Corner' },
  { id: 'Wood_Redwood_Branch_Long', label: 'Redwood Branch Long' },
  { id: 'Wood_Redwood_Branch_Short', label: 'Redwood Branch Short' },
  { id: 'Wood_Redwood_Branch_Corner', label: 'Redwood Branch Corner' },
  { id: 'Wood_Sallow_Branch_Long', label: 'Sallow Branch Long' },
  { id: 'Wood_Sallow_Branch_Short', label: 'Sallow Branch Short' },
  { id: 'Wood_Sallow_Branch_Corner', label: 'Sallow Branch Corner' },
  { id: 'Wood_Spiral_Branch_Long', label: 'Spiral Branch Long' },
  { id: 'Wood_Spiral_Branch_Short', label: 'Spiral Branch Short' },
  { id: 'Wood_Spiral_Branch_Corner', label: 'Spiral Branch Corner' },
  { id: 'Wood_Stormbark_Branch_Long', label: 'Stormbark Branch Long' },
  { id: 'Wood_Stormbark_Branch_Short', label: 'Stormbark Branch Short' },
  { id: 'Wood_Stormbark_Branch_Corner', label: 'Stormbark Branch Corner' },
  { id: 'Wood_Windwillow_Branch_Long', label: 'Windwillow Branch Long' },
  { id: 'Wood_Windwillow_Branch_Short', label: 'Windwillow Branch Short' },
  { id: 'Wood_Windwillow_Branch_Corner', label: 'Windwillow Branch Corner' },
  { id: 'Wood_Wisteria_Wild_Branch_Long', label: 'Wild Wisteria Branch Long' },
  { id: 'Wood_Wisteria_Wild_Branch_Short', label: 'Wild Wisteria Branch Short' },
  { id: 'Wood_Wisteria_Wild_Branch_Corner', label: 'Wild Wisteria Branch Corner' },
]

// ─── Ore (Miner) ────────────────────────────────────────────────────
export const ORE_BLOCKS: BlockEntry[] = [
  { id: 'Ore_Adamantite_Basalt', label: 'Adamantite (Basalt)' },
  { id: 'Ore_Adamantite_Shale', label: 'Adamantite (Shale)' },
  { id: 'Ore_Adamantite_Slate', label: 'Adamantite (Slate)' },
  { id: 'Ore_Adamantite_Stone', label: 'Adamantite (Stone)' },
  { id: 'Ore_Adamantite_Volcanic', label: 'Adamantite (Volcanic)' },
  { id: 'Ore_Cobalt_Basalt', label: 'Cobalt (Basalt)' },
  { id: 'Ore_Cobalt_Sandstone', label: 'Cobalt (Sandstone)' },
  { id: 'Ore_Cobalt_Shale', label: 'Cobalt (Shale)' },
  { id: 'Ore_Cobalt_Slate', label: 'Cobalt (Slate)' },
  { id: 'Ore_Cobalt_Stone', label: 'Cobalt (Stone)' },
  { id: 'Ore_Cobalt_Volcanic', label: 'Cobalt (Volcanic)' },
  { id: 'Ore_Copper_Basalt', label: 'Copper (Basalt)' },
  { id: 'Ore_Copper_Sandstone', label: 'Copper (Sandstone)' },
  { id: 'Ore_Copper_Shale', label: 'Copper (Shale)' },
  { id: 'Ore_Copper_Stone', label: 'Copper (Stone)' },
  { id: 'Ore_Copper_Volcanic', label: 'Copper (Volcanic)' },
  { id: 'Ore_Gold_Basalt', label: 'Gold (Basalt)' },
  { id: 'Ore_Gold_Sandstone', label: 'Gold (Sandstone)' },
  { id: 'Ore_Gold_Shale', label: 'Gold (Shale)' },
  { id: 'Ore_Gold_Stone', label: 'Gold (Stone)' },
  { id: 'Ore_Gold_Volcanic', label: 'Gold (Volcanic)' },
  { id: 'Ore_Iron_Basalt', label: 'Iron (Basalt)' },
  { id: 'Ore_Iron_Sandstone', label: 'Iron (Sandstone)' },
  { id: 'Ore_Iron_Shale', label: 'Iron (Shale)' },
  { id: 'Ore_Iron_Slate', label: 'Iron (Slate)' },
  { id: 'Ore_Iron_Stone', label: 'Iron (Stone)' },
  { id: 'Ore_Iron_Volcanic', label: 'Iron (Volcanic)' },
  { id: 'Ore_Mithril_Basalt', label: 'Mithril (Basalt)' },
  { id: 'Ore_Mithril_Magma', label: 'Mithril (Magma)' },
  { id: 'Ore_Mithril_Slate', label: 'Mithril (Slate)' },
  { id: 'Ore_Mithril_Stone', label: 'Mithril (Stone)' },
  { id: 'Ore_Mithril_Volcanic', label: 'Mithril (Volcanic)' },
  { id: 'Ore_Onyxium_Basalt', label: 'Onyxium (Basalt)' },
  { id: 'Ore_Onyxium_Sandstone', label: 'Onyxium (Sandstone)' },
  { id: 'Ore_Onyxium_Shale', label: 'Onyxium (Shale)' },
  { id: 'Ore_Onyxium_Stone', label: 'Onyxium (Stone)' },
  { id: 'Ore_Onyxium_Volcanic', label: 'Onyxium (Volcanic)' },
  { id: 'Ore_Silver_Basalt', label: 'Silver (Basalt)' },
  { id: 'Ore_Silver_Sandstone', label: 'Silver (Sandstone)' },
  { id: 'Ore_Silver_Shale', label: 'Silver (Shale)' },
  { id: 'Ore_Silver_Slate', label: 'Silver (Slate)' },
  { id: 'Ore_Silver_Stone', label: 'Silver (Stone)' },
  { id: 'Ore_Silver_Volcanic', label: 'Silver (Volcanic)' },
  { id: 'Ore_Thorium_Basalt', label: 'Thorium (Basalt)' },
  { id: 'Ore_Thorium_Sandstone', label: 'Thorium (Sandstone)' },
  { id: 'Ore_Thorium_Shale', label: 'Thorium (Shale)' },
  { id: 'Ore_Thorium_Stone', label: 'Thorium (Stone)' },
  { id: 'Ore_Thorium_Volcanic', label: 'Thorium (Volcanic)' },
  // Rock types
  { id: 'Rock_Stone', label: 'Stone' },
  { id: 'Rock_Stone_Mossy', label: 'Mossy Stone' },
  { id: 'Rock_Shale', label: 'Shale' },
  { id: 'Rock_Slate', label: 'Slate' },
  { id: 'Rock_Quartzite', label: 'Quartzite' },
  { id: 'Rock_Sandstone', label: 'Sandstone' },
  { id: 'Rock_Sandstone_Red', label: 'Red Sandstone' },
  { id: 'Rock_Sandstone_White', label: 'White Sandstone' },
  { id: 'Rock_Basalt', label: 'Basalt' },
  { id: 'Rock_Volcanic', label: 'Volcanic' },
  { id: 'Rock_Marble', label: 'Marble' },
  { id: 'Rock_Calcite', label: 'Calcite' },
  { id: 'Rock_Aqua', label: 'Aqua Rock' },
  { id: 'Rock_Chalk', label: 'Chalk' },
  { id: 'Rock_Bedrock', label: 'Bedrock' },
  { id: 'Rock_Salt', label: 'Salt' },
  // Gems
  { id: 'Rock_Gem_Diamond', label: 'Diamond' },
  { id: 'Rock_Gem_Emerald', label: 'Emerald' },
  { id: 'Rock_Gem_Ruby', label: 'Ruby' },
  { id: 'Rock_Gem_Sapphire', label: 'Sapphire' },
  { id: 'Rock_Gem_Topaz', label: 'Topaz' },
  { id: 'Rock_Gem_Voidstone', label: 'Voidstone' },
  { id: 'Rock_Gem_Zephyr', label: 'Zephyr' },
]

// ─── Plant (Herbalist) ──────────────────────────────────────────────
export const PLANT_BLOCKS: BlockEntry[] = [
  // Crops
  { id: 'Plant_Crop_Wheat_Block', label: 'Wheat' },
  { id: 'Plant_Wheat_Mature', label: 'Mature Wheat' },
  { id: 'Plant_Crop_Wheat_Stage_4_Burnt', label: 'Burnt Wheat' },
  { id: 'Plant_Crop_Rice_Block', label: 'Rice' },
  { id: 'Plant_Crop_Corn_Block', label: 'Corn' },
  { id: 'Plant_Crop_Cotton_Block', label: 'Cotton' },
  { id: 'Plant_Crop_Potato_Block', label: 'Potato' },
  { id: 'Plant_Crop_Carrot_Block', label: 'Carrot' },
  { id: 'Plant_Crop_Tomato_Block', label: 'Tomato' },
  { id: 'Plant_Crop_Turnip_Block', label: 'Turnip' },
  { id: 'Plant_Crop_Onion_Block', label: 'Onion' },
  { id: 'Plant_Crop_Lettuce_Block', label: 'Lettuce' },
  { id: 'Plant_Crop_Pumpkin_Block', label: 'Pumpkin' },
  { id: 'Plant_Crop_Chilli_Block', label: 'Chilli' },
  { id: 'Plant_Crop_Cauliflower_Block', label: 'Cauliflower' },
  { id: 'Plant_Crop_Aubergine_Block', label: 'Aubergine' },
  { id: 'Plant_Crop_Berry_Block', label: 'Berry' },
  { id: 'Plant_Crop_Berry_Wet_Block', label: 'Wet Berry' },
  { id: 'Plant_Crop_Berry_Winter_Block', label: 'Winter Berry' },
  { id: 'Plant_Crop_Apple_Block', label: 'Apple' },
  // Potion crops
  { id: 'Plant_Crop_Health1_Block', label: 'Health Herb 1' },
  { id: 'Plant_Crop_Health2_Block', label: 'Health Herb 2' },
  { id: 'Plant_Crop_Health3_Block', label: 'Health Herb 3' },
  { id: 'Plant_Crop_Mana1_Block', label: 'Mana Herb 1' },
  { id: 'Plant_Crop_Mana2_Block', label: 'Mana Herb 2' },
  { id: 'Plant_Crop_Mana3_Block', label: 'Mana Herb 3' },
  { id: 'Plant_Crop_Stamina1_Block', label: 'Stamina Herb 1' },
  { id: 'Plant_Crop_Stamina2_Block', label: 'Stamina Herb 2' },
  { id: 'Plant_Crop_Stamina3_Block', label: 'Stamina Herb 3' },
  // Mushrooms
  { id: 'Plant_Crop_Mushroom_Block', label: 'Mushroom' },
  { id: 'Plant_Crop_Mushroom_Common_Brown', label: 'Brown Mushroom' },
  { id: 'Plant_Crop_Mushroom_Common_Blue', label: 'Blue Mushroom' },
  { id: 'Plant_Crop_Mushroom_Common_Lime', label: 'Lime Mushroom' },
  { id: 'Plant_Crop_Mushroom_Cap_Red', label: 'Red Cap Mushroom' },
  { id: 'Plant_Crop_Mushroom_Cap_Green', label: 'Green Cap Mushroom' },
  { id: 'Plant_Crop_Mushroom_Cap_Brown', label: 'Brown Cap Mushroom' },
  { id: 'Plant_Crop_Mushroom_Cap_White', label: 'White Cap Mushroom' },
  { id: 'Plant_Crop_Mushroom_Cap_Poison', label: 'Poison Cap Mushroom' },
  { id: 'Plant_Crop_Mushroom_Flatcap_Green', label: 'Green Flatcap Mushroom' },
  { id: 'Plant_Crop_Mushroom_Flatcap_Blue', label: 'Blue Flatcap Mushroom' },
  { id: 'Plant_Crop_Mushroom_Glowing_Blue', label: 'Glowing Blue Mushroom' },
  { id: 'Plant_Crop_Mushroom_Glowing_Green', label: 'Glowing Green Mushroom' },
  { id: 'Plant_Crop_Mushroom_Glowing_Orange', label: 'Glowing Orange Mushroom' },
  { id: 'Plant_Crop_Mushroom_Glowing_Purple', label: 'Glowing Purple Mushroom' },
  { id: 'Plant_Crop_Mushroom_Glowing_Red', label: 'Glowing Red Mushroom' },
  { id: 'Plant_Crop_Mushroom_Glowing_Violet', label: 'Glowing Violet Mushroom' },
  { id: 'Plant_Crop_Mushroom_Shelve_Brown', label: 'Brown Shelf Mushroom' },
  { id: 'Plant_Crop_Mushroom_Shelve_Green', label: 'Green Shelf Mushroom' },
  { id: 'Plant_Crop_Mushroom_Shelve_Yellow', label: 'Yellow Shelf Mushroom' },
  { id: 'Plant_Crop_Mushroom_Boomshroom_Small', label: 'Small Boomshroom' },
  { id: 'Plant_Crop_Mushroom_Boomshroom_Large', label: 'Large Boomshroom' },
  // Flowers
  { id: 'Plant_Flower_Common_Blue', label: 'Blue Flower' },
  { id: 'Plant_Flower_Common_Red', label: 'Red Flower' },
  { id: 'Plant_Flower_Common_Yellow', label: 'Yellow Flower' },
  { id: 'Plant_Flower_Common_White', label: 'White Flower' },
  { id: 'Plant_Flower_Common_Pink', label: 'Pink Flower' },
  { id: 'Plant_Flower_Common_Purple', label: 'Purple Flower' },
  { id: 'Plant_Flower_Common_Orange', label: 'Orange Flower' },
  { id: 'Plant_Flower_Common_Violet', label: 'Violet Flower' },
  { id: 'Plant_Flower_Common_Cyan', label: 'Cyan Flower' },
  { id: 'Plant_Flower_Common_Lime', label: 'Lime Flower' },
  { id: 'Plant_Flower_Common_Grey', label: 'Grey Flower' },
  { id: 'Plant_Flower_Common_Poisoned', label: 'Poisoned Flower' },
  { id: 'Plant_Flower_Common_Blue2', label: 'Blue Aloe' },
  { id: 'Plant_Flower_Common_Cyan2', label: 'Cyan Aloe' },
  { id: 'Plant_Flower_Common_Grey2', label: 'Grey Aloe' },
  { id: 'Plant_Flower_Common_Lime2', label: 'Lime Aloe' },
  { id: 'Plant_Flower_Common_Orange2', label: 'Orange Aloe' },
  { id: 'Plant_Flower_Common_Pink2', label: 'Pink Aloe' },
  { id: 'Plant_Flower_Common_Poisoned2', label: 'Poisoned Aloe' },
  { id: 'Plant_Flower_Common_Purple2', label: 'Purple Aloe' },
  { id: 'Plant_Flower_Common_Red2', label: 'Red Aloe' },
  { id: 'Plant_Flower_Common_Violet2', label: 'Violet Aloe' },
  { id: 'Plant_Flower_Common_White2', label: 'White Aloe' },
  { id: 'Plant_Flower_Common_Yellow2', label: 'Yellow Aloe' },
  { id: 'Plant_Flower_Orchid_Blue', label: 'Blue Orchid' },
  { id: 'Plant_Flower_Orchid_Red', label: 'Red Orchid' },
  { id: 'Plant_Flower_Orchid_Yellow', label: 'Yellow Orchid' },
  { id: 'Plant_Flower_Orchid_White', label: 'White Orchid' },
  { id: 'Plant_Flower_Orchid_Pink', label: 'Pink Orchid' },
  { id: 'Plant_Flower_Orchid_Purple', label: 'Purple Orchid' },
  { id: 'Plant_Flower_Orchid_Orange', label: 'Orange Orchid' },
  { id: 'Plant_Flower_Orchid_Cyan', label: 'Cyan Orchid' },
  { id: 'Plant_Flower_Orchid_Poisoned', label: 'Poisoned Orchid' },
  { id: 'Plant_Flower_Flax_Blue', label: 'Blue Flax' },
  { id: 'Plant_Flower_Flax_Yellow', label: 'Yellow Flax' },
  { id: 'Plant_Flower_Flax_White', label: 'White Flax' },
  { id: 'Plant_Flower_Flax_Pink', label: 'Pink Flax' },
  { id: 'Plant_Flower_Flax_Purple', label: 'Purple Flax' },
  { id: 'Plant_Flower_Flax_Orange', label: 'Orange Flax' },
  { id: 'Plant_Flower_Tall_Blue', label: 'Tall Blue Flower' },
  { id: 'Plant_Flower_Tall_Red', label: 'Tall Red Flower' },
  { id: 'Plant_Flower_Tall_Yellow', label: 'Tall Yellow Flower' },
  { id: 'Plant_Flower_Tall_Pink', label: 'Tall Pink Flower' },
  { id: 'Plant_Flower_Tall_Purple', label: 'Tall Purple Flower' },
  { id: 'Plant_Flower_Tall_Violet', label: 'Tall Violet Flower' },
  { id: 'Plant_Flower_Tall_Cyan', label: 'Tall Cyan Flower' },
  { id: 'Plant_Flower_Tall_Cyan2', label: 'Tall Cyan Flower 2' },
  { id: 'Plant_Flower_Hemlock', label: 'Hemlock' },
  { id: 'Plant_Flower_Poisoned_Orange', label: 'Poisoned Orange Flower' },
  { id: 'Plant_Flower_Bushy_Blue', label: 'Bushy Blue Flower' },
  { id: 'Plant_Flower_Bushy_Red', label: 'Bushy Red Flower' },
  { id: 'Plant_Flower_Bushy_Yellow', label: 'Bushy Yellow Flower' },
  { id: 'Plant_Flower_Bushy_White', label: 'Bushy White Flower' },
  { id: 'Plant_Flower_Bushy_Purple', label: 'Bushy Purple Flower' },
  { id: 'Plant_Flower_Bushy_Orange', label: 'Bushy Orange Flower' },
  { id: 'Plant_Flower_Bushy_Violet', label: 'Bushy Violet Flower' },
  { id: 'Plant_Flower_Bushy_Cyan', label: 'Bushy Cyan Flower' },
  { id: 'Plant_Flower_Bushy_Green', label: 'Bushy Green Flower' },
  { id: 'Plant_Flower_Bushy_Grey', label: 'Bushy Grey Flower' },
  { id: 'Plant_Flower_Bushy_Poisoned', label: 'Bushy Poisoned Flower' },
  // Fruits
  { id: 'Plant_Fruit_Apple', label: 'Apple' },
  { id: 'Plant_Fruit_Coconut', label: 'Coconut' },
  { id: 'Plant_Fruit_Mango', label: 'Mango' },
  { id: 'Plant_Fruit_Pinkberry', label: 'Pinkberry' },
  { id: 'Plant_Fruit_Azure', label: 'Azure Fruit' },
  { id: 'Plant_Fruit_Spiral', label: 'Spiral Fruit' },
  { id: 'Plant_Fruit_Windwillow', label: 'Windwillow Fruit' },
  // Herbs / misc
  { id: 'Plant_Lavender_Stage_0', label: 'Lavender' },
  { id: 'Plant_Sunflower_Stage_0', label: 'Sunflower' },
  { id: 'Plant_Hay_Bundle', label: 'Hay Bundle' },
  { id: 'Plant_Barnacles', label: 'Barnacles' },
  // Ferns
  { id: 'Plant_Fern', label: 'Fern' },
  { id: 'Plant_Fern_Arid', label: 'Arid Fern' },
  { id: 'Plant_Fern_Forest', label: 'Forest Fern' },
  { id: 'Plant_Fern_Jungle', label: 'Jungle Fern' },
  { id: 'Plant_Fern_Tall', label: 'Tall Fern' },
  { id: 'Plant_Fern_Wet_Big', label: 'Big Wet Fern' },
  { id: 'Plant_Fern_Winter', label: 'Winter Fern' },
  // Cacti
  { id: 'Plant_Cactus_1', label: 'Cactus 1' },
  { id: 'Plant_Cactus_2', label: 'Cactus 2' },
  { id: 'Plant_Cactus_3', label: 'Cactus 3' },
  { id: 'Plant_Cactus_Ball_1', label: 'Ball Cactus' },
  { id: 'Plant_Cactus_Flat_1', label: 'Flat Cactus 1' },
  { id: 'Plant_Cactus_Flat_2', label: 'Flat Cactus 2' },
  { id: 'Plant_Cactus_Flat_3', label: 'Flat Cactus 3' },
  { id: 'Plant_Cactus_Flower', label: 'Cactus Flower' },
  // Leaves
  { id: 'Plant_Leaves_Oak', label: 'Oak Leaves' },
  { id: 'Plant_Leaves_Birch', label: 'Birch Leaves' },
  { id: 'Plant_Leaves_Maple', label: 'Maple Leaves' },
  { id: 'Plant_Leaves_Cedar', label: 'Cedar Leaves' },
  { id: 'Plant_Leaves_Fir', label: 'Fir Leaves' },
  { id: 'Plant_Leaves_Palm', label: 'Palm Leaves' },
  { id: 'Plant_Leaves_Jungle', label: 'Jungle Leaves' },
  { id: 'Plant_Leaves_Redwood', label: 'Redwood Leaves' },
  { id: 'Plant_Leaves_Ash', label: 'Ash Leaves' },
  { id: 'Plant_Leaves_Aspen', label: 'Aspen Leaves' },
  { id: 'Plant_Leaves_Azure', label: 'Azure Leaves' },
  { id: 'Plant_Leaves_Bamboo', label: 'Bamboo Leaves' },
  { id: 'Plant_Leaves_Banyan', label: 'Banyan Leaves' },
  { id: 'Plant_Leaves_Beech', label: 'Beech Leaves' },
  { id: 'Plant_Leaves_Crystal', label: 'Crystal Leaves' },
  { id: 'Plant_Leaves_Fire', label: 'Fire Leaves' },
  { id: 'Plant_Leaves_Camphor', label: 'Camphor Leaves' },
  { id: 'Plant_Leaves_Amber', label: 'Amber Leaves' },
]

// ─── Job-to-blocks mapping ──────────────────────────────────────────

export const GATHERABLE_BLOCKS: Record<string, BlockEntry[]> = {
  FARMER: PLANT_BLOCKS,
  MINER: ORE_BLOCKS,
  HERBALIST: PLANT_BLOCKS,
}

// Flat list with category for search across all blocks
export const ALL_GATHERABLE_BLOCKS = Object.entries(GATHERABLE_BLOCKS).flatMap(([category, blocks]) =>
  blocks.map((b) => ({ ...b, category }))
)

// ─── Soil ────────────────────────────────────────────────────────────
export const SOIL_BLOCKS: BlockEntry[] = [
  { id: 'Soil_Dirt', label: 'Dirt' },
  { id: 'Soil_Dirt_Burnt', label: 'Dirt Burnt' },
  { id: 'Soil_Dirt_Cold', label: 'Dirt Cold' },
  { id: 'Soil_Dirt_Dry', label: 'Dirt Dry' },
  { id: 'Soil_Dirt_Poisoned', label: 'Dirt Poisoned' },
  { id: 'Soil_Grass', label: 'Grass' },
  { id: 'Soil_Grass_Burnt', label: 'Grass Burnt' },
  { id: 'Soil_Grass_Cold', label: 'Grass Cold' },
  { id: 'Soil_Grass_Deep', label: 'Grass Deep' },
  { id: 'Soil_Grass_Dry', label: 'Grass Dry' },
  { id: 'Soil_Grass_Full', label: 'Grass Full' },
  { id: 'Soil_Grass_Sunny', label: 'Grass Sunny' },
  { id: 'Soil_Grass_Wet', label: 'Grass Wet' },
  { id: 'Soil_Gravel', label: 'Gravel' },
  { id: 'Soil_Gravel_Mossy', label: 'Gravel Mossy' },
  { id: 'Soil_Gravel_Sand', label: 'Gravel Sand' },
  { id: 'Soil_Gravel_Sand_Red', label: 'Gravel Sand Red' },
  { id: 'Soil_Gravel_Sand_White', label: 'Gravel Sand White' },
  { id: 'Soil_Pebbles', label: 'Pebbles' },
  { id: 'Soil_Pebbles_Frozen', label: 'Pebbles Frozen' },
  { id: 'Soil_Snow', label: 'Snow' },
  { id: 'Soil_Snow_Half', label: 'Snow Half' },
]

// ─── Rubble ──────────────────────────────────────────────────────────
export const RUBBLE_BLOCKS: BlockEntry[] = [
  { id: 'Rubble_Aqua', label: 'Aqua Rubble' },
  { id: 'Rubble_Aqua_Medium', label: 'Aqua Rubble Medium' },
  { id: 'Rubble_Basalt', label: 'Basalt Rubble' },
  { id: 'Rubble_Basalt_Medium', label: 'Basalt Rubble Medium' },
  { id: 'Rubble_Calcite', label: 'Calcite Rubble' },
  { id: 'Rubble_Calcite_Medium', label: 'Calcite Rubble Medium' },
  { id: 'Rubble_Ice', label: 'Ice Rubble' },
  { id: 'Rubble_Ice_Medium', label: 'Ice Rubble Medium' },
  { id: 'Rubble_Marble', label: 'Marble Rubble' },
  { id: 'Rubble_Marble_Medium', label: 'Marble Rubble Medium' },
  { id: 'Rubble_Quartzite', label: 'Quartzite Rubble' },
  { id: 'Rubble_Quartzite_Medium', label: 'Quartzite Rubble Medium' },
  { id: 'Rubble_Sandstone', label: 'Sandstone Rubble' },
  { id: 'Rubble_Sandstone_Medium', label: 'Sandstone Rubble Medium' },
  { id: 'Rubble_Sandstone_Red', label: 'Red Sandstone Rubble' },
  { id: 'Rubble_Sandstone_Red_Medium', label: 'Red Sandstone Rubble Medium' },
  { id: 'Rubble_Sandstone_White', label: 'White Sandstone Rubble' },
  { id: 'Rubble_Sandstone_White_Medium', label: 'White Sandstone Rubble Medium' },
  { id: 'Rubble_Shale', label: 'Shale Rubble' },
  { id: 'Rubble_Shale_Medium', label: 'Shale Rubble Medium' },
  { id: 'Rubble_Slate', label: 'Slate Rubble' },
  { id: 'Rubble_Slate_Medium', label: 'Slate Rubble Medium' },
  { id: 'Rubble_Stone', label: 'Stone Rubble' },
  { id: 'Rubble_Stone_Medium', label: 'Stone Rubble Medium' },
  { id: 'Rubble_Stone_Mossy', label: 'Mossy Stone Rubble' },
  { id: 'Rubble_Stone_Mossy_Medium', label: 'Mossy Stone Rubble Medium' },
  { id: 'Rubble_Volcanic', label: 'Volcanic Rubble' },
  { id: 'Rubble_Volcanic_Medium', label: 'Volcanic Rubble Medium' },
]

// ─── Deco ────────────────────────────────────────────────────────────
export const DECO_BLOCKS: BlockEntry[] = [
  { id: 'Deco_Bone_Ribs_Feran', label: 'Feran Bone Ribs' },
  { id: 'Deco_Bone_Skulls_Feran', label: 'Feran Bone Skulls' },
  { id: 'Deco_Bone_Skulls_Feran_Large', label: 'Feran Bone Skulls Large' },
  { id: 'Deco_Bone_Skulls_Feran_Wall', label: 'Feran Bone Skulls Wall' },
  { id: 'Deco_Bone_Skulls_Wall', label: 'Bone Skulls Wall' },
  { id: 'Deco_Coral_Shell', label: 'Coral Shell' },
  { id: 'Deco_Coral_Shell_Purple', label: 'Purple Coral Shell' },
  { id: 'Deco_Coral_Shell_Sanddollar', label: 'Sand Dollar' },
  { id: 'Deco_Coral_Shell_Swirly', label: 'Swirly Shell' },
  { id: 'Deco_Coral_Shell_Urchin', label: 'Sea Urchin' },
  { id: 'Deco_Nest', label: 'Nest' },
  { id: 'Deco_SpiderWeb', label: 'Spider Web' },
  { id: 'Deco_Starfish', label: 'Starfish' },
  { id: 'Deco_Trash', label: 'Trash' },
  { id: 'Deco_Trash_Pile_Large', label: 'Trash Pile Large' },
  { id: 'Deco_Trash_Pile_Small', label: 'Trash Pile Small' },
]

// ─── Furniture ───────────────────────────────────────────────────────
export const FURNITURE_BLOCKS: BlockEntry[] = [
  { id: 'Furniture_Ancient_Bed', label: 'Ancient Bed' },
  { id: 'Furniture_Crude_Bed', label: 'Crude Bed' },
  { id: 'Furniture_Desert_Bed', label: 'Desert Bed' },
  { id: 'Furniture_Feran_Bed', label: 'Feran Bed' },
  { id: 'Furniture_Frozen_Castle_Bed', label: 'Frozen Castle Bed' },
  { id: 'Furniture_Human_Ruins_Bed', label: 'Human Ruins Bed' },
  { id: 'Furniture_Jungle_Bed', label: 'Jungle Bed' },
  { id: 'Furniture_Kweebec_Bed', label: 'Kweebec Bed' },
  { id: 'Furniture_Lumberjack_Bed', label: 'Lumberjack Bed' },
  { id: 'Furniture_Royal_Magic_Bed', label: 'Royal Magic Bed' },
  { id: 'Furniture_Tavern_Bed', label: 'Tavern Bed' },
  { id: 'Furniture_Temple_Dark_Bed', label: 'Dark Temple Bed' },
  { id: 'Furniture_Temple_Emerald_Bed', label: 'Emerald Temple Bed' },
  { id: 'Furniture_Temple_Light_Bed', label: 'Light Temple Bed' },
  { id: 'Furniture_Village_Bed', label: 'Village Bed' },
  { id: 'Wooden_Trash_Can', label: 'Wooden Trash Can' },
]

// ─── Misc ────────────────────────────────────────────────────────────
export const MISC_BLOCKS: BlockEntry[] = [
  { id: 'Kweebec_Ancient', label: 'Kweebec Ancient' },
  { id: 'Plant_Barnacles', label: 'Barnacles' },
  { id: 'Plant_Boomshroom_Large', label: 'Boomshroom Large' },
  { id: 'Plant_Boomshroom_Small', label: 'Boomshroom Small' },
  { id: 'Plant_Bramble_Dead_Lavathorn', label: 'Lavathorn' },
  { id: 'Plant_Bramble_Dead_Twisted', label: 'Dead Twisted Bramble' },
  { id: 'Plant_Bramble_Dry_Magic', label: 'Magic Bramble' },
  { id: 'Plant_Bramble_Dry_Sandthorn', label: 'Sandthorn' },
  { id: 'Plant_Bramble_Dry_Twisted', label: 'Dry Twisted Bramble' },
  { id: 'Plant_Bramble_Moss_Twisted', label: 'Moss Twisted Bramble' },
  { id: 'Plant_Bramble_Winter', label: 'Winter Bramble' },
  { id: 'Plant_Bush', label: 'Bush' },
  { id: 'Plant_Bush_Arid', label: 'Arid Bush' },
  { id: 'Plant_Bush_Arid_Palm', label: 'Arid Palm Bush' },
  { id: 'Plant_Bush_Arid_Red', label: 'Arid Red Bush' },
  { id: 'Plant_Bush_Arid_Sharp', label: 'Arid Sharp Bush' },
  { id: 'Plant_Bush_Bramble', label: 'Bramble Bush' },
  { id: 'Plant_Bush_Crystal', label: 'Crystal Bush' },
  { id: 'Plant_Bush_Dead', label: 'Dead Bush' },
  { id: 'Plant_Bush_Dead_Hanging', label: 'Dead Hanging Bush' },
  { id: 'Plant_Bush_Dead_Tall', label: 'Dead Tall Bush' },
  { id: 'Plant_Bush_Dead_Twisted', label: 'Dead Twisted Bush' },
  { id: 'Plant_Bush_Green', label: 'Green Bush' },
  { id: 'Plant_Bush_Hanging', label: 'Hanging Bush' },
  { id: 'Plant_Bush_Jungle', label: 'Jungle Bush' },
  { id: 'Plant_Bush_Lush', label: 'Lush Bush' },
  { id: 'Plant_Bush_Wet', label: 'Wet Bush' },
  { id: 'Plant_Bush_Winter', label: 'Winter Bush' },
  { id: 'Plant_Bush_Winter_Red', label: 'Winter Red Bush' },
  { id: 'Plant_Bush_Winter_Sharp', label: 'Winter Sharp Bush' },
  { id: 'Plant_Bush_Winter_Snow', label: 'Winter Snow Bush' },
  { id: 'Plant_Coral_Block_Blue', label: 'Coral Block Blue' },
  { id: 'Plant_Coral_Block_Cyan', label: 'Coral Block Cyan' },
  { id: 'Plant_Coral_Block_Green', label: 'Coral Block Green' },
  { id: 'Plant_Coral_Block_Grey', label: 'Coral Block Grey' },
  { id: 'Plant_Coral_Block_Lime', label: 'Coral Block Lime' },
  { id: 'Plant_Coral_Block_Orange', label: 'Coral Block Orange' },
  { id: 'Plant_Coral_Block_Pink', label: 'Coral Block Pink' },
  { id: 'Plant_Coral_Block_Poison', label: 'Coral Block Poison' },
  { id: 'Plant_Coral_Block_Purple', label: 'Coral Block Purple' },
  { id: 'Plant_Coral_Block_Red', label: 'Coral Block Red' },
  { id: 'Plant_Coral_Block_Violet', label: 'Coral Block Violet' },
  { id: 'Plant_Coral_Block_White', label: 'Coral Block White' },
  { id: 'Plant_Coral_Block_Yellow', label: 'Coral Block Yellow' },
  { id: 'Plant_Coral_Bush_Blue', label: 'Coral Bush Blue' },
  { id: 'Plant_Coral_Bush_Cyan', label: 'Coral Bush Cyan' },
  { id: 'Plant_Coral_Bush_Green', label: 'Coral Bush Green' },
  { id: 'Plant_Coral_Bush_Grey', label: 'Coral Bush Grey' },
  { id: 'Plant_Coral_Bush_Lime', label: 'Coral Bush Lime' },
  { id: 'Plant_Coral_Bush_Orange', label: 'Coral Bush Orange' },
  { id: 'Plant_Coral_Bush_Pink', label: 'Coral Bush Pink' },
  { id: 'Plant_Coral_Bush_Poisoned', label: 'Coral Bush Poisoned' },
  { id: 'Plant_Coral_Bush_Purple', label: 'Coral Bush Purple' },
  { id: 'Plant_Coral_Bush_Red', label: 'Coral Bush Red' },
  { id: 'Plant_Coral_Bush_Violet', label: 'Coral Bush Violet' },
  { id: 'Plant_Coral_Bush_White', label: 'Coral Bush White' },
  { id: 'Plant_Coral_Bush_Yellow', label: 'Coral Bush Yellow' },
  { id: 'Plant_Coral_Model_Blue', label: 'Coral Model Blue' },
  { id: 'Plant_Coral_Model_Cyan', label: 'Coral Model Cyan' },
  { id: 'Plant_Coral_Model_Green', label: 'Coral Model Green' },
  { id: 'Plant_Coral_Model_Grey', label: 'Coral Model Grey' },
  { id: 'Plant_Coral_Model_Lime', label: 'Coral Model Lime' },
  { id: 'Plant_Coral_Model_Orange', label: 'Coral Model Orange' },
  { id: 'Plant_Coral_Model_Pink', label: 'Coral Model Pink' },
  { id: 'Plant_Coral_Model_Purple', label: 'Coral Model Purple' },
  { id: 'Plant_Coral_Model_Red', label: 'Coral Model Red' },
  { id: 'Plant_Coral_Model_Violet', label: 'Coral Model Violet' },
  { id: 'Plant_Coral_Model_White', label: 'Coral Model White' },
  { id: 'Plant_Coral_Model_Yellow', label: 'Coral Model Yellow' },
  { id: 'Plant_Crop_Health1', label: 'Health Potion Herb 1' },
  { id: 'Plant_Crop_Health2', label: 'Health Potion Herb 2' },
  { id: 'Plant_Crop_Health3', label: 'Health Potion Herb 3' },
  { id: 'Plant_Crop_Mana1', label: 'Mana Potion Herb 1' },
  { id: 'Plant_Crop_Mana2', label: 'Mana Potion Herb 2' },
  { id: 'Plant_Crop_Mana3', label: 'Mana Potion Herb 3' },
  { id: 'Plant_Crop_Mushroom_Block_Blue', label: 'Giant Mushroom Blue' },
  { id: 'Plant_Crop_Mushroom_Block_Blue_Branch', label: 'Giant Mushroom Blue Branch' },
  { id: 'Plant_Crop_Mushroom_Block_Blue_Mycelium', label: 'Giant Mushroom Blue Mycelium' },
  { id: 'Plant_Crop_Mushroom_Block_Blue_Trunk', label: 'Giant Mushroom Blue Trunk' },
  { id: 'Plant_Crop_Mushroom_Block_Brown', label: 'Giant Mushroom Brown' },
  { id: 'Plant_Crop_Mushroom_Block_Brown_Branch', label: 'Giant Mushroom Brown Branch' },
  { id: 'Plant_Crop_Mushroom_Block_Brown_Mycelium', label: 'Giant Mushroom Brown Mycelium' },
  { id: 'Plant_Crop_Mushroom_Block_Brown_Trunk', label: 'Giant Mushroom Brown Trunk' },
  { id: 'Plant_Crop_Mushroom_Block_Green', label: 'Giant Mushroom Green' },
  { id: 'Plant_Crop_Mushroom_Block_Green_Branch', label: 'Giant Mushroom Green Branch' },
  { id: 'Plant_Crop_Mushroom_Block_Green_Mycelium', label: 'Giant Mushroom Green Mycelium' },
  { id: 'Plant_Crop_Mushroom_Block_Green_Trunk', label: 'Giant Mushroom Green Trunk' },
  { id: 'Plant_Crop_Mushroom_Block_Purple', label: 'Giant Mushroom Purple' },
  { id: 'Plant_Crop_Mushroom_Block_Purple_Branch', label: 'Giant Mushroom Purple Branch' },
  { id: 'Plant_Crop_Mushroom_Block_Purple_Mycelium', label: 'Giant Mushroom Purple Mycelium' },
  { id: 'Plant_Crop_Mushroom_Block_Purple_Trunk', label: 'Giant Mushroom Purple Trunk' },
  { id: 'Plant_Crop_Mushroom_Block_Red', label: 'Giant Mushroom Red' },
  { id: 'Plant_Crop_Mushroom_Block_Red_Branch', label: 'Giant Mushroom Red Branch' },
  { id: 'Plant_Crop_Mushroom_Block_Red_Mycelium', label: 'Giant Mushroom Red Mycelium' },
  { id: 'Plant_Crop_Mushroom_Block_Red_Trunk', label: 'Giant Mushroom Red Trunk' },
  { id: 'Plant_Crop_Mushroom_Block_White', label: 'Giant Mushroom White' },
  { id: 'Plant_Crop_Mushroom_Block_White_Branch', label: 'Giant Mushroom White Branch' },
  { id: 'Plant_Crop_Mushroom_Block_White_Mycelium', label: 'Giant Mushroom White Mycelium' },
  { id: 'Plant_Crop_Mushroom_Block_White_Trunk', label: 'Giant Mushroom White Trunk' },
  { id: 'Plant_Crop_Mushroom_Block_Yellow', label: 'Giant Mushroom Yellow' },
  { id: 'Plant_Crop_Mushroom_Block_Yellow_Branch', label: 'Giant Mushroom Yellow Branch' },
  { id: 'Plant_Crop_Mushroom_Block_Yellow_Mycelium', label: 'Giant Mushroom Yellow Mycelium' },
  { id: 'Plant_Crop_Mushroom_Block_Yellow_Trunk', label: 'Giant Mushroom Yellow Trunk' },
  { id: 'Plant_Crop_Mushroom_Cap_Brown', label: 'Mushroom Cap Brown' },
  { id: 'Plant_Crop_Mushroom_Cap_Green', label: 'Mushroom Cap Green' },
  { id: 'Plant_Crop_Mushroom_Cap_Poison', label: 'Mushroom Cap Poison' },
  { id: 'Plant_Crop_Mushroom_Cap_Red', label: 'Mushroom Cap Red' },
  { id: 'Plant_Crop_Mushroom_Cap_White', label: 'Mushroom Cap White' },
  { id: 'Plant_Crop_Mushroom_Common_Blue', label: 'Mushroom Common Blue' },
  { id: 'Plant_Crop_Mushroom_Common_Brown', label: 'Mushroom Common Brown' },
  { id: 'Plant_Crop_Mushroom_Common_Lime', label: 'Mushroom Common Lime' },
  { id: 'Plant_Crop_Mushroom_Flatcap_Blue', label: 'Mushroom Flatcap Blue' },
  { id: 'Plant_Crop_Mushroom_Flatcap_Green', label: 'Mushroom Flatcap Green' },
  { id: 'Plant_Crop_Mushroom_Glowing_Blue', label: 'Glowing Mushroom Blue' },
  { id: 'Plant_Crop_Mushroom_Glowing_Green', label: 'Glowing Mushroom Green' },
  { id: 'Plant_Crop_Mushroom_Glowing_Orange', label: 'Glowing Mushroom Orange' },
  { id: 'Plant_Crop_Mushroom_Glowing_Purple', label: 'Glowing Mushroom Purple' },
  { id: 'Plant_Crop_Mushroom_Glowing_Red', label: 'Glowing Mushroom Red' },
  { id: 'Plant_Crop_Mushroom_Glowing_Violet', label: 'Glowing Mushroom Violet' },
  { id: 'Plant_Crop_Mushroom_Shelve_Brown', label: 'Shelf Mushroom Brown' },
  { id: 'Plant_Crop_Mushroom_Shelve_Green', label: 'Shelf Mushroom Green' },
  { id: 'Plant_Crop_Mushroom_Shelve_Yellow', label: 'Shelf Mushroom Yellow' },
  { id: 'Plant_Crop_Stamina1', label: 'Stamina Herb 1' },
  { id: 'Plant_Crop_Stamina2', label: 'Stamina Herb 2' },
  { id: 'Plant_Crop_Stamina3', label: 'Stamina Herb 3' },
  { id: 'Plant_Crop_Wheat_Stage_4_Burnt', label: 'Burnt Wheat' },
  { id: 'Plant_Fern_Jungle_Trunk', label: 'Jungle Fern Trunk' },
  { id: 'Plant_Fern_Wet_Giant', label: 'Giant Wet Fern' },
  { id: 'Plant_Fern_Wet_Giant_Trunk', label: 'Giant Wet Fern Trunk' },
  { id: 'Plant_Flower_Water_Blue', label: 'Water Flower Blue' },
  { id: 'Plant_Flower_Water_Duckweed', label: 'Duckweed' },
  { id: 'Plant_Flower_Water_Green', label: 'Water Flower Green' },
  { id: 'Plant_Flower_Water_Purple', label: 'Water Flower Purple' },
  { id: 'Plant_Flower_Water_Red', label: 'Water Flower Red' },
  { id: 'Plant_Flower_Water_White', label: 'Water Flower White' },
  { id: 'Plant_Fruit_Apple', label: 'Apple Tree Fruit' },
  { id: 'Plant_Fruit_Azure', label: 'Azure Fruit' },
  { id: 'Plant_Fruit_Coconut', label: 'Coconut' },
  { id: 'Plant_Fruit_Mango', label: 'Mango' },
  { id: 'Plant_Fruit_Pinkberry', label: 'Pinkberry' },
  { id: 'Plant_Fruit_Spiral', label: 'Spiral Fruit' },
  { id: 'Plant_Fruit_Windwillow', label: 'Windwillow Fruit' },
  { id: 'Plant_Grass_Arid', label: 'Arid Grass' },
  { id: 'Plant_Grass_Arid_Short', label: 'Arid Grass Short' },
  { id: 'Plant_Grass_Arid_Tall', label: 'Arid Grass Tall' },
  { id: 'Plant_Grass_Cave_Short', label: 'Cave Grass Short' },
  { id: 'Plant_Grass_Dry', label: 'Dry Grass' },
  { id: 'Plant_Grass_Dry_Tall', label: 'Dry Grass Tall' },
  { id: 'Plant_Grass_Gnarled', label: 'Gnarled Grass' },
  { id: 'Plant_Grass_Gnarled_Short', label: 'Gnarled Grass Short' },
  { id: 'Plant_Grass_Gnarled_Tall', label: 'Gnarled Grass Tall' },
  { id: 'Plant_Grass_Jungle', label: 'Jungle Grass' },
  { id: 'Plant_Grass_Jungle_Short', label: 'Jungle Grass Short' },
  { id: 'Plant_Grass_Jungle_Tall', label: 'Jungle Grass Tall' },
  { id: 'Plant_Grass_Lush', label: 'Lush Grass' },
  { id: 'Plant_Grass_Lush_Short', label: 'Lush Grass Short' },
  { id: 'Plant_Grass_Lush_Tall', label: 'Lush Grass Tall' },
  { id: 'Plant_Grass_Poisoned', label: 'Poisoned Grass' },
  { id: 'Plant_Grass_Poisoned_Short', label: 'Poisoned Grass Short' },
  { id: 'Plant_Grass_Rocky', label: 'Rocky Grass' },
  { id: 'Plant_Grass_Rocky_Short', label: 'Rocky Grass Short' },
  { id: 'Plant_Grass_Rocky_Tall', label: 'Rocky Grass Tall' },
  { id: 'Plant_Grass_Sharp', label: 'Sharp Grass' },
  { id: 'Plant_Grass_Sharp_Overgrown', label: 'Sharp Grass Overgrown' },
  { id: 'Plant_Grass_Sharp_Short', label: 'Sharp Grass Short' },
  { id: 'Plant_Grass_Sharp_Tall', label: 'Sharp Grass Tall' },
  { id: 'Plant_Grass_Sharp_Wild', label: 'Sharp Grass Wild' },
  { id: 'Plant_Grass_Snowy', label: 'Snowy Grass' },
  { id: 'Plant_Grass_Snowy_Short', label: 'Snowy Grass Short' },
  { id: 'Plant_Grass_Snowy_Tall', label: 'Snowy Grass Tall' },
  { id: 'Plant_Grass_Wet', label: 'Wet Grass' },
  { id: 'Plant_Grass_Wet_Overgrown', label: 'Wet Grass Overgrown' },
  { id: 'Plant_Grass_Wet_Short', label: 'Wet Grass Short' },
  { id: 'Plant_Grass_Wet_Tall', label: 'Wet Grass Tall' },
  { id: 'Plant_Grass_Wet_Wild', label: 'Wet Grass Wild' },
  { id: 'Plant_Grass_Winter', label: 'Winter Grass' },
  { id: 'Plant_Grass_Winter_Short', label: 'Winter Grass Short' },
  { id: 'Plant_Grass_Winter_Tall', label: 'Winter Grass Tall' },
  { id: 'Plant_Hay_Bundle', label: 'Hay Bundle' },
  { id: 'Plant_Lavender_Stage_0', label: 'Lavender' },
  { id: 'Plant_Leaves_Autumn', label: 'Autumn Leaves' },
  { id: 'Plant_Leaves_Bottle', label: 'Bottle Leaves' },
  { id: 'Plant_Leaves_Bramble', label: 'Bramble Leaves' },
  { id: 'Plant_Leaves_Burnt', label: 'Burnt Leaves' },
  { id: 'Plant_Leaves_Dead', label: 'Dead Leaves' },
  { id: 'Plant_Leaves_Dry', label: 'Dry Leaves' },
  { id: 'Plant_Leaves_Fir_Red', label: 'Red Fir Leaves' },
  { id: 'Plant_Leaves_Fir_Snow', label: 'Snowy Fir Leaves' },
  { id: 'Plant_Leaves_Goldentree', label: 'Golden Tree Leaves' },
  { id: 'Plant_Leaves_Gumboab', label: 'Gumboab Leaves' },
  { id: 'Plant_Leaves_Palm_Arid', label: 'Arid Palm Leaves' },
  { id: 'Plant_Leaves_Palm_Oasis', label: 'Oasis Palm Leaves' },
  { id: 'Plant_Leaves_Palo', label: 'Palo Leaves' },
  { id: 'Plant_Leaves_Petrified', label: 'Petrified Leaves' },
  { id: 'Plant_Leaves_Poisoned', label: 'Poisoned Leaves' },
  { id: 'Plant_Leaves_Rhododendron', label: 'Rhododendron Leaves' },
  { id: 'Plant_Leaves_Sallow', label: 'Sallow Leaves' },
  { id: 'Plant_Leaves_Snow', label: 'Snow Leaves' },
  { id: 'Plant_Leaves_Spiral', label: 'Spiral Leaves' },
  { id: 'Plant_Leaves_Stormbark', label: 'Stormbark Leaves' },
  { id: 'Plant_Leaves_Windwillow', label: 'Windwillow Leaves' },
  { id: 'Plant_Leaves_Wisteria_Wild', label: 'Wild Wisteria Leaves' },
  { id: 'Plant_Moss_Block_Blue', label: 'Moss Block Blue' },
  { id: 'Plant_Moss_Block_Green', label: 'Moss Block Green' },
  { id: 'Plant_Moss_Block_Green_Dark', label: 'Moss Block Dark Green' },
  { id: 'Plant_Moss_Block_Red', label: 'Moss Block Red' },
  { id: 'Plant_Moss_Block_Yellow', label: 'Moss Block Yellow' },
  { id: 'Plant_Moss_Blue', label: 'Blue Moss' },
  { id: 'Plant_Moss_Cave_Blue', label: 'Cave Moss Blue' },
  { id: 'Plant_Moss_Cave_Green', label: 'Cave Moss Green' },
  { id: 'Plant_Moss_Cave_Green_Dark', label: 'Cave Moss Dark Green' },
  { id: 'Plant_Moss_Cave_Red', label: 'Cave Moss Red' },
  { id: 'Plant_Moss_Cave_Yellow', label: 'Cave Moss Yellow' },
  { id: 'Plant_Moss_Green', label: 'Green Moss' },
  { id: 'Plant_Moss_Green_Dark', label: 'Dark Green Moss' },
  { id: 'Plant_Moss_Red', label: 'Red Moss' },
  { id: 'Plant_Moss_Rug_Blue', label: 'Moss Rug Blue' },
  { id: 'Plant_Moss_Rug_Green', label: 'Moss Rug Green' },
  { id: 'Plant_Moss_Rug_Green_Dark', label: 'Moss Rug Dark Green' },
  { id: 'Plant_Moss_Rug_Lime', label: 'Moss Rug Lime' },
  { id: 'Plant_Moss_Rug_Pink', label: 'Moss Rug Pink' },
  { id: 'Plant_Moss_Rug_Red', label: 'Moss Rug Red' },
  { id: 'Plant_Moss_Rug_Yellow', label: 'Moss Rug Yellow' },
  { id: 'Plant_Moss_Short_Blue', label: 'Short Moss Blue' },
  { id: 'Plant_Moss_Short_Green', label: 'Short Moss Green' },
  { id: 'Plant_Moss_Short_Green_Dark', label: 'Short Moss Dark Green' },
  { id: 'Plant_Moss_Short_Red', label: 'Short Moss Red' },
  { id: 'Plant_Moss_Short_Yellow', label: 'Short Moss Yellow' },
  { id: 'Plant_Moss_Wall_Blue', label: 'Wall Moss Blue' },
  { id: 'Plant_Moss_Wall_Green', label: 'Wall Moss Green' },
  { id: 'Plant_Moss_Wall_Green_Dark', label: 'Wall Moss Dark Green' },
  { id: 'Plant_Moss_Wall_Red', label: 'Wall Moss Red' },
  { id: 'Plant_Moss_Wall_Yellow', label: 'Wall Moss Yellow' },
  { id: 'Plant_Moss_Yellow', label: 'Yellow Moss' },
  { id: 'Plant_Reeds_Arid', label: 'Arid Reeds' },
  { id: 'Plant_Reeds_Lava', label: 'Lava Reeds' },
  { id: 'Plant_Reeds_Marsh', label: 'Marsh Reeds' },
  { id: 'Plant_Reeds_Poison', label: 'Poison Reeds' },
  { id: 'Plant_Reeds_Water', label: 'Water Reeds' },
  { id: 'Plant_Reeds_Wet', label: 'Wet Reeds' },
  { id: 'Plant_Reeds_Winter', label: 'Winter Reeds' },
  { id: 'Plant_Roots_Cave', label: 'Cave Roots' },
  { id: 'Plant_Roots_Cave_Small', label: 'Cave Roots Small' },
  { id: 'Plant_Roots_Leafy', label: 'Leafy Roots' },
  { id: 'Plant_Sapling_Amber', label: 'Amber Sapling' },
  { id: 'Plant_Sapling_Ash', label: 'Ash Sapling' },
  { id: 'Plant_Sapling_Aspen', label: 'Aspen Sapling' },
  { id: 'Plant_Sapling_Azure', label: 'Azure Sapling' },
  { id: 'Plant_Sapling_Bamboo', label: 'Bamboo Sapling' },
  { id: 'Plant_Sapling_Banyan', label: 'Banyan Sapling' },
  { id: 'Plant_Sapling_Beech', label: 'Beech Sapling' },
  { id: 'Plant_Sapling_Birch', label: 'Birch Sapling' },
  { id: 'Plant_Sapling_Bottletree', label: 'Bottletree Sapling' },
  { id: 'Plant_Sapling_Camphor', label: 'Camphor Sapling' },
  { id: 'Plant_Sapling_Cedar', label: 'Cedar Sapling' },
  { id: 'Plant_Sapling_Crystal', label: 'Crystal Sapling' },
  { id: 'Plant_Sapling_Dry', label: 'Dry Sapling' },
  { id: 'Plant_Sapling_Fig_Blue', label: 'Blue Fig Sapling' },
  { id: 'Plant_Sapling_Fire', label: 'Fire Sapling' },
  { id: 'Plant_Sapling_Gumboab', label: 'Gumboab Sapling' },
  { id: 'Plant_Sapling_Ice', label: 'Ice Sapling' },
  { id: 'Plant_Sapling_Jungle', label: 'Jungle Sapling' },
  { id: 'Plant_Sapling_Maple', label: 'Maple Sapling' },
  { id: 'Plant_Sapling_Oak', label: 'Oak Sapling' },
  { id: 'Plant_Sapling_Palm', label: 'Palm Sapling' },
  { id: 'Plant_Sapling_Palo', label: 'Palo Sapling' },
  { id: 'Plant_Sapling_Petrified', label: 'Petrified Sapling' },
  { id: 'Plant_Sapling_Poisoned', label: 'Poisoned Sapling' },
  { id: 'Plant_Sapling_Redwood', label: 'Redwood Sapling' },
  { id: 'Plant_Sapling_Sallow', label: 'Sallow Sapling' },
  { id: 'Plant_Sapling_Spiral', label: 'Spiral Sapling' },
  { id: 'Plant_Sapling_Spruce', label: 'Spruce Sapling' },
  { id: 'Plant_Sapling_Spruce_Frozen', label: 'Frozen Spruce Sapling' },
  { id: 'Plant_Sapling_Stormbark', label: 'Stormbark Sapling' },
  { id: 'Plant_Sapling_Windwillow', label: 'Windwillow Sapling' },
  { id: 'Plant_Sapling_Wisteria_Wild', label: 'Wild Wisteria Sapling' },
  { id: 'Plant_Seaweed_Arid_Red', label: 'Arid Seaweed Red' },
  { id: 'Plant_Seaweed_Arid_Short', label: 'Arid Seaweed Short' },
  { id: 'Plant_Seaweed_Arid_Stack', label: 'Arid Seaweed Stack' },
  { id: 'Plant_Seaweed_Arid_Tall', label: 'Arid Seaweed Tall' },
  { id: 'Plant_Seaweed_Arid_Yellow', label: 'Arid Seaweed Yellow' },
  { id: 'Plant_Seaweed_Dead_Eerie', label: 'Eerie Dead Seaweed' },
  { id: 'Plant_Seaweed_Dead_Ghostly', label: 'Ghostly Dead Seaweed' },
  { id: 'Plant_Seaweed_Dead_Short', label: 'Dead Seaweed Short' },
  { id: 'Plant_Seaweed_Dead_Stack', label: 'Dead Seaweed Stack' },
  { id: 'Plant_Seaweed_Dead_Tall', label: 'Dead Seaweed Tall' },
  { id: 'Plant_Seaweed_Grass', label: 'Grass Seaweed' },
  { id: 'Plant_Seaweed_Grass_Bulbs', label: 'Grass Seaweed Bulbs' },
  { id: 'Plant_Seaweed_Grass_Green', label: 'Green Grass Seaweed' },
  { id: 'Plant_Seaweed_Grass_Short', label: 'Grass Seaweed Short' },
  { id: 'Plant_Seaweed_Grass_Stack', label: 'Grass Seaweed Stack' },
  { id: 'Plant_Seaweed_Grass_Tall', label: 'Grass Seaweed Tall' },
  { id: 'Plant_Seaweed_Wet_Stack', label: 'Wet Seaweed Stack' },
  { id: 'Plant_Seaweed_Winter_Aurora', label: 'Aurora Winter Seaweed' },
  { id: 'Plant_Seaweed_Winter_Blue', label: 'Blue Winter Seaweed' },
  { id: 'Plant_Seaweed_Winter_Short', label: 'Winter Seaweed Short' },
  { id: 'Plant_Seaweed_Winter_Stack', label: 'Winter Seaweed Stack' },
  { id: 'Plant_Seaweed_Winter_Tall', label: 'Winter Seaweed Tall' },
  { id: 'Plant_Seeds_Pine', label: 'Pine Seeds' },
  { id: 'Plant_Sunflower_Stage_0', label: 'Sunflower' },
  { id: 'Plant_Vine', label: 'Vine' },
  { id: 'Plant_Vine_Green_Hanging', label: 'Green Hanging Vine' },
  { id: 'Plant_Vine_Hanging', label: 'Hanging Vine' },
  { id: 'Plant_Vine_Jungle', label: 'Jungle Vine' },
  { id: 'Plant_Vine_Liana', label: 'Liana Vine' },
  { id: 'Plant_Vine_Liana_End', label: 'Liana Vine End' },
  { id: 'Plant_Vine_Red_Hanging', label: 'Red Hanging Vine' },
  { id: 'Plant_Vine_Rug', label: 'Vine Rug' },
  { id: 'Plant_Vine_Wall', label: 'Wall Vine' },
  { id: 'Plant_Vine_Wall_Dead', label: 'Dead Wall Vine' },
  { id: 'Plant_Vine_Wall_Dry', label: 'Dry Wall Vine' },
  { id: 'Plant_Vine_Wall_Poisoned', label: 'Poisoned Wall Vine' },
  { id: 'Plant_Vine_Wall_Winter', label: 'Winter Wall Vine' },
  { id: 'Teleporter', label: 'Teleporter' },
  { id: 'Template_Fruit', label: 'Template Fruit' },
  { id: 'Wood_Sticks', label: 'Wood Sticks' },
]

// ─── All blocks (for block template editor picker) ──────────────────

// ALL blocks across every category
export const ALL_BLOCKS = [
  ...WOOD_BLOCKS.map((b) => ({ ...b, category: 'WOOD' })),
  ...ORE_BLOCKS.map((b) => ({ ...b, category: 'ORE' })),
  ...PLANT_BLOCKS.map((b) => ({ ...b, category: 'PLANT' })),
  ...SOIL_BLOCKS.map((b) => ({ ...b, category: 'SOIL' })),
  ...RUBBLE_BLOCKS.map((b) => ({ ...b, category: 'RUBBLE' })),
  ...DECO_BLOCKS.map((b) => ({ ...b, category: 'DECO' })),
  ...FURNITURE_BLOCKS.map((b) => ({ ...b, category: 'FURNITURE' })),
  ...MISC_BLOCKS.map((b) => ({ ...b, category: 'MISC' })),
]

// Fast lookup: block ID → label
export const ALL_BLOCKS_MAP: Record<string, string> = Object.fromEntries(ALL_BLOCKS.map((b) => [b.id, b.label]))
