import { COSMETICS_CATEGORY } from '../game/item_classification'

export const ITEM_CATEGORIES = [
  'ALL',
  'HELMET',
  'CHESTPLATE',
  'BELT',
  'GAUNTLETS',
  'PANTS',
  'BOOTS',
  'LONGSWORD',
  'DAGGERS',
  'BOW',
  'STAFF',
  'AXE',
  'SPELLBOOK',
  'BATTLEAXE',
  'SWORD',
  'CLUB',
  'MACE',
  'SPEAR',
  'AMULET',
  'RING',
  COSMETICS_CATEGORY,
  'PET',
  'RELIC',
  'TOOL_HERBALIST',
  'TOOL_PAYSAN',
  'TOOL_MINER',
  'CONSUMABLE',
  'RESOURCE',
  'RUNE',
] as const

export const FILTERABLE_STATS = [
  'strength',
  'intelligence',
  'agility',
  'chance',
  'wisdom',
  'vitality',
  'rawDamage',
  'criticalHit',
  'heal',
  'stamina',
  'earthResistance',
  'fireResistance',
  'waterResistance',
  'airResistance',
] as const

export const CATEGORY_GROUPS = {
  ALL: null,
  ARMOR: new Set(['HELMET', 'CHESTPLATE', 'BELT', 'GAUNTLETS', 'PANTS', 'BOOTS']),
  WEAPONS: new Set([
    'LONGSWORD',
    'DAGGERS',
    'BOW',
    'STAFF',
    'AXE',
    'SPELLBOOK',
    'BATTLEAXE',
    'SWORD',
    'CLUB',
    'MACE',
    'SPEAR',
  ]),
  ACCESSORIES: new Set(['AMULET', 'RING']),
  COSMETICS: new Set([COSMETICS_CATEGORY]),
  PETS: new Set(['PET']),
  RUNES: new Set(['RUNE']),
  RELICS: new Set(['RELIC']),
  TOOLS: new Set(['TOOL_HERBALIST', 'TOOL_PAYSAN', 'TOOL_MINER']),
  CONSUMABLES: new Set(['CONSUMABLE']),
  RESOURCES: new Set(['RESOURCE']),
} as const

export type CategoryGroupKey = keyof typeof CATEGORY_GROUPS

export const SORT_OPTIONS = ['level_asc', 'level_desc', 'name_asc', 'newest'] as const
export type SortOption = (typeof SORT_OPTIONS)[number]

export const MOB_LEVEL_BRACKETS = [
  { label: '1-20', min: 1, max: 20 },
  { label: '21-50', min: 21, max: 50 },
  { label: '51-80', min: 51, max: 80 },
  { label: '81-120', min: 81, max: 120 },
  { label: '121+', min: 121, max: Infinity },
] as const

export const ELEMENTS = ['EARTH', 'FIRE', 'WATER', 'AIR'] as const

export const MOB_FAMILIES: Record<string, string[]> = {
  Wool: [
    'wooling',
    'wooligan',
    'hornhead',
    'chief_wooligan',
    'magmooligan',
    'woolice',
    'ramrage',
    'eternwool',
    'woolkin_celestial',
    'wanilla_the_pretty',
    'woolly_doom',
    'ramrage_eternal',
  ],
  Razmo: [
    'razkin',
    'razmo',
    'great_razmo',
    'razord',
    'plaguemo',
    'razmaster',
    'plague_razmo',
    'razlord_prime',
    'razmo_the_plague_king',
    'razmo_the_crowned',
    'cinderwhisker',
  ],
  Koa: [
    'koaletin',
    'koa',
    'koard',
    'koagulant',
    'koloss',
    'firekoa',
    'frostkoa',
    'titan_koa',
    'primordial_koa',
    'koa_the_bloated',
    'koa_the_eternal',
    'ditch_koaletin',
    'swamp_firekoa',
  ],
  Silk: [
    'silkling',
    'zephyr_silkweaver',
    'ember_silkweaver',
    'zephyr_silklord',
    'frost_silkweaver',
    'cocoon_king',
    'silklord_ageless',
    'golden_silkling',
    'golden_matron',
    'silk_warden',
    'wallow_grub',
  ],
  Hollow: [
    'green_walker',
    'strawman',
    'burnt_effigy',
    'sandwraith',
    'moldrot',
    'palebones',
    'frostshamble',
    'aberrant_hulk',
    'risen_prime',
    'hollow_sovereign',
    'hanged_effigy',
    'the_first_hollow',
  ],
  Bonekin: [
    'bonelet',
    'nerakling_marrow',
    'draugr_retarded',
    'boneguard',
    'shadow_knight',
    'bonegorger',
    'boneherald',
    'pale_mare',
    'dread_lancer',
    'bonelord',
    'deathless_paragon',
    'sir_rattlebone',
    'sir_deathless',
    'bone_choir',
    'cinder_bonelord',
    'marrow_acolyte',
    'sand_lich',
    'drowned_buccaneer',
    'hades_keeper',
    'the_silent_abbot',
    'nerak_the_marrow_king',
  ],
  Goblin: [
    'goblin_runt',
    'goblin_crazy',
    'goblin_green',
    'goblin_brute',
    'gopnik',
    'gobadoc',
    'goblin_duke',
    'gopnik_blyat',
    'firegoblin',
    'goblin_sous_chef',
    'goblin_taster',
    'duke_the_insolvent',
    'gobadoc_the_starved',
    'cauldron_imp',
  ],
  Wolf: [
    'wolfling',
    'timber_wolf',
    'grimfang',
    'emberwulf',
    'frostwolf',
    'moonfang_alpha',
    'moonfang_ancient',
    'fenrik_the_moonlit',
    'fenrik_dire',
    'flarewolf',
  ],
  Crab: [
    'scuttler',
    'shore_crab',
    'hermitude',
    'clawlord',
    'magmaclaw',
    'frostclaw',
    'titan_claw',
    'sunken_claw',
    'crabito_the_drowned',
    'crabito_the_crowned',
    'ensable_hatchling',
    'ensable_warden',
  ],
  Gecko: ['tikling', 'tokek', 'sandskip', 'cendroling', 'armorscale', 'tokek_sunking', 'obsidian_tokek'],
  Spider: [
    'webling',
    'aragog_child',
    'weaver',
    'broodling',
    'widow_matron',
    'magmaweaver',
    'white_widow',
    'spinner_prime',
    'crater_queen',
    'pale_weaver',
    'empress_of_widows',
    'aragog_mother',
    'aragog_spawnling',
    'widow_consort',
    'widow_of_widows',
  ],
  Scarak: [
    'young_parasite',
    'parasite',
    'scarak_louse',
    'scarak_fighter',
    'scarak_defender',
    'scarak_seeker',
    'scarak_overlord',
    'broodfather',
    'scarak_hive_prime',
    'scarak_broodmother',
  ],
  Tusker: [
    'piglet',
    'tusklet',
    'boar',
    'warthog',
    'phacochson',
    'phacochef',
    'bisonbrute',
    'ancient_tusk',
    'mammoth_king',
    'tuskarr_the_oldest',
    'tuskarr_the_eternal',
    'runt_piglet',
    'pyre_warthog',
    'phacoch_cultist',
  ],
  Kweebec: [
    'sproutkin',
    'seedkin',
    'sapling_warden',
    'heartwood_ancient',
    'rootlord_ancient',
    'elder_kweebec',
    'ember_kweebec',
    'kweebec_grove_heart',
    'kweebec_heartwood',
  ],
  Void: [
    'void_crawler',
    'void_eye',
    'void_spawn',
    'void_necromancer',
    'void_spectre',
    'void_spawnling',
    'forge_of_souls',
  ],
  Pyre: [
    'sparkling',
    'flareling',
    'firesteel_golem',
    'pyre_titan',
    'cinder_tyrant',
    'pyre_ember_king',
    'pyre_seraph',
    'pyre_wraith',
    'forge_golem',
    'lava_serpent',
  ],
  Frost: ['frostling', 'yeti', 'crystal_golem', 'glacial_sovereign', 'yeti_immortal', 'yeti_the_deathless'],
  Wildling: ['wildling_spear', 'wildling_huntress', 'bjorn', 'wildlord', 'noggin_the_chief', 'wildlord_bjorn_prime'],
  Corvid: [
    'pecker',
    'sparrowdart',
    'campcaw',
    'bannerwatch',
    'thunder_owl',
    'shadow_vulture',
    'stormhawk',
    'thunderlord',
    'tempest_lord',
    'thunderscorn',
    'pecker_the_widow',
    'gull_campcaw',
    'emberbat',
  ],
  Reptilian: [
    'raptor_cave',
    'ashraptor',
    'archaeo',
    'pterodon',
    'rex_alpha',
    'trillo',
    'rex_primordial',
    'primal_tyrant',
    'rex_the_elder',
    'rex_the_world_eater',
  ],
  Dragon: ['dragon_fire', 'dragon_frost', 'dragon_void', 'dragon_acolyte', 'dragon_egg'],
  Slothian: [
    'slothling',
    'slothmaster',
    'elder_sloth',
    'ancient_hermit',
    'patient_elder',
    'nerak_priest',
    'yurei_abbot',
  ],
  Saurian: ['saurian_scout', 'saurian_warden', 'saurian_warlord', 'saurian_god_king'],
  Talokan: ['talokan_aero', 'wild_talokan', 'talokan_feu', 'talokan_tidelord', 'talokan_ancient'],
  Fen: ['swamp_sentinel', 'snapjaw', 'fen_stalker', 'fen_dread', 'mire_titan', 'fen_the_silent', 'tentacle_horror'],
  'Aquatic Swarm': [
    'pike',
    'piranha_school',
    'shark_hammer',
    'flying_fish',
    'deep_leviathan',
    'kraken_apex',
    'piranha_black_king',
    'piranha_tyrant',
    'reef_pike',
    'abyss_eel',
    'kraken_leviathan',
  ],
  Feran: [
    'feran_cub',
    'feran_scout',
    'feran_elder_warrior',
    'moonclaw_empress',
    'feran_the_whisperer',
    'nine_tails_kitsune',
    'stray_kit',
  ],
  'Apex Bears': ['grizzly', 'sabertooth', 'polar_reaver', 'titan_bear', 'saberfang_ageless', 'grizzly_the_undying'],
  Wraith: [
    'wraithling',
    'lantern_wraith',
    'banner_wraith',
    'soulking',
    'soulless_regent',
    'abbot_of_ends',
    'truffle_wraith',
    'banner_of_silence',
  ],
  Critters: [
    'alley_bunny',
    'plaza_pecker',
    'cluckling',
    'goldhen_matilda',
    'grainfox',
    'wheat_slither',
    'glass_snail',
    'magmalug',
    'magmalug_the_gorged',
    'snapthorn_weak',
    'protector_diamond',
  ],
}

export const MOB_ID_TO_FAMILY: Record<string, string> = Object.fromEntries(
  Object.entries(MOB_FAMILIES).flatMap(([family, ids]) => ids.map((id) => [id, family]))
)
