import minecraftData from 'minecraft-data'

import { VERSION } from './settings.js'

const {
  blocksByName: { ladder, vine },
} = minecraftData(VERSION)

const to_tag_array = tags =>
  Object.entries(tags).map(([tagName, entries]) => ({ tagName, entries }))

export const BLOCK_TAGS = to_tag_array({
  'minecraft:climbable': [ladder.id, vine.id],
  'minecraft:enderman_holdable': [],
  'minecraft:banners': [],
  'minecraft:soul_fire_base_blocks': [],
  'minecraft:campfires': [],
  'minecraft:infiniburn_nether': [],
  'minecraft:flower_pots': [],
  'minecraft:infiniburn_overworld': [],
  'minecraft:wooden_fences': [],
  'minecraft:piglin_repellents': [],
  'minecraft:wall_post_override': [],
  'minecraft:wooden_slabs': [],
  'minecraft:portals': [],
  'minecraft:small_flowers': [],
  'minecraft:bamboo_plantable_on': [],
  'minecraft:wooden_trapdoors': [],
  'minecraft:pressure_plates': [],
  'minecraft:jungle_logs': [],
  'minecraft:wooden_stairs': [],
  'minecraft:spruce_logs': [],
  'minecraft:signs': [],
  'minecraft:carpets': [],
  'minecraft:base_stone_overworld': [],
  'minecraft:wool': [],
  'minecraft:wooden_buttons': [],
  'minecraft:stairs': [],
  'minecraft:wither_summon_base_blocks': [],
  'minecraft:logs': [],
  'minecraft:stone_bricks': [],
  'minecraft:hoglin_repellents': [],
  'minecraft:fire': [],
  'minecraft:beehives': [],
  'minecraft:ice': [],
  'minecraft:base_stone_nether': [],
  'minecraft:dragon_immune': [],
  'minecraft:crops': [],
  'minecraft:wall_signs': [],
  'minecraft:slabs': [],
  'minecraft:valid_spawn': [],
  'minecraft:mushroom_grow_block': [],
  'minecraft:guarded_by_piglins': [],
  'minecraft:wooden_doors': [],
  'minecraft:warped_stems': [],
  'minecraft:standing_signs': [],
  'minecraft:infiniburn_end': [],
  'minecraft:trapdoors': [],
  'minecraft:crimson_stems': [],
  'minecraft:buttons': [],
  'minecraft:flowers': [],
  'minecraft:corals': [],
  'minecraft:prevent_mob_spawning_inside': [],
  'minecraft:wart_blocks': [],
  'minecraft:planks': [],
  'minecraft:soul_speed_blocks': [],
  'minecraft:dark_oak_logs': [],
  'minecraft:rails': [],
  'minecraft:coral_plants': [],
  'minecraft:non_flammable_wood': [],
  'minecraft:leaves': [],
  'minecraft:walls': [],
  'minecraft:coral_blocks': [],
  'minecraft:beacon_base_blocks': [],
  'minecraft:strider_warm_blocks': [],
  'minecraft:fence_gates': [],
  'minecraft:bee_growables': [],
  'minecraft:shulker_boxes': [],
  'minecraft:wooden_pressure_plates': [],
  'minecraft:wither_immune': [],
  'minecraft:acacia_logs': [],
  'minecraft:anvil': [],
  'minecraft:birch_logs': [],
  'minecraft:tall_flowers': [],
  'minecraft:wall_corals': [],
  'minecraft:underwater_bonemeals': [],
  'minecraft:stone_pressure_plates': [],
  'minecraft:impermeable': [],
  'minecraft:sand': [],
  'minecraft:nylium': [],
  'minecraft:gold_ores': [],
  'minecraft:logs_that_burn': [],
  'minecraft:fences': [],
  'minecraft:saplings': [],
  'minecraft:beds': [],
  'minecraft:oak_logs': [],
  'minecraft:unstable_bottom_center': [],
  'minecraft:doors': [],
})

export const ITEM_TAGS = to_tag_array({
  'minecraft:banners': [],
  'minecraft:soul_fire_base_blocks': [],
  'minecraft:stone_crafting_materials': [],
  'minecraft:wooden_fences': [],
  'minecraft:piglin_repellents': [],
  'minecraft:beacon_payment_items': [],
  'minecraft:wooden_slabs': [],
  'minecraft:small_flowers': [],
  'minecraft:wooden_trapdoors': [],
  'minecraft:jungle_logs': [],
  'minecraft:lectern_books': [],
  'minecraft:wooden_stairs': [],
  'minecraft:spruce_logs': [],
  'minecraft:signs': [],
  'minecraft:carpets': [],
  'minecraft:wool': [],
  'minecraft:wooden_buttons': [],
  'minecraft:stairs': [],
  'minecraft:fishes': [],
  'minecraft:logs': [],
  'minecraft:stone_bricks': [],
  'minecraft:creeper_drop_music_discs': [],
  'minecraft:arrows': [],
  'minecraft:slabs': [],
  'minecraft:wooden_doors': [],
  'minecraft:warped_stems': [],
  'minecraft:trapdoors': [],
  'minecraft:crimson_stems': [],
  'minecraft:buttons': [],
  'minecraft:flowers': [],
  'minecraft:stone_tool_materials': [],
  'minecraft:planks': [],
  'minecraft:boats': [],
  'minecraft:dark_oak_logs': [],
  'minecraft:rails': [],
  'minecraft:non_flammable_wood': [],
  'minecraft:leaves': [],
  'minecraft:walls': [],
  'minecraft:coals': [],
  'minecraft:wooden_pressure_plates': [],
  'minecraft:acacia_logs': [],
  'minecraft:anvil': [],
  'minecraft:piglin_loved': [],
  'minecraft:music_discs': [],
  'minecraft:birch_logs': [],
  'minecraft:tall_flowers': [],
  'minecraft:sand': [],
  'minecraft:gold_ores': [],
  'minecraft:logs_that_burn': [],
  'minecraft:fences': [],
  'minecraft:saplings': [],
  'minecraft:beds': [],
  'minecraft:oak_logs': [],
  'minecraft:doors': [],
})

export const FLUID_TAGS = to_tag_array({
  'minecraft:lava': [],
  'minecraft:water': [],
})

export const ENTITY_TAGS = to_tag_array({
  'minecraft:skeletons': [],
  'minecraft:raiders': [],
  'minecraft:arrows': [],
  'minecraft:beehive_inhabitors': [],
  'minecraft:impact_projectiles': [],
})
