// SPDX-License-Identifier: LicenseRef-AresRPG-Source-Available
// © 2026 Sceat — All rights reserved. See LICENSE.
// #1743 instrument — the Move verdict is transcribed from engine/sources/actions.move + tackle.move and
// foundation/sources/spell_formula.move. It is intentionally not generated by the sim.

export const tackle_rollback_parity = {
  clock: {
    world_seed: 12345,
    spawn_id: 1,
    turn_entropy: 0,
    turn_ordinal: 2,
    seat: 0,
    slot: 0,
  },
  runner: {
    id: 'runner',
    cell: { x: 3, y: 3 },
    agility: 0,
    ap: 6,
    mp: 3,
  },
  lockers: [
    { id: 'locker_north', cell: { x: 3, y: 2 }, agility: 0 },
    { id: 'locker_west', cell: { x: 2, y: 3 }, agility: 0 },
  ],
  attempted_path: [
    { x: 4, y: 3 },
    { x: 5, y: 3 },
  ],
  move_verdict: {
    path_cost: 2,
    dodge: 2,
    locker_denominators: [4, 4],
    num: 4,
    den: 16,
    turn_seed: 1595451561,
    tackle_seed: 1361970538,
    draw: 1561039407,
    roll: 15,
    escaped: false,
    allowed_cells: [{ x: 3, y: 3 }],
    mp_after: 0,
    mp_spent: 3,
    attempted_movement_rolled_back: true,
  },
}
