// SPDX-License-Identifier: LicenseRef-AresRPG-Source-Available
// © 2026 Sceat — All rights reserved. See LICENSE.

export type KaresCopy = Readonly<{
  stake_more: string
  additional_daily: string
  max: string
  external_wallet_hint: string
  select_wallet: string
  staking_revenue: string
  game_account: string
  external_wallet: string
  daily_kares: string
  daily_sui: string
  daily_estimate_note: string
  position_rewards: string
  manage_stake: string
  same_account: string
  close: string
  launch_market_cap: string
  launch_market_cap_note: string
  combat_rewards: string
  combat_detail: string
  allocation_rationale: string
  vested_five_years: string
  unlocked_immediately: string
  sale_unlock_note: string
  community_release_note: string
  sale_card_soon_title: string
  sale_card_soon_note: string
  sale_card_soon_action: string
  sale_card_live_label: string
  sale_card_live_title: string
  sale_card_target_reached: string
  sale_card_done_title: string
  sale_card_done_note: string
  sale_card_refund_note: string
  basecamp_announcement: string
  funding_unknown: string
  success_threshold: string
  sale_cap: string
  cap_overflow: string
  overflow_refunds: string

  stage_minimum: string
  stage_maximum: string
  minimum_refund: string
  full_refund_available: string
  refund_claim_note: string

  nav_funding: string
  nav_benefits: string
  nav_tokenomics: string
  nav_incentives: string
  nav_play: string
  benefits_title: string
  benefits_lead: string
  revenue_title: string
  revenue_metric: string
  revenue_detail: string
  baseline_title: string
  baseline_detail: string
  crates_title: string
  crates_detail: string
  incentives_title: string
  incentives_detail: string
  incentives_clock: string
  incentives_examples: string
  play_title: string
  play_detail: string

  awaiting_minimum: string
  claimable_tokens: string
  refundable_sui: string
  final_price: string
  full_refund: string

  min_marker: string
  max_marker: string
  min_reached: string
  min_pending: string
  oversubscribed: string
  subscribed: string
  oversub_note: string
  opens_in: string
  closes_in: string
  days_short: string
  your_investment: string
  your_allocation: string
  current_price: string
  estimated_until_close: string
  accepted_contribution: string
  excess_refund: string
  unclaimed_note: string
  connect_preview: string
  no_pending_allocation: string
  play_game: string
  play_game_note: string
  join_title: string
  join_note: string
  step_connect: string
  step_contribute: string
  step_claim: string
  allocation_lead: string
  community_detail: string
  supply_detail: string
  emissions_detail: string
  price_cap_note: string

  eyebrow: string
  launch_title: string
  launch_lead: string
  offering: string
  refund_note: string
  offering_contract: string
  fixed_supply: string
  fair_share: string
  fair_detail: string
  connect: string
  disconnect: string
  choose_account: string
  no_wallet: string
  refresh: string
  loading: string
  unavailable: string
  staking_unavailable: string
  pending: string
  confirmed: string
  confirmed_refresh: string
  contribute: string
  amount: string
  balance: string
  amount_invalid: string
  insufficient: string
  gas_note: string
  raised: string
  minimum: string
  maximum: string
  opens: string
  closes: string
  estimate: string
  price_note: string
  your_contribution: string
  claim: string
  claim_kares: string
  refund: string
  upcoming: string
  open: string
  successful: string
  refundable: string
  testnet: string
  back_game: string
  funding_title: string
  liquidity: string
  development: string
  liquidity_note: string
  development_note: string
  staking_title: string
  staking_lead: string
  pool_stake: string
  your_stake: string
  claimable: string
  stake: string
  withdraw: string
  claim_rewards: string
  fund_title: string
  fund_note: string
  donate: string
  no_positions: string
  inactive: string
  account_label: string
  position: string
  tokenomics: string
  community: string
  team: string
  five_years: string
  mastery_title: string
  mastery_note: string
  rewards_note: string
  revenue_note: string
  payment: string
  points: string
  burn_buy: string
  kares_missing: string
  language: string
}>
