// SPDX-License-Identifier: LicenseRef-AresRPG-Source-Available
// © 2026 Sceat — All rights reserved. See LICENSE.
import type { ErrorCopy } from '../i18n/error_text.ts'
export type KaresCopy = ErrorCopy &
  Readonly<{
    upgradeability_note: string
    blast_soon: string
    blast_live: string
    blast_closing: string
    blast_funded: string
    blast_complete: string
    blast_cancelled: string
    blast_loading: string
    blast_unavailable: string
    blast_note: string
    blast_action: string
    blast_progress: string
    stake_more: string
    additional_daily: string
    max: string
    external_wallet_hint: string
    select_wallet: string
    staking_revenue: string
    game_account: string
    external_wallet: string
    daily_kares: string
    daily_sui: string
    daily_estimate_note: string
    manage_stake: string
    same_account: string
    close: string
    combat_rewards: string
    combat_detail: string
    vested_five_years: string
    community_release_note: string
    community_detail: string
    supply_detail: string
    emissions_detail: string
    fixed_supply: string
    connect: string
    disconnect: string
    no_wallet: string
    refresh: string
    loading: string
    staking_unavailable: string
    pending: string
    confirmed: string
    confirmed_refresh: string
    amount: string
    balance: string
    amount_invalid: string
    insufficient: string
    gas_note: string
    testnet: string
    back_game: string
    staking_title: string
    your_stake: string
    claimable: string
    stake: string
    withdraw: string
    claim_rewards: string
    claim_batch: string
    withdraw_batch: string
    inactive: string
    position: string
    unallocated_supply: string
    tokenomics: string
    community: string
    team: string
    five_years: string
    mastery_title: string
    mastery_note: string
    rewards_note: string
    revenue_note: string
    points: string
    buy_kares: string
    kares_missing: string
    language: string
  }>
